-- MIT. Actual futures under the existing viewer principal; no input-loop waits.
local test = require("test")
local funcs = require("funcs")
local security = require("security")
local channel = require("channel")
local driver = require("driver")
local reader = require("reader")
local harness = require("harness")
local function define_tests()
    test.describe("Asynchronous session status", function()
        test.it("yields between operations and cancels a rebound watch", function()
            local alice = harness.principal("bee.test.status_async", harness.ALL)
            local id = harness.thread(alice, "Async status")
            local policy, policy_error = security.policy("bee.threads:client_test_policy")
            if not policy then error(tostring(policy_error)) end
            local scope = security.new_scope({policy})
            local actor = security.new_actor("bee.test.status_async")
            local calls = 0
            local state = driver.new(function(intent: reader.Intent): (funcs.Future?, string?)
                calls = calls + 1
                local future, err = funcs.new():with_actor(actor):with_scope(scope):async(intent.target, intent.request)
                if err then return nil, tostring(err) end
                return future, nil
            end)
            driver.bind(state, id, 0)
            reader.lost(state.reader)
            local first = assert(driver.advance(state, harness.key(), 0))
            test.eq(calls, 1)
            test.eq(driver.advance(state, harness.key(), 0), first)
            test.eq(calls, 1)
            channel.select({first.response:case_receive()})
            test.is_true(driver.complete(state, first, 1))
            test.is_nil(driver.advance(state, harness.key(), 1))
            local read = assert(driver.advance(state, harness.key(), 2))
            channel.select({read.response:case_receive()})
            test.is_true(driver.complete(state, read, 3))
            test.eq(state.reader.availability, "ready")
            local watch = assert(driver.advance(state, harness.key(), 4))
            test.eq(watch.phase, "watch")
            driver.bind(state, nil, 5)
            test.is_nil(state.pending)
            test.eq(state.reader.availability, "unbound")
            test.is_false(driver.complete(state, watch, 6))
            driver.close(state)
            test.is_nil(driver.advance(state, harness.key(), 100000))
        end)
        test.it("backs off rejected admission without claiming idle", function()
            local calls = 0
            local state = driver.new(function(_: reader.Intent): (funcs.Future?, string?)
                calls = calls + 1
                return nil, "rejected"
            end)
            driver.bind(state, "unreachable", 0)
            test.is_nil(driver.advance(state, "k1", 0))
            test.eq(state.reader.availability, "unavailable")
            test.is_nil(driver.advance(state, "k2", driver.RETRY_MS - 1))
            test.eq(calls, 1)
            test.is_nil(driver.advance(state, "k3", driver.RETRY_MS))
            test.eq(calls, 2)
            driver.close(state)
        end)
    end)
end
return require("test").run_cases(define_tests)
