-- MIT. The generated Codex provider configuration: exact provider decoding,
-- the reviewed fields only, TOML string escaping, the endpoint as a
-- credential destination, and a stable measurement.
local test = require("test")
local configuration = require("configuration")
local function provider(data: {[string]: unknown}): {[string]: unknown}
    return {id = "host:provider", kind = "registry.entry", meta = {type = "bee.codex_provider"}, data = data}
end
local function define_tests()
    test.describe("Codex configuration", function()
        test.it("renders only the reviewed fields for a host provider and measures them", function()
            local decoded, err = configuration.decode("host:provider", provider({schema_revision = "bee.codex-provider@1", name = "bee", base_url = "https://gateway.example.net/v1", model = "gpt-5", reasoning_effort = "high", developer_instructions = "Answer tersely. Keep the \"host\" boundary.\n"}))
            if not decoded then error(tostring(err)) end
            test.eq(#decoded.digest, 64)
            local projection = assert(configuration.projection(decoded))
            test.eq(projection.path, ".codex/config.toml")
            test.eq(projection.revision, "bee.codex-config@1")
            test.is_true(projection.content:find('model_provider = "bee"', 1, true) ~= nil)
            test.is_true(projection.content:find('model_reasoning_effort = "high"', 1, true) ~= nil)
            test.is_true(projection.content:find('developer_instructions = "Answer tersely. Keep the \\"host\\" boundary.\\n"', 1, true) ~= nil)
            test.is_true(projection.content:find('[model_providers.bee]', 1, true) ~= nil)
            test.is_true(projection.content:find('env_key = "OPENAI_API_KEY"', 1, true) ~= nil)
            test.is_true(projection.content:find('wire_api = "responses"', 1, true) ~= nil)
            test.is_true(projection.content:find('base_url = "https://gateway.example.net/v1"', 1, true) ~= nil)
            test.eq(#projection.digest, 64)
            local again = assert(configuration.projection(decoded))
            test.eq(again.digest, projection.digest)
            decoded.developer_instructions = "Use a different host policy."
            local changed = assert(configuration.projection(decoded))
            test.neq(changed.digest, projection.digest)
            test.is_true(changed.content:find("Use a different host policy.", 1, true) ~= nil)
        end)
        test.it("escapes strings and refuses arbitrary fields, bad names and non-loopback http", function()
            local quoted = configuration.render({ref = "host:provider", name = "bee", base_url = 'https://h.example/v1"x', model = "gpt-5", loopback_fixture = false, digest = string.rep("0", 64)})
            test.is_true(quoted:find('base_url = "https://h.example/v1\\"x"', 1, true) ~= nil)
            local _, extra = configuration.decode("host:provider", provider({schema_revision = "bee.codex-provider@1", name = "bee", base_url = "https://h.example/v1", model = "gpt-5", include = "x"}))
            test.eq(extra, "host:provider: unknown field include")
            local _, guessed_instructions = configuration.decode("host:provider", provider({schema_revision = "bee.codex-provider@1", name = "bee", base_url = "https://h.example/v1", model = "gpt-5", model_instructions = "ignored"}))
            test.eq(guessed_instructions, "host:provider: unknown field model_instructions")
            local _, effort = configuration.decode("host:provider", provider({schema_revision = "bee.codex-provider@1", name = "bee", base_url = "https://h.example/v1", model = "gpt-5", reasoning_effort = "turbo"}))
            test.eq(effort, "host:provider: reasoning_effort must be low, medium, high, xhigh or max")
            local _, empty_instructions = configuration.decode("host:provider", provider({schema_revision = "bee.codex-provider@1", name = "bee", base_url = "https://h.example/v1", model = "gpt-5", developer_instructions = ""}))
            test.eq(empty_instructions, "host:provider: developer_instructions must be bounded nonempty text without unsupported control bytes")
            local _, large_instructions = configuration.decode("host:provider", provider({schema_revision = "bee.codex-provider@1", name = "bee", base_url = "https://h.example/v1", model = "gpt-5", developer_instructions = string.rep("x", configuration.MAX_DEVELOPER_INSTRUCTIONS_BYTES + 1)}))
            test.eq(large_instructions, "host:provider: developer_instructions must be bounded nonempty text without unsupported control bytes")
            local _, typed_instructions = configuration.decode("host:provider", provider({schema_revision = "bee.codex-provider@1", name = "bee", base_url = "https://h.example/v1", model = "gpt-5", developer_instructions = true}))
            test.eq(typed_instructions, "host:provider: developer_instructions must be bounded nonempty text without unsupported control bytes")
            local _, control_instructions = configuration.decode("host:provider", provider({schema_revision = "bee.codex-provider@1", name = "bee", base_url = "https://h.example/v1", model = "gpt-5", developer_instructions = "keep\0safe"}))
            test.eq(control_instructions, "host:provider: developer_instructions must be bounded nonempty text without unsupported control bytes")
            local escaped = assert(configuration.decode("host:provider", provider({schema_revision = "bee.codex-provider@1", name = "bee", base_url = "https://h.example/v1", model = "gpt-5", developer_instructions = string.rep("\n", configuration.MAX_DEVELOPER_INSTRUCTIONS_BYTES)})))
            local oversized, oversized_error = configuration.projection(escaped)
            test.is_nil(oversized)
            test.eq(oversized_error, "configuration exceeds " .. tostring(configuration.MAX_CONFIGURATION_BYTES) .. " bytes after TOML escaping")
            local default_content = configuration.render({ref = "host:provider", name = "bee", base_url = "https://h.example/v1", model = "gpt-5", loopback_fixture = false, digest = string.rep("0", 64)})
            test.is_nil(default_content:find("model_reasoning_effort", 1, true))
            local _, bad_name = configuration.decode("host:provider", provider({schema_revision = "bee.codex-provider@1", name = "Bee Provider", base_url = "https://h.example/v1", model = "gpt-5"}))
            test.eq(bad_name, "host:provider: name must be a lowercase identifier")
            local _, plain = configuration.decode("host:provider", provider({schema_revision = "bee.codex-provider@1", name = "bee", base_url = "http://gateway.example.net/v1", model = "gpt-5"}))
            test.eq(plain, "host:provider: plain http is permitted only for the loopback fixture")
            local _, remote_loopback = configuration.decode("host:provider", provider({schema_revision = "bee.codex-provider@1", name = "bee", base_url = "http://10.0.0.5:8080/v1", model = "gpt-5", loopback_fixture = true}))
            test.eq(remote_loopback, "host:provider: the loopback fixture endpoint must be 127.0.0.1 with a port")
            local loopback = assert(configuration.decode("host:provider", provider({schema_revision = "bee.codex-provider@1", name = "bee", base_url = "http://127.0.0.1:4321/v1", model = "gpt-5", loopback_fixture = true})))
            test.is_true(loopback.loopback_fixture)
            local _, query = configuration.decode("host:provider", provider({schema_revision = "bee.codex-provider@1", name = "bee", base_url = "https://h.example/v1?x=1", model = "gpt-5"}))
            test.eq(query, "host:provider: base_url carries no query or fragment")
            local _, untyped = configuration.decode("host:provider", {id = "host:provider", kind = "registry.entry", meta = {type = "registry.entry"}, data = {}})
            test.eq(untyped, "host:provider is not a bee.codex_provider")
        end)
        test.it("selects built-in ChatGPT login without a custom API-key endpoint", function()
            local data: {[string]: unknown} = {schema_revision = "bee.codex-provider@1", name = "openai", authentication = "chatgpt", model = "gpt-5"}
            local decoded, err = configuration.decode("host:provider", provider(data))
            if not decoded then error(tostring(err)) end
            local gateway: configuration.Gateway = {endpoint = "127.0.0.1:4312", action_id = "action-1", tools = {"thread_read"}, hooks = {}, token_environment = "BEE_GATEWAY_TOKEN"}
            local projected, projection_error = configuration.projection(decoded, configuration.gateway_section(gateway))
            if not projected then error(tostring(projection_error)) end
            test.is_true(projected.content:find('forced_login_method = "chatgpt"', 1, true) ~= nil)
            test.is_true(projected.content:find('cli_auth_credentials_store = "file"', 1, true) ~= nil)
            test.is_true(projected.content:find('[mcp_servers.bee]', 1, true) ~= nil)
            test.is_nil(projected.content:find("env_key", 1, true))
            test.is_nil(projected.content:find("base_url", 1, true))
            test.is_nil(projected.content:find("[model_providers.", 1, true))
            data.base_url = "https://other.example/v1"
            test.is_nil(configuration.decode("host:provider", provider(data)))
            data.base_url = nil; data.loopback_fixture = false
            test.is_nil(configuration.decode("host:provider", provider(data)))
            data.loopback_fixture = nil; data.name = "custom"
            test.is_nil(configuration.decode("host:provider", provider(data)))
            data.name = "openai"; data.authentication = "automatic"
            test.is_nil(configuration.decode("host:provider", provider(data)))
            data.authentication = "api_key"
            test.is_nil(configuration.decode("host:provider", provider(data)))
        end)
        test.it("lets builtin account login use Codex's model default without relaxing custom providers", function()
            local data: {[string]: unknown} = {schema_revision = "bee.codex-provider@1", name = "openai", authentication = "chatgpt"}
            local decoded, err = configuration.decode("host:provider", provider(data))
            if not decoded then error(tostring(err)) end
            local projected = assert(configuration.projection(decoded))
            test.is_nil(projected.content:find("model =", 1, true))
            test.is_true(projected.content:find('forced_login_method = "chatgpt"', 1, true) ~= nil)
            test.is_nil(projected.content:find("base_url", 1, true))
            data.model = ""
            test.is_nil(configuration.decode("host:provider", provider(data)))
            data.model = nil; data.authentication = "api_key"; data.base_url = "https://gateway.example/v1"
            test.is_nil(configuration.decode("host:provider", provider(data)))
        end)
        test.it("renders gateway and path-bound hook trust without token bytes", function()
            local gateway: configuration.Gateway = {endpoint = "127.0.0.1:4312", action_id = "action-1", tools = {"thread_read"}, hooks = {"SessionStart"}, token_environment = "BEE_GATEWAY_TOKEN", hook_token_environment = "BEE_GATEWAY_HOOK_TOKEN"}
            local section = configuration.gateway_section(gateway)
            test.is_true(section:find('bearer_token_env_var = "BEE_GATEWAY_TOKEN"', 1, true) ~= nil)
            test.is_true(section:find('bearer_token_env_var = "BEE_GATEWAY_HOOK_TOKEN"', 1, true) ~= nil)
            local files = assert(configuration.hook_files(gateway, "/private/owner/home"))
            test.eq(#files, 2)
            test.eq(files[1].path, ".codex/hooks.json")
            test.eq(files[2].path, ".codex/bee.config.toml")
            test.is_true(files[2].content:find("/private/owner/home/.codex/hooks.json", 1, true) ~= nil)
            test.is_nil(files[1].content:find("BEE_GATEWAY_HOOK_TOKEN", 1, true))
            local repeat_files = assert(configuration.hook_files(gateway, "/private/owner/home"))
            test.eq(files[1].digest, repeat_files[1].digest)
            local escaped = assert(configuration.hook_files(gateway, '/private/"owner\\home'))
            test.is_true(escaped[2].content:find('"/private/\\"owner\\\\home/.codex/hooks.json:session_start:0:0"', 1, true) ~= nil)
        end)
        test.it("rejects gateway hooks Codex cannot deliver", function()
            local gateway: configuration.Gateway = {endpoint = "127.0.0.1:4312", action_id = "action-1", tools = {"thread_read"}, hooks = {"SessionEnd"}, token_environment = "BEE_GATEWAY_TOKEN", hook_token_environment = "BEE_GATEWAY_HOOK_TOKEN"}
            local files, err = configuration.hook_files(gateway, "/private/owner/home")
            test.is_nil(files)
            test.eq(err, "Codex does not support gateway hook event SessionEnd")
        end)
    end)
end
return test.run_cases(define_tests)
