-- SPDX-License-Identifier: MIT
local test = require("test")
local process = require("process")
local channel = require("channel")
local time = require("time")
local image = require("image")
local function receive(listener: channel.Channel<process.Message<unknown>>)
    local selected = channel.select({listener:case_receive(), time.after("5s"):case_receive()})
    test.eq(selected.channel, listener)
    test.eq(selected.ok, true)
end
local function define_tests()
    test.describe("Docker owner supervision", function()
        test.it("enforces revocation while the serial Docker operation is blocked", function()
            local blocked = assert(process.listen("bee.test.docker.blocked", {message = true}))
            local stopped = assert(process.listen("bee.test.docker.stopped", {message = true}))
            local replies = assert(process.listen(image.REPLY, {message = true}))
            assert(process.registry.register("bee.test.docker.attempt"))
            local owner = assert(process.spawn("bee.tests.placement_owner:docker_owner_fixture", "bee:workers"))
            local called, problem = pcall(function()
                assert(process.send(tostring(owner), image.REQUEST, {version = 1, request_id = "aaaa"}))
                receive(blocked)
                assert(process.registry.register("bee.test.docker.revoked"))
                receive(stopped)
                process.registry.unregister("bee.test.docker.attempt")
                assert(process.send(tostring(owner), "bee.test.docker.release", {}))
                receive(replies)
            end)
            process.cancel(tostring(owner), "fixture ends")
            process.registry.unregister("bee.test.docker.attempt")
            process.registry.unregister("bee.test.docker.revoked")
            process.unlisten(blocked); process.unlisten(stopped); process.unlisten(replies)
            if not called then error(tostring(problem)) end
        end)
    end)
end
return test.run_cases(define_tests)
