-- SPDX-License-Identifier: MIT
local test = require("test")
local sql = require("sql")
local supervision = require("supervision")
local function define_tests()
    test.describe("Placement demand eligibility", function()
        test.it("keeps Docker uncertainty and cleanup pending, and native preparer cleanup, active", function()
            local db = assert(sql.get("bee.tests.placement_owner:eligibility_db"))
            assert(db:execute("CREATE TABLE bee_placement_attempts (attempt_id TEXT, placement_kind TEXT, execution_state TEXT, cleanup_state TEXT, updated_at TEXT)"))
            assert(db:execute("CREATE TABLE bee_placement_evidence (attempt_id TEXT, kind TEXT)"))
            assert(db:execute("INSERT INTO bee_placement_attempts VALUES ('a', 'native', 'intended', 'pending', 'now')"))
            test.eq(supervision.pending(db, "native"), false)
            for _, state in ipairs({"starting", "running", "stopping"}) do
                assert(db:execute("UPDATE bee_placement_attempts SET execution_state = ?", {state}))
                test.eq(supervision.pending(db, "native"), true)
            end
            assert(db:execute("UPDATE bee_placement_attempts SET execution_state = 'uncertain'"))
            test.eq(supervision.pending(db, "native"), false)
            assert(db:execute("UPDATE bee_placement_attempts SET placement_kind = 'docker'"))
            test.eq(supervision.pending(db, "docker"), true)
            assert(db:execute("UPDATE bee_placement_attempts SET execution_state = 'exited'"))
            test.eq(supervision.pending(db, "docker"), true)
            assert(db:execute("UPDATE bee_placement_attempts SET cleanup_state = 'complete'"))
            test.eq(supervision.pending(db, "docker"), false)
            assert(db:execute("UPDATE bee_placement_attempts SET placement_kind = 'native', cleanup_state = 'pending'"))
            test.eq(supervision.pending(db, "native"), false)
            assert(db:execute("INSERT INTO bee_placement_evidence VALUES ('a', 'workdir_preparer.state')"))
            test.eq(supervision.pending(db, "native"), true)
            assert(db:execute("INSERT INTO bee_placement_evidence VALUES ('a', 'workdir_preparers.settled')"))
            test.eq(supervision.pending(db, "native"), false)
            db:release()
        end)
    end)
end
return test.run_cases(define_tests)
