local test = require("test")
local bounds = require("bounds")

local function define_tests()
    test.describe("Shared value bounds", function()
        test.it("applies an optional upper bound to nonnegative integer counts", function()
            test.eq(bounds.count(3, 3), 3)
            test.eq(bounds.count(4, 3), nil)
            test.eq(bounds.count(-1, 3), nil)
            test.eq(bounds.count(3.5, 3), nil)
        end)
        test.it("retains the safe integer default when no upper bound is supplied", function()
            test.eq(bounds.count(9007199254740991), 9007199254740991)
            test.eq(bounds.count(9007199254740992), nil)
        end)
        test.it("returns a string only when it belongs to the supplied choices", function()
            test.eq(bounds.member("window", {"headless", "window"}), "window")
            test.eq(bounds.member("terminal", {"headless", "window"}), nil)
            test.eq(bounds.member(1, {"headless", "window"}), nil)
        end)
    end)
end

return test.run_cases(define_tests)
