local test = require("test")
local bounds = require("bounds")

local function define_tests()
    test.describe("Shared value bounds", function()
        test.it("applies an optional upper bound to nonnegative integer counts", function()
            test.eq(bounds.count(3, 3), 3)
            test.eq(bounds.count(4, 3), nil)
            test.eq(bounds.count(-1, 3), nil)
            test.eq(bounds.count(3.5, 3), nil)
        end)
        test.it("retains the safe integer default when no upper bound is supplied", function()
            test.eq(bounds.count(9007199254740991), 9007199254740991)
            test.eq(bounds.count(9007199254740992), nil)
        end)
        test.it("returns a string only when it belongs to the supplied choices", function()
            test.eq(bounds.member("window", {"headless", "window"}), "window")
            test.eq(bounds.member("terminal", {"headless", "window"}), nil)
            test.eq(bounds.member(1, {"headless", "window"}), nil)
        end)
        test.it("accepts a timestamp only when the clock parses it", function()
            test.eq(bounds.timestamp("2026-10-03T12:00:00.000Z"), "2026-10-03T12:00:00.000Z")
            test.eq(bounds.timestamp("yesterday"), nil)
            test.eq(bounds.timestamp(1), nil)
        end)
        test.it("reads a list of identifiers, optionally distinct", function()
            test.eq(#assert(bounds.ids({"a", "b", "a"})), 3)
            local repeated, reason = bounds.ids({"a", "b", "a"}, true)
            test.eq(repeated, nil)
            test.eq(reason, "list item 3 repeats")
            local bad, bad_reason = bounds.ids({"a", ""})
            test.eq(bad, nil)
            test.eq(bad_reason, "list item 2 is not an identifier")
        end)
        test.it("separates an absent field from an invalid identifier", function()
            local absent, absent_valid = bounds.optional_id({}, "ref")
            test.eq(absent, nil)
            test.is_true(absent_valid)
            local present, present_valid = bounds.optional_id({ref = "x"}, "ref")
            test.eq(present, "x")
            test.is_true(present_valid)
            local invalid, invalid_valid = bounds.optional_id({ref = ""}, "ref")
            test.eq(invalid, nil)
            test.is_false(invalid_valid)
        end)
    end)
end

return test.run_cases(define_tests)
