local test = require("test")
local hash = require("hash")
local canonical = require("canonical")

local function define_tests()
    test.describe("Canonical JSON encoding and digest", function()
        test.it("preserves the measured nested empty collection shape", function()
            local encoded = assert(canonical.encode({modules = table.create(1, 0), imports = table.create(0, 1)}))
            test.eq(encoded, '{"imports":{},"modules":[]}')
            test.eq(assert(hash.sha256(encoded)), "f5ef72f39852525809e147f0d22d851db828cd9c259a2fe6cb526b99720f339a")
        end)
        test.it("preserves sorted object keys and digest", function()
            local encoded = assert(canonical.encode({b = 2, a = 1}))
            test.eq(encoded, '{"a":1,"b":2}')
            test.eq(assert(hash.sha256(encoded)), "43258cff783fe7036d8a43033f830adfc60ec037382473548ac742b888292777")
        end)
        test.it("preserves ordered arrays and digest", function()
            local encoded = assert(canonical.encode({"a", "b"}))
            test.eq(encoded, '["a","b"]')
            test.eq(assert(hash.sha256(encoded)), "0473ef2dc0d324ab659d3580c1134e9d812035905c4781fdd6d529b0c6860e13")
        end)
        test.it("accepts the exact byte bound and rejects one byte less", function()
            test.eq(canonical.encode({x = 1}, 7), '{"x":1}')
            local encoded, encode_error = canonical.encode({x = 1}, 6)
            test.eq(encoded, nil)
            test.eq(encode_error, "value exceeds the encoded byte bound")
        end)
        test.it("applies the explicit nesting bound", function()
            test.eq(canonical.encode({outer = true}, nil, 2), '{"outer":true}')
            local encoded, encode_error = canonical.encode({outer = true}, nil, 1)
            test.eq(encoded, nil)
            test.eq(encode_error, "value nests deeper than 1")
        end)
        test.it("preserves escaped control bytes and their digest", function()
            local encoded = assert(canonical.encode({text = "line\n"}))
            test.eq(encoded, '{"text":"line\\u000a"}')
            test.eq(assert(hash.sha256(encoded)), "126dd2deb225f9d6778d19b3f87d47d3d03508d51991185623934bb8f4b36eea")
        end)
        test.it("rejects non-finite numbers", function()
            local encoded, encode_error = canonical.encode(math.huge)
            test.eq(encoded, nil)
            test.eq(encode_error, "number is not finite")
        end)
        test.it("rejects mixed-key and sparse tables", function()
            local mixed, mixed_error = canonical.encode({[1] = "first", name = "value"})
            test.eq(mixed, nil)
            test.eq(mixed_error, "table mixes list and object keys")
            local sparse, sparse_error = canonical.encode({[1] = "first", [3] = "third"})
            test.eq(sparse, nil)
            test.eq(sparse_error, "list is not dense")
        end)
        test.it("preserves empty table shape when creating a replacement", function()
            local object = canonical.empty_like(table.create(0, 1))
            local list = canonical.empty_like(table.create(1, 0))
            test.eq(canonical.encode(object), "{}")
            test.eq(canonical.encode(list), "[]")
        end)
    end)
end

return test.run_cases(define_tests)
