-- MIT. The client trusts only this node's supervisor: found by name, checked
-- by host, correlated by request id, bounded by a deadline.
local test = require("test")
local process = require("process")
local time = require("time")
local client = require("client")
local types = require("types")
local OWNER = {node_id = "local", service_id = "bee.hive.telemetry"}
local TARGET = {operation_ref = "bee.hive.telemetry:stats"}
local function settle()
    time.sleep("50ms")
end
local function define_tests()
    test.describe("Hive client", function()
        test.it("reports an absent supervisor without waiting", function()
            local handle, open_error = client.open()
            if not handle then error(tostring(open_error)) end
            local reply = handle:call(OWNER, TARGET, {mode = "echo"}, {timeout = "1s"})
            test.is_false(reply.ok)
            test.eq(reply.error and reply.error.code, "UNAVAILABLE")
            handle:close()
        end)
        test.it("refuses a supervisor name that resolves outside the supervisor host", function()
            local impostor, spawn_error = process.spawn("bee.hive:fake_supervisor", "bee:workers")
            if not impostor then error(tostring(spawn_error)) end
            settle()
            local handle = client.open()
            if not handle then error("open") end
            local reply = handle:call(OWNER, TARGET, {mode = "echo"}, {timeout = "1s"})
            test.eq(reply.error and reply.error.code, "UNAVAILABLE")
            test.eq(reply.error and reply.error.message, "supervisor name resolves outside the supervisor host")
            handle:close()
            process.terminate(impostor)
            settle()
        end)
        test.it("correlates replies from the supervisor and ignores everyone else", function()
            local supervisor, spawn_error = process.spawn("bee.hive:fake_supervisor", types.SUPERVISOR_HOST)
            if not supervisor then error(tostring(spawn_error)) end
            settle()
            local handle = client.open()
            if not handle then error("open") end
            local echoed = handle:call(OWNER, TARGET, {mode = "echo", n = 1}, {idempotency_key = "k1", timeout = "2s"})
            test.is_true(echoed.ok)
            test.eq(echoed.value.echo.n, 1)
            test.eq(echoed.value.owner, "bee.hive.telemetry")
            local stale = handle:call(OWNER, TARGET, {mode = "stale"}, {timeout = "2s"})
            test.is_true(stale.ok)
            test.is_true(stale.value.fresh)
            local delayed = handle:call(OWNER, TARGET, {mode = "delayed"}, {timeout = "2s"})
            test.is_true(delayed.value.late)
            local impostor = handle:call(OWNER, TARGET, {mode = "impostor"}, {timeout = "400ms"})
            test.eq(impostor.error and impostor.error.code, "DEADLINE_EXCEEDED")
            local malformed = handle:call(OWNER, TARGET, {mode = "malformed"}, {timeout = "2s"})
            test.eq(malformed.error and malformed.error.code, "INTERNAL")
            local silent = handle:call(OWNER, TARGET, {mode = "silent"}, {timeout = "200ms"})
            test.eq(silent.error and silent.error.code, "DEADLINE_EXCEEDED")
            local after = handle:call(OWNER, TARGET, {mode = "echo", n = 2}, {timeout = "2s"})
            test.eq(after.value.echo.n, 2)
            local invalid = handle:call(OWNER, {operation_ref = "a:b", interface_ref = "a:c"}, {}, {timeout = "1s"})
            test.eq(invalid.error and invalid.error.code, "INVALID_ARGUMENT")
            handle:close()
            process.terminate(supervisor)
            settle()
        end)
    end)
end
local cases = test.run_cases(define_tests)
return {run = function(options) return cases(options) end}
