version: '1.0'
registry:
  enable_history: true
  history_type: sqlite
  history_path: .wippy/registry.db
shutdown:
  timeout: 3s
workspace:
  replacements:
    bee/persist: ./modules/bee-persist
    bee/threads: ./modules/bee-threads
    bee/driver: ./modules/bee-driver
    bee/driver-agy: ./modules/bee-driver-agy
    bee/driver-claude: ./modules/bee-driver-claude
    bee/driver-codex: ./modules/bee-driver-codex
    bee/driver-grok: ./modules/bee-driver-grok
    bee/driver-muse: ./modules/bee-driver-muse
