//go:build ignore

// Run from the pinned runtime module: go run /path/to/bee/tests/tools/hub_pack_fixture.go pack.wapp
package main

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/wippyai/runtime/boot/deps/packentries"
	"github.com/wippyai/wapp"
)

func main() {
	f, err := os.Open(os.Args[1])
	if err != nil {
		panic(err)
	}
	defer f.Close()
	digest := sha256.New()
	if _, err := io.Copy(digest, f); err != nil {
		panic(err)
	}
	reader, err := wapp.NewReader(f)
	if err != nil {
		panic(err)
	}
	entries, err := reader.GetEntries()
	if err != nil {
		panic(err)
	}
	rows := make([]map[string]any, 0, len(entries))
	for _, entry := range entries {
		meta := entry.Meta
		if meta == nil {
			meta = map[string]any{}
		}
		var data any = map[string]any{}
		if entry.Kind == "ns.requirement" || entry.Kind == "ns.dependency" || entry.ID.String() == "bee.env:binary_identity" {
			data = packentries.UnwrapPayloadData(entry.Data)
		}
		rows = append(rows, map[string]any{"id": entry.ID.String(), "kind": entry.Kind, "meta": meta, "data": data})
	}
	encoded, err := json.Marshal(rows)
	if err != nil {
		panic(err)
	}
	fmt.Printf("-- MIT. Entry identities/metadata and requirement data from bee/bee pack sha256:%x.\n", digest.Sum(nil))
	fmt.Println("-- Generated by tests/tools/hub_pack_fixture.go; executable bodies are omitted.")
	fmt.Println("local json = require(\"json\")\nlocal bounds = require(\"bounds\")\nlocal inspection = require(\"inspection\")\nlocal M = {}")
	fmt.Printf("local encoded = [====[%s]====]\n", encoded)
	fmt.Println(`function M.entries(): {inspection.Entry}
    local raw = assert(json.decode(encoded))
    assert(type(raw) == "table")
    local entries: {inspection.Entry} = {}
    for _, row in ipairs(raw) do
        local entry = assert(bounds.object(row))
        entries[#entries + 1] = {id = assert(bounds.id(entry.id)), kind = assert(bounds.id(entry.kind)),
            meta = assert(bounds.object(entry.meta)), data = entry.data}
    end
    return entries
end
return M`)
}
