// SPDX-License-Identifier: MIT
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// This opt-in acceptance starts the installed Agy binary through Bee without a
// model prompt. The wrapper only selects a disposable log path; Bee still owns
// every configuration argument and file delivered to the provider.
func TestActualAgyManagedStartup(t *testing.T) {
	binary := os.Getenv("BEE_BINARY")
	executable := os.Getenv("AGY_BIN")
	if binary == "" || executable == "" {
		t.Fatal("BEE_BINARY and AGY_BIN are required")
	}
	var err error
	if binary, err = filepath.Abs(binary); err != nil {
		t.Fatal(err)
	}
	if executable, err = filepath.Abs(executable); err != nil {
		t.Fatal(err)
	}
	root := t.TempDir()
	project, state, home := filepath.Join(root, "project"), filepath.Join(root, "state"), filepath.Join(root, "home")
	logPath := filepath.Join(root, "agy.log")
	if err := os.MkdirAll(filepath.Join(project, "bin"), 0700); err != nil {
		t.Fatal(err)
	}
	globalMarker := filepath.Join(home, ".gemini", "global-settings-marker")
	if err := os.MkdirAll(filepath.Dir(globalMarker), 0700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(globalMarker, []byte("ordinary-global-settings"), 0600); err != nil {
		t.Fatal(err)
	}
	wrapper := "#!/bin/sh\nexec " + shellQuote(executable) + " --log-file " + shellQuote(logPath) + " \"$@\"\n"
	if err := os.WriteFile(filepath.Join(project, "bin", "agy"), []byte(wrapper), 0700); err != nil {
		t.Fatal(err)
	}
	ui, err := newDesktopWithArguments(binary, project, state, home, []string{"agy"})
	if err != nil {
		t.Fatal(err)
	}
	defer func() {
		ui.close()
		if err := stopFixtureOwners(binary, state); err != nil {
			t.Errorf("stop fixture owners: %v", err)
		}
	}()
	deadline := time.Now().Add(30 * time.Second)
	loadedHooks := false
	for time.Now().Before(deadline) {
		data, readErr := os.ReadFile(logPath)
		if readErr == nil && strings.Contains(string(data), "loaded 1 named hooks") {
			loadedHooks = true
			break
		}
		time.Sleep(100 * time.Millisecond)
	}
	if !loadedHooks {
		data, _ := os.ReadFile(logPath)
		t.Fatalf("actual Agy did not load Bee's added customization root: %s", string(data))
	}
	for _, path := range []string{
		filepath.Join(home, ".gemini", "config", "mcp_config.json"),
		filepath.Join(home, ".gemini", "config", "hooks.json"),
		filepath.Join(home, ".gemini", "GEMINI.md"),
	} {
		data, err := os.ReadFile(path)
		if err == nil && (strings.Contains(string(data), "/mcp/") || strings.Contains(string(data), "hook-post") || strings.Contains(string(data), "generated by bee")) {
			t.Fatalf("Bee configuration appeared in Agy's global tree: %s", path)
		}
		if err != nil && !os.IsNotExist(err) {
			t.Fatalf("inspect Agy global path %s: %v", path, err)
		}
	}
	if _, err := os.Stat(filepath.Join(project, ".agents")); !os.IsNotExist(err) {
		t.Fatal("Bee wrote Agy customization into the project")
	}
	marker, err := os.ReadFile(globalMarker)
	if err != nil || string(marker) != "ordinary-global-settings" {
		t.Fatalf("global settings marker changed: %q, %v", string(marker), err)
	}
	found := map[string]bool{}
	err = filepath.Walk(state, func(path string, info os.FileInfo, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if info.Mode().IsRegular() {
			relative := filepath.ToSlash(path)
			for _, name := range []string{".agents/mcp_config.json", ".agents/hooks.json"} {
				if strings.HasSuffix(relative, name) {
					found[name] = true
				}
			}
		}
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{".agents/mcp_config.json", ".agents/hooks.json"} {
		if !found[name] {
			t.Fatal(fmt.Sprintf("Bee did not materialize %s in retained state", name))
		}
	}
	if err := ui.quit(); err != nil {
		t.Fatal(err)
	}
	t.Log("Actual Agy loaded Bee's additional customization root, left global/project configuration untouched, and detached promptly")
}

// This opt-in acceptance uses a real CLI and a selected login file, but submits
// no model prompt. Machine settings and trust state are never copied.
func TestActualGrokManagedStartup(t *testing.T) {
	binary := os.Getenv("BEE_BINARY")
	executable := os.Getenv("GROK_BIN")
	loginSource := os.Getenv("GROK_LOGIN_FILE")
	if binary == "" || executable == "" || loginSource == "" {
		t.Fatal("BEE_BINARY, GROK_BIN and GROK_LOGIN_FILE are required")
	}
	binary, err := filepath.Abs(binary)
	if err != nil {
		t.Fatal(err)
	}
	executable, err = filepath.Abs(executable)
	if err != nil {
		t.Fatal(err)
	}
	root := t.TempDir()
	project, state, home := filepath.Join(root, "project"), filepath.Join(root, "state"), filepath.Join(root, "home")
	if err := os.MkdirAll(filepath.Join(project, "bin"), 0700); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(executable, filepath.Join(project, "bin", "grok")); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(home, ".grok"), 0700); err != nil {
		t.Fatal(err)
	}
	login, err := os.ReadFile(loginSource)
	if err != nil {
		t.Fatal("machine login unavailable")
	}
	if err := os.WriteFile(filepath.Join(home, ".grok", "auth.json"), login, 0600); err != nil {
		t.Fatal(err)
	}
	ui, err := newDesktop(binary, project, state, home)
	if err != nil {
		t.Fatal(err)
	}
	defer func() {
		ui.close()
		if err := stopFixtureOwners(binary, state); err != nil {
			t.Errorf("stop fixture owners: %v", err)
		}
	}()
	if err := ui.waitFor("Choose a profile", 25*time.Second); err != nil {
		t.Fatal(err)
	}
	for i := 0; i < 3; i++ {
		_, before, _ := ui.snapshot()
		if err := ui.send("\x1b[B"); err != nil {
			t.Fatal(err)
		}
		if err := ui.waitForAfter("Choose a profile", before, 5*time.Second); err != nil {
			t.Fatal(err)
		}
	}
	if err := ui.send("\r"); err != nil {
		t.Fatal(err)
	}
	deadline := time.Now().Add(30 * time.Second)
	for time.Now().Before(deadline) {
		db, err := openRecoveryDB(filepath.Join(state, "threads.db"))
		if err != nil {
			t.Fatal(err)
		}
		rows, err := db.Query("SELECT record_json FROM bee_thread_records WHERE kind='observation' AND source='bee'")
		found := false
		if err == nil {
			for rows.Next() {
				var raw string
				if err := rows.Scan(&raw); err != nil {
					rows.Close()
					db.Close()
					t.Fatal(err)
				}
				var rec struct {
					Body struct {
						Data struct {
							Name    string `json:"event_name"`
							Payload string `json:"payload_json"`
						} `json:"data"`
					} `json:"body"`
				}
				if json.Unmarshal([]byte(raw), &rec) != nil || rec.Body.Data.Name != "bee.harness.hook" {
					continue
				}
				var payload struct {
					Event  string         `json:"event"`
					Fields map[string]any `json:"fields"`
				}
				if json.Unmarshal([]byte(rec.Body.Data.Payload), &payload) == nil && payload.Event == "SessionStart" {
					session, ok := payload.Fields["session_id"].(string)
					found = found || (ok && session != "")
				}
			}
			readErr := rows.Err()
			rows.Close()
			if readErr != nil {
				db.Close()
				t.Fatal(readErr)
			}
		}
		db.Close()
		if found {
			t.Log("Actual Grok emitted SessionStart through generated hook configuration into its bound Bee thread; no prompt submitted")
			if err := ui.quit(); err != nil {
				t.Fatal(err)
			}
			return
		}
		time.Sleep(100 * time.Millisecond)
	}
	t.Fatal("actual Grok startup hook did not commit within 30 seconds")
}
