-- SPDX-License-Identifier: MIT
local test = require("test")
local gateway = require("gateway")
local protocol = require("protocol")
local node_client = require("node_client")
local system = require("system")
local funcs = require("funcs")
local security = require("security")
local bounds = require("bounds")
local channel = require("channel")
local function value(raw: unknown): {[string]: unknown}
    local reply = assert(bounds.object(raw))
    if reply.ok ~= true then error(tostring((bounds.object(reply.error) or {}).message)) end
    return assert(bounds.object(reply.value))
end
local function define_tests()
    value(gateway.open({address = assert(gateway.endpoint())}))
    test.describe("MCP command on the running node", function()
        test.it("pairs through Hive under the gateway service scope and wakes on approval", function()
            local node = assert(system.node.id())
            local state = assert(node_client.call(node, "workspaces", {}))
            local workspace = assert(bounds.id(state.home))
            local asked = assert(protocol.call(node, "mcp.connect", {name = "Outside Bee", workspace_id = workspace}, "10s"))
            test.is_true(asked.ok)
            local pairing = value(asked.value)
            test.is_nil(pairing.token)
            local completed = channel.new(1)
            coroutine.spawn(function()
                local finished, err = protocol.call(node, "mcp.wait", {client_id = pairing.client_id}, "10s")
                assert(completed:send({reply = finished, error = err}))
            end)
            local approver = funcs.new():with_actor(security.new_actor("bee.application:" .. workspace .. ":mcp-approver",
                {workspace_id = workspace, definition_id = "bee.approvals.inbox.app:app"}))
            local approval = value(approver:call("bee.approvals.binding:read", {approval_id = pairing.approval_id}))
            value(approver:call("bee.approvals.binding:decide", {approval_id = pairing.approval_id,
                expected_revision = approval.revision, proposal_digest = approval.proposal_digest, reviewed_digest = approval.reviewed_digest, decision = "approved"}))
            local delivered = assert(bounds.object(completed:receive()))
            test.is_nil(delivered.error)
            local reply = assert(bounds.object(delivered.reply))
            test.is_true(reply.ok == true)
            local connection = value(reply.value)
            test.eq(connection.status, "connected")
            test.is_true(type(connection.token) == "string")
            local again = assert(protocol.call(node, "mcp.wait", {client_id = pairing.client_id}, "10s"))
            test.is_nil(value(again.value).token)
            local manager = funcs.new():with_actor(security.new_actor("bee.application:" .. workspace .. ":mcp-manager",
                {workspace_id = workspace, definition_id = "bee.gateway.app:app"}))
            value(manager:call("bee.gateway.binding:external_call", {operation = "revoke", client_id = pairing.client_id}))
        end)
        test.it("revokes pending pairing and withdraws its Needs you request", function()
            local node = assert(system.node.id())
            local workspace = assert(bounds.id(assert(node_client.call(node, "workspaces", {})).home))
            local asked = assert(protocol.call(node, "mcp.connect", {name = "Cancelled client", workspace_id = workspace}, "10s"))
            local pairing = value(asked.value)
            local manager = funcs.new():with_actor(security.new_actor("bee.application:" .. workspace .. ":mcp-manager",
                {workspace_id = workspace, definition_id = "bee.gateway.app:app"}))
            value(manager:call("bee.gateway.binding:external_call", {operation = "revoke", client_id = pairing.client_id}))
            local approver = funcs.new():with_actor(security.new_actor("bee.application:" .. workspace .. ":mcp-approver",
                {workspace_id = workspace, definition_id = "bee.approvals.inbox.app:app"}))
            local approval = value(approver:call("bee.approvals.binding:read", {approval_id = pairing.approval_id}))
            test.eq(approval.state, "withdrawn")
            local completed = assert(protocol.call(node, "mcp.wait", {client_id = pairing.client_id}, "10s"))
            local connection = value(completed.value)
            test.eq(connection.status, "revoked")
            test.is_nil(connection.token)
        end)
        test.it("refuses an agent using the client-management facade", function()
            local reply = assert(bounds.object(funcs.call("bee.gateway.binding:external_call", {operation = "list"})))
            test.is_false(reply.ok == true)
            test.eq(assert(bounds.object(reply.error)).code, "DENIED")
        end)
    end)
end
return test.run_cases(define_tests)
