-- SPDX-License-Identifier: MIT
local test = require("test")
local configuration = require("configuration")
local json = require("json")
local bounds = require("bounds")
local function define_tests()
    test.describe("External MCP configuration", function()
        test.it("renders Claude and Codex references with one token disclosure", function()
            local rendered = assert(configuration.render("Terminal Claude", "127.0.0.1:4312", "client-1", "fixture-token"))
            local _, occurrences = rendered:gsub("fixture%-token", "")
            test.eq(occurrences, 1)
            test.is_true(rendered:find('bearer_token_env_var = "BEE_MCP_TOKEN"', 1, true) ~= nil)
            test.is_true(rendered:find('claude mcp add --transport http bee', 1, true) ~= nil)
            test.is_true(rendered:find("http://127.0.0.1:4312/mcp/client-1", 1, true) ~= nil)
            local raw = assert(rendered:match("```json\n(.-)\n```"))
            local document = assert(bounds.object(json.decode(raw)))
            local servers = assert(bounds.object(document.mcpServers))
            local bee = assert(bounds.object(servers.bee))
            test.eq(bee.type, "http")
            test.eq(assert(bounds.object(bee.headers)).Authorization, "Bearer ${BEE_MCP_TOKEN}")
        end)
        test.it("refuses non-loopback listeners and malformed identifiers", function()
            for _, endpoint in ipairs({"10.1.2.3:4312", "192.168.1.2:4312", "localhost:4312", "127.0.0.1:0"}) do
                test.is_nil(configuration.render("client", endpoint, "client-1", "fixture-token"))
            end
            test.is_nil(configuration.render("client", "127.0.0.1:4312", "../client", "fixture-token"))
            test.is_nil(configuration.render("client", "127.0.0.1:4312", "client-1", "bad'\nvalue"))
        end)
    end)
end
return test.run_cases(define_tests)
