local test = require("test")
local surface = require("surface")
local traits = require("traits")
local bounds = require("bounds")
local host = require("host")
local gateway = require("gateway")
local function raw(hooks: {string}?, active: {string}?, approval: boolean?): {[string]: unknown}
    return {tools = {}, traits = {{id = "memory:trait", title = "Memory", prompt = "Remember facts", tools = {},
        application_ref = "memory:app", application_revision = "1", listens = {"turn.completed"}, hooks = hooks or {}}},
        base_tools = {}, active_traits = active or {}, fixed_context = {}, dynamic_keys = {},
        access = approval and {policy = "memory:approve", traits = {"memory:trait"}} or nil}
end
local function define_tests()
    test.describe("Extension consent", function()
        test.it("activates a seeded trait from the person's decision without access status", function()
            local session = host.open(true)
            local current = assert((gateway.surface(session.binding)))
            test.eq(current.selection.active[1], host.TRAIT)
            local client = host.client("decision-memory")
            local discovery = host.value(host.receive(client, "subscribe", {trait_id = host.TRAIT, idempotency_key = "decision-memory"}))
            test.not_nil(discovery)
        end)
        test.it("reviews app identity, exact declarations, workspace and session before activation", function()
            local session, question = host.open()
            local proposal = assert(bounds.object(question.proposal))
            local payload = assert(bounds.object(proposal.payload))
            test.eq(payload.session_ref, session.session)
            test.eq(payload.thread_id, session.thread)
            test.eq(question.workspace_id, host.WORKSPACE)
            local declared = assert(bounds.object(assert(bounds.array(payload.declarations, 16))[1]))
            test.eq(declared.application_ref, host.APP)
            test.eq(declared.application_revision, "1")
            test.eq(assert(bounds.array(declared.listens, 6))[1], "turn.completed")
            test.is_true(assert(bounds.text(assert(bounds.object(question.prompt)).text)):find("listens: turn.completed", 1, true) ~= nil)
        end)
        test.it("pins registry app ownership and revision and refuses declaration upgrades", function()
            local declared, err = traits.load("bee.tests.memory:trait")
            if not declared then error(tostring(err)) end
            test.eq(declared.application_ref, "bee.tests.memory:app")
            test.eq(declared.application_revision, "1")
            test.not_nil(traits.review(declared))
            declared.listens = {"tool.after"}
            local live, refused = traits.review(declared)
            test.is_nil(live)
            test.is_true(tostring(refused):find("re-approval required", 1, true) ~= nil)
        end)
        test.it("never offers a listener as a freely selectable trait", function()
            local configured, _, err = surface.prepare(raw(nil, {"memory:trait"}), {}, {})
            test.is_nil(configured, tostring(err))
        end)
        test.it("requires the person even when an extension has no tools", function()
            local configured, _, err = surface.prepare(raw(), {}, {})
            test.is_nil(configured, tostring(err))
            local offered = assert((surface.prepare(raw(nil, nil, true), {}, {})))
            test.is_nil(surface.select(offered, {"memory:trait"}, {}))
            local approved = assert(surface.grant(offered, {"memory:trait"}))
            test.not_nil(surface.select(approved, {"memory:trait"}, {}))
        end)
        test.it("refuses hook activation with its phase one capability error", function()
            local offered = assert((surface.prepare(raw({"tool.before"}, nil, true), {}, {})))
            local approved, err = surface.grant(offered, {"memory:trait"})
            test.is_nil(approved)
            test.is_true(tostring(err):find("hooks not yet supported", 1, true) ~= nil, tostring(err))
        end)
    end)
end
return test.run_cases(define_tests)
