local test = require("test")
local sql = require("sql")
local json = require("json")
local funcs = require("funcs")
local schema = require("schema")
local grants = require("grants")
local bounds = require("bounds")
local store = require("store")
local clock = require("clock")
local service = require("service")
local DATABASE = "bee.gateway:grants_migration_db"
local function migrate(name: string)
    local id = "bee.gateway.migrations:" .. name
    local result, err = funcs.call(id,{target_db = "bee:db",database_id = DATABASE,direction = "up",id = id})
    assert(not err,tostring(err)); assert(assert(bounds.object(result)).status ~= "error",json.encode(result))
end
local function define_tests()
    test.describe("Gateway Grant migration",function()
        test.it("imports legacy receipt authority and existing profile surfaces without requiring retained source requests",function()
            local db = schema.open(DATABASE,"bee.approvals.migrations")
            for _, name in ipairs({"gateway","hooks","complete","lease","external"}) do migrate(name) end
            assert(db:execute([[INSERT INTO bee_gateway_bindings(binding_id,subject,action_id,attempt_id,thread_id,owner_incarnation,carrier_epoch,tools_json,hooks_json,epoch,credential_generation,expires_at,created_at,workspace_id)
                VALUES ('binding','subject','action','attempt','thread',1,1,'[]','[]',1,0,'2099-01-01T00:00:00Z','2026-10-01T00:00:00Z','workspace')]]))
            local configuration = {tools = {},traits = {},base_tools = {"app_tools"},active_traits = {},fixed_context = {},dynamic_keys = {},profile = {mcp = {}}}
            assert(db:execute("INSERT INTO bee_gateway_surfaces VALUES ('binding',?,'[]','{}',1)",{json.encode(configuration)}))
            assert(db:execute("INSERT INTO bee_gateway_access_grants VALUES ('binding','archived-approval',?,'[\"bee.app:runtime\"]')",{string.rep("a",64)}))
            migrate("grants")
            local receipt = assert(grants.read(db,"archived-approval:grant"))
            test.eq(receipt.provenance.kind,"legacy")
            test.eq(receipt.subject.audience,"binding")
            test.eq(receipt.workspace_id,"workspace")
            test.eq(receipt.metadata.configuration_digest,"legacy")
            local surface = assert(bounds.object(json.decode(assert(db:query("SELECT surface_json FROM bee_gateway_surfaces"))[1].surface_json)))
            local legacy = assert(grants.read(db,assert(bounds.id(surface.authority_grant_id))))
            test.eq(legacy.provenance.kind,"legacy")
            test.eq(legacy.provenance.consenting_actor,"unrecorded")
            test.eq(json.encode(assert(bounds.object(legacy.scope.parameters)).configuration),(json.encode(configuration)))
            assert(db:execute("UPDATE bee_gateway_bindings SET expires_at = '2020-01-01T00:00:00.000Z' WHERE binding_id = 'binding'"))
            test.eq(grants.state(assert(grants.read(db,legacy.grant_id)),clock.milliseconds()),"expired")
            assert(db:execute("UPDATE bee_gateway_bindings SET expires_at = '2099-01-01T00:00:00.000Z' WHERE binding_id = 'binding'"))
            local tx = assert(db:begin())
            test.not_nil((store.profile_authority(tx,"binding","workspace",surface)))
            surface.base_tools = {"app_tools","thread_read"}
            test.is_nil((store.profile_authority(tx,"binding","workspace",surface)))
            surface.base_tools = configuration.base_tools
            test.is_nil((store.profile_authority(tx,"different-binding","workspace",surface)))
            test.eq(#assert(store.grants(tx,"binding")),1)
            assert(not grants.revoke(tx,receipt,receipt.revision,"person",clock.milliseconds()))
            test.eq(#assert(store.grants(tx,"binding")),0)
            test.eq(assert(store.read(tx,"binding")).active_json,"[]")
            assert(tx:commit())
            test.eq(#assert(db:query("SELECT * FROM bee_gateway_access_receipts")),1)
            test.eq(#assert(db:query("SELECT name FROM sqlite_master WHERE name = 'bee_gateway_access_grants'")),0)
            assert(db:execute("UPDATE bee_gateway_bindings SET sealed_at = '2026-10-01T00:00:01.000Z' WHERE binding_id = 'binding'"))
            local ended = assert(grants.read(db,legacy.grant_id))
            test.eq(ended.state,"revoked")
            local revoked = service.execute(db,"person","grant",{operation = "revoke",grant_id = ended.grant_id,expected_revision = ended.revision},clock.milliseconds())
            test.eq(revoked.ok,true,tostring(revoked.message))
            test.eq(assert(db:query("SELECT state FROM bee_approval_grants WHERE grant_id = ?",{ended.grant_id}))[1].state,"revoked")
            assert(db:execute("UPDATE bee_gateway_bindings SET sealed_at = NULL,expires_at = '2099-01-01T00:00:00.000Z' WHERE binding_id = 'binding'"))
            test.eq(assert(grants.read(db,ended.grant_id)).state,"revoked")
            local history = assert(db:query("SELECT kind FROM bee_approval_grant_history WHERE grant_id = ? ORDER BY revision",{ended.grant_id}))
            test.eq(history[#history].kind,"grant.revoked")
            db:release()
        end)
    end)
end
return test.run_cases(define_tests)
