-- MIT
local test = require("test")
local mcp = require("mcp")
local bounds = require("bounds")
local function define_tests()
    test.describe("MCP peer application tools", function()
        test.it("keeps omitted-node requests local and accepts a bounded peer", function()
            local local_request = assert(mcp.app_tools_arguments({arguments = {}}))
            test.is_nil(local_request.node)
            test.eq(local_request.operation, "list")
            local remote = assert(mcp.app_tools_arguments({arguments = {node = "runner-node"}}))
            test.eq(remote.node, "runner-node")
            local listed = assert(mcp.tests_arguments({arguments = {operation = "list", application = "sdk:app", node = "runner-node"}}))
            test.eq(listed.node, "runner-node")
            local status = assert(mcp.tests_arguments({arguments = {operation = "status", run_id = "run-1", node = "runner-node"}}))
            test.eq(status.node, "runner-node")
            test.is_nil(assert(mcp.tests_arguments({arguments = {operation = "status", run_id = "run-1"}})).node)
        end)
        test.it("adds explicit app_tools calls and mutation keys without changing direct aliases", function()
            local request = assert(mcp.app_tools_arguments({arguments = {operation = "call", node = "runner-node",
                tool = "sdk_run", arguments = {configuration = "ci"}, idempotency_key = "run-1"}}))
            test.eq(request.tool, "sdk_run")
            test.eq(request.idempotency_key, "run-1")
            test.eq(assert(bounds.object(request.arguments)).configuration, "ci")
            local run = assert(mcp.tests_arguments({arguments = {operation = "run", application = "sdk:app", node = "runner-node",
                idempotency_key = "suite-1"}}))
            test.eq(run.idempotency_key, "suite-1")
            test.eq(assert(mcp.tool("app_tools")).operation, "bee.node.binding:app_tools")
            test.eq(assert(mcp.tool("tests")).operation, "bee.node.binding:tests_call")
        end)
        test.it("refuses malformed nodes and mixed discovery/call fields", function()
            for _, node in ipairs({false, 5, "*", "runner\n", string.rep("x", 161)}) do
                test.is_nil(mcp.app_tools_arguments({arguments = {node = node}}))
                test.is_nil(mcp.tests_arguments({arguments = {operation = "list", application = "sdk:app", node = node}}))
            end
            test.is_nil(mcp.app_tools_arguments({arguments = {node = "runner", tool = "sdk_run"}}))
            test.is_nil(mcp.app_tools_arguments({arguments = {operation = "call"}}))
            test.is_nil(mcp.app_tools_arguments({arguments = {operation = "call", tool = "sdk_run", arguments = false}}))
            test.is_nil(mcp.app_tools_arguments({arguments = {operation = "call", tool = "sdk_run", actor_id = "person"}}))
        end)
        test.it("advertises optional node and explicit call fields in the tool schemas", function()
            local tools = assert(bounds.object(assert(mcp.tool("app_tools")).schema.properties))
            for _, field in ipairs({"node", "operation", "tool", "arguments", "idempotency_key"}) do test.not_nil(tools[field]) end
            local tests = assert(bounds.object(assert(mcp.tool("tests")).schema.properties))
            test.not_nil(tests.node)
            test.not_nil(tests.idempotency_key)
        end)
    end)
end
return test.run_cases(define_tests)
