-- SPDX-License-Identifier: MIT
local test = require("test")
local agents = require("agents")
local function run()
    test.describe("Session startup presentation", function()
        test.it("presents preparation progress as starting and retains the build detail", function()
            local detail = "Building the digest-pinned runtime image\nStep 3/6 : COPY bin/ /usr/local/bin/"
            local progress = assert(agents.preparation_progress({type = "text", segment_id = "executor-progress", operation = "replace", channel = "progress", text = detail}))
            test.eq(progress.state, "starting")
            test.eq(progress.detail, detail)
            test.is_nil(agents.preparation_progress({type = "text", segment_id = "executor-progress", operation = "replace", channel = "answer", text = detail}))
            test.is_nil(agents.preparation_progress({type = "text", segment_id = "executor-progress", operation = "replace", channel = "progress", text = string.rep("x", 4097)}))
        end)
        test.it("shows starting until the acknowledged running event arrives", function()
            local pending = assert(agents.placement_progress({execution_state = "starting"}))
            test.eq(pending.state, "starting")
            local running = assert(agents.placement_progress({execution_state = "running"}))
            test.eq(running.state, "working")
        end)
        test.it("shows the exact startup failure and rejects a missing cause", function()
            local failed = assert(agents.placement_progress({execution_state = "start_failed", start_failure = "containers/create: daemon refused"}))
            test.eq(failed.state, "failed")
            test.eq(failed.cause, "containers/create: daemon refused")
            local invalid, reason = agents.placement_progress({execution_state = "start_failed"})
            test.is_nil(invalid)
            test.eq(reason, "failed startup observation omitted its cause")
        end)
    end)
end
return {run = test.run_cases(run)}
