-- MIT. Grok configuration: projection of .grok/config.toml for gateway MCP delivery.
-- Grok loads MCP servers and permissions from $GROK_HOME/config.toml or .grok/config.toml.
local hash = require("hash")

local M = {}
M.REVISION = "bee.grok-config@1"
M.PATH = ".grok/config.toml"
M.PROVIDER_REF = "bee:gateway_endpoint"
M.MAX_CONFIGURATION_BYTES = 8192

type Gateway = {
    endpoint: string,
    action_id: string,
    tools: {string},
    hooks: {string},
    token_environment: string,
    hook_token_environment: string?,
}

type Projection = {
    revision: string,
    path: string,
    content: string,
    digest: string,
    provider_ref: string,
}

local function toml_string(value: string): string
    local escaped = value:gsub("\\", "\\\\"):gsub('"', '\\"'):gsub("\n", "\\n"):gsub("\r", "\\r"):gsub("\t", "\\t")
    return '"' .. escaped .. '"'
end

function M.render_gateway(gateway: Gateway): string
    local url = "http://" .. gateway.endpoint .. "/mcp/" .. gateway.action_id
    local lines = {
        "# generated by bee " .. M.REVISION,
        "[permission]",
        'allow = [',
        '    "MCPTool(bee__*)",',
        ']',
        "",
        "[mcp_servers.bee]",
        "url = " .. toml_string(url),
        "enabled = true",
        "",
        "[mcp_servers.bee.headers]",
        "Authorization = " .. toml_string("Bearer ${" .. gateway.token_environment .. "}"),
        "",
    }
    return table.concat(lines, "\n")
end

function M.projection(gateway: Gateway): (Projection?, string?)
    local content = M.render_gateway(gateway)
    if #content > M.MAX_CONFIGURATION_BYTES then
        return nil, "configuration exceeds " .. tostring(M.MAX_CONFIGURATION_BYTES) .. " bytes"
    end
    local digest, hash_error = hash.sha256(content)
    if hash_error or not digest then return nil, "configuration digest failed" end
    return {
        revision = M.REVISION,
        path = M.PATH,
        content = content,
        digest = digest,
        provider_ref = M.PROVIDER_REF,
    }, nil
end

return M
