-- MIT. Grok configuration: one scoped MCP subtree inserted into the
-- host-approved private configuration snapshot at materialization.
local hash = require("hash")
local canonical = require("canonical")
local quote = require("quote")
local configure_protocol = require("configure_protocol")

local M = {}
M.REVISION = "bee.grok-config@1"
M.PATH = ".grok/config.toml"
M.BASE_PATH = ".grok/.bee-global-config.toml"
M.PROVIDER_REF = "bee:gateway_endpoint"
M.MAX_CONFIGURATION_BYTES = 8192

type Gateway = {
    endpoint: string,
    action_id: string,
    tools: {string},
    hooks: {string},
    token_environment: string,
    hook_token_environment: string?,
}

type Projection = {
    revision: string,
    path: string,
    content: string,
    digest: string,
    provider_ref: string,
    composition: {kind: "toml_insert", base_path: string, path: {string}},
}

local function toml_string(value: string): string
    local escaped = value:gsub("\\", "\\\\"):gsub('"', '\\"'):gsub("\n", "\\n"):gsub("\r", "\\r"):gsub("\t", "\\t")
    return '"' .. escaped .. '"'
end

function M.render_gateway(gateway: Gateway): string
    local url = "http://" .. gateway.endpoint .. "/mcp/" .. gateway.action_id
    local lines = {
        "# generated by bee " .. M.REVISION,
        "[mcp_servers.bee]",
        "url = " .. toml_string(url),
        "enabled = true",
        "",
        "[mcp_servers.bee.headers]",
        "Authorization = " .. toml_string("Bearer ${" .. gateway.token_environment .. "}"),
        "",
    }
    return table.concat(lines, "\n")
end

function M.projection(gateway: Gateway): (Projection?, string?)
    local content = M.render_gateway(gateway)
    if #content > M.MAX_CONFIGURATION_BYTES then
        return nil, "configuration exceeds " .. tostring(M.MAX_CONFIGURATION_BYTES) .. " bytes"
    end
    local digest, hash_error = hash.sha256(content)
    if hash_error or not digest then return nil, "configuration digest failed" end
    return {
        revision = M.REVISION,
        path = M.PATH,
        content = content,
        digest = digest,
        provider_ref = M.PROVIDER_REF,
        composition = {kind = "toml_insert", base_path = M.BASE_PATH, path = {"mcp_servers", "bee"}},
    }, nil
end

function M.hooks_file(gateway: configure_protocol.GatewayInput): (configure_protocol.Configuration?, string?)
    local executable = gateway.hook_command
    if not executable then return nil, "grok hooks require the host-selected hook command" end
    local token = gateway.hook_token_environment
    if not token then return nil, "grok hooks require a separate hook credential environment" end
    local selected: {[string]: unknown} = {}
    for _, event in ipairs(gateway.hooks) do
        if event ~= "SessionStart" and event ~= "UserPromptSubmit" and event ~= "PreToolUse"
            and event ~= "PostToolUse" and event ~= "Stop" then
            return nil, "grok does not support gateway hook event " .. event
        end
        local command = quote.line({executable, "hook-post", gateway.endpoint, gateway.action_id, token, event})
        selected[event] = {{hooks = {{type = "command", command = command, timeout = 3}}}}
    end
    local content, encode_error = canonical.encode({hooks = selected})
    if not content then return nil, encode_error end
    content = content .. "\n"
    if #content > M.MAX_CONFIGURATION_BYTES then return nil, "hook configuration exceeds byte limit" end
    local digest, digest_error = hash.sha256(content)
    if not digest then return nil, tostring(digest_error or "hook configuration digest failed") end
    return {revision = "bee.grok-hooks@1", path = ".grok/hooks/bee.json", content = content,
        digest = digest, provider_ref = configure_protocol.GATEWAY_PROVIDER_REF}, nil
end

return M
