-- MIT. Package browsing never emits an install or unbound filesystem request.
local test = require("test")
local base64 = require("base64")
local contents = require("contents")
local function define_tests()
    test.describe("Module contents", function()
        test.it("binds nested file reads to the exact inspected artifact", function()
            local state = contents.new()
            local initial = contents.start(state, "bee/example", "1.0.0")
            test.eq(initial.operation, "state")
            contents.apply(state, "state", {ok = true, replayed = false, value = {component = "bee/example", version = "1.0.0", digest = string.rep("a", 64),
                entries = {{id = "example:main", kind = "function.lua", data = {source = "return true"}}}, resources = {{id = "example:assets", type = "fs"}}}})
            local listing = contents.activate(state, "example:assets")
            test.not_nil(listing)
            if not listing then return end
            test.eq(listing.operation, "files")
            test.eq(listing.request.expected_digest, string.rep("a", 64))
            contents.apply(state, "files", {ok = true, replayed = false, value = {component = "bee/example", version = "1.0.0", digest = string.rep("a", 64), files = {{name = "docs", type = "directory"}}}})
            local nested = contents.activate(state, "docs")
            test.not_nil(nested)
            if not nested then return end
            test.eq(nested.request.path, "docs")
            contents.apply(state, "files", {ok = true, replayed = false, value = {component = "bee/example", version = "1.0.0", digest = string.rep("a", 64), files = {{name = "guide.md", type = "file"}}}})
            local file = contents.activate(state, "guide.md")
            test.not_nil(file)
            if not file then return end
            test.eq(file.operation, "read_file")
            test.eq(file.request.path, "docs/guide.md")
            contents.apply(state, "read_file", {ok = true, replayed = false, value = {component = "bee/example", version = "1.0.0", digest = string.rep("a", 64), offset = 0,
                content_base64 = base64.encode("hello\n\27[31munsafe"), next_offset = 18}})
            test.eq(state.lines[1], "hello")
            test.is_nil(state.lines[2]:find("\27", 1, true))
            local next = contents.next(state)
            test.not_nil(next)
            if next then test.eq(next.request.offset, 18); test.eq(next.request.expected_digest, string.rep("a", 64)) end
            local back = contents.back(state)
            test.eq(back.request.path, "docs")
        end)
        test.it("refuses changed artifacts and unsafe returned filenames", function()
            local state = contents.new()
            contents.start(state, "bee/example", "1.0.0")
            contents.apply(state, "state", {ok = true, replayed = false, value = {component = "bee/example", version = "2.0.0", digest = string.rep("a", 64), entries = {}, resources = {}}})
            test.eq(#state.rows, 0)
            test.is_true(state.notice:find("Package changed", 1, true) ~= nil)
            contents.apply(state, "files", {ok = true, replayed = false, value = {component = "bee/example", version = "1.0.0", digest = string.rep("a", 64), files = {{name = "../host", type = "file"}}}})
            test.eq(#state.rows, 0)
            test.eq(state.notice, "Invalid package filename")
        end)
    end)
end
return test.run_cases(define_tests)
