-- MIT. Modules only describes Hub calls and retains no authority itself.
local test = require("test")
local model = require("model")
local function ok(value: unknown): model.Reply return {ok = true, code = nil, message = nil, value = value, replayed = false} end
local function define_tests()
    test.describe("Modules model", function()
        test.it("keeps keyword browsing separate from text search and emits only facade intents", function()
            local state = model.new()
            local catalog = model.catalog_intent(state)
            test.eq(catalog.operation, "catalog")
            test.eq(catalog.request and catalog.request.keyword, "bee")
            test.is_nil(catalog.request and catalog.request.query)
            model.set_keyword(state, "")
            model.set_query(state, "docker")
            catalog = model.catalog_intent(state)
            test.eq(catalog.request and catalog.request.keyword, "")
            test.eq(catalog.request and catalog.request.query, "docker")
        end)
        test.it("accepts JSON parameter values with their native types and invalidates a displayed plan", function()
            local state = model.new()
            model.select(state, "userspace/docker")
            model.select_version(state, "0.5.12")
            test.is_nil(model.set_parameter(state, "userspace.docker:port", "8080"))
            test.eq(state.parameters[1].value, 8080)
            model.apply_plan(state, ok({digest = string.rep("a", 64), ready = true, base_revision = 7, modules = {}, missing = {}, migrations = {}, starts = {}, capabilities = {},
                request = {action = "install", component = "userspace/docker", version = "0.5.12", migration_policy = "none",
                    parameters = {{name = "userspace.docker:port", value = 8080}}}}))
            test.not_nil(state.plan)
            test.is_nil(model.set_parameter(state, "userspace.docker:enabled", "false"))
            test.is_nil(state.plan)
            test.not_nil(model.set_parameter(state, "userspace.docker:bad", "not-json"))
        end)
        test.it("binds confirmation to the immutable plan digest and clears it when the request changes", function()
            local state = model.new()
            model.select(state, "userspace/docker")
            model.select_version(state, "0.5.12")
            model.apply_plan(state, ok({digest = string.rep("b", 64), ready = true, base_revision = 7, modules = {}, missing = {}, migrations = {}, starts = {}, capabilities = {},
                request = {action = "install", component = "userspace/docker", version = "0.5.12", migration_policy = "none", parameters = {}}}))
            test.is_nil(model.confirm(state))
            local intent, problem = model.confirm_intent(state)
            test.is_nil(problem)
            test.not_nil(intent)
            if intent then test.eq(intent.operation, "apply"); test.eq(intent.expected_digest, string.rep("b", 64)) end
            model.set_policy(state, "up")
            test.is_nil(state.plan)
            test.is_nil(model.confirm_intent(state))
        end)
        test.it("ignores a delayed plan for an earlier request", function()
            local state = model.new()
            model.select(state, "userspace/docker")
            model.select_version(state, "0.5.12")
            model.set_action(state, "update")
            model.apply_plan(state, ok({digest = string.rep("c", 64), ready = true, base_revision = 7, modules = {}, missing = {}, migrations = {}, starts = {}, capabilities = {},
                request = {action = "install", component = "userspace/docker", version = "0.5.12", parameters = {}, migration_policy = "none"}}))
            test.is_nil(state.plan)
            test.eq(state.notice, "plan belongs to an earlier package selection; ignored")
        end)
        test.it("requires a completed receipt before presenting a successful operation", function()
            local state = model.new()
            model.apply_result(state, ok({state = "failed", message = "transaction failed"}))
            test.not_nil(state.result)
            if state.result then test.is_false(state.result.ok) end
            model.apply_result(state, ok({state = "recovery_required", message = "check status"}))
            test.not_nil(state.result)
            if state.result then test.is_false(state.result.ok) end
            model.apply_result(state, ok({state = "published", message = "publication is not completion"}))
            if state.result then test.is_false(state.result.ok) end
            model.apply_result(state, ok({}))
            if state.result then test.is_false(state.result.ok) end
            model.apply_result(state, ok({state = "complete", message = "done"}))
            if state.result then test.is_true(state.result.ok) end
        end)
    end)
end
return test.run_cases(define_tests)
