local test = require("test")
local sql = require("sql")
local funcs = require("funcs")
local registry = require("registry")
local guard = require("guard")
local schema = require("schema")
local DATABASE = "bee.tests.stateguard:db"
local MIGRATION = "bee.approvals.migrations:approvals"
local FUTURE = "bee.approvals.migrations:future"
local function migrate(id: string)
    local result, problem = funcs.call(MIGRATION, {database_id = DATABASE, direction = "up", id = id})
    assert(not problem, tostring(problem))
    assert(type(result) == "table" and result.status ~= "error", tostring(type(result) == "table" and result.error))
end
local function reset(): sql.DB
    local db = assert(sql.get(DATABASE))
    for _, name in ipairs(schema.TABLES) do assert(db:execute("DROP TABLE IF EXISTS " .. name)) end
    assert(db:execute("DROP TABLE IF EXISTS _migrations"))
    return db
end
local function define_tests()
    test.describe("Bee state version guard", function()
        test.it("refuses a migrated schema newer than the binary before an approval query", function()
            local db = reset()
            db:release()
            migrate(FUTURE)
            db = assert(sql.get(DATABASE))
            local problem = guard.check(db, "/isolated/person/bee", "0.2.0", {[MIGRATION] = true}, {"bee.approvals.migrations:"})
            test.not_nil(problem)
            test.is_true(tostring(problem):find("/isolated/person/bee", 1, true) ~= nil)
            test.is_true(tostring(problem):find(FUTURE, 1, true) ~= nil)
            test.is_true(tostring(problem):find("Install", 1, true) ~= nil)
            test.is_true(tostring(problem):find("or newer", 1, true) ~= nil)
            db:release()
        end)
        test.it("allows a normal forward upgrade and records its writer", function()
            local db = reset()
            test.is_nil(guard.check(db, "/isolated/person/bee", "0.1.0", {}, {}))
            assert(guard.record(db, "0.1.0", "old", {}))
            db:release()
            migrate(MIGRATION)
            db = assert(sql.get(DATABASE))
            test.is_nil(guard.check(db, "/isolated/person/bee", "0.2.0", {[MIGRATION] = true}, {"bee.approvals.migrations:"}))
            assert(guard.record(db, "0.2.0", "new", {MIGRATION}))
            test.is_nil(guard.check(db, "/isolated/person/bee", "0.2.0", {[MIGRATION] = true}, {"bee.approvals.migrations:"}))
            local problem = guard.check(db, "/isolated/person/bee", "0.1.0", {[MIGRATION] = true}, {"bee.approvals.migrations:"})
            test.eq(problem, 'Bee refuses to start: state in "/isolated/person/bee" was written by Bee 0.2.0, newer than this Bee 0.1.0. Install Bee 0.2.0 or newer and open this folder again.')
            db:release()
        end)
        test.it("checks schema even when development builds share a version", function()
            local db = reset()
            assert(guard.record(db, "0.2.0-dev", "future", {FUTURE}))
            local problem = guard.check(db, "/isolated/person/bee", "0.2.0-dev", {[MIGRATION] = true}, {"bee.approvals.migrations:"})
            test.is_true(tostring(problem):find(FUTURE, 1, true) ~= nil)
            db:release()
        end)
        test.it("boot records the host migration schema beside the writer version", function()
            local db = assert(sql.get("bee:db"))
            local rows = assert(db:query("SELECT description FROM _migrations WHERE id = ?", {guard.WRITER}))
            test.eq(#rows, 1)
            test.is_true(tostring(rows[1].description):find(MIGRATION, 1, true) ~= nil)
            db:release()
        end)
        test.it("keeps third-party ledger entries outside the Bee schema check", function()
            local db = reset()
            assert(guard.record(db, "0.2.0", "current", {MIGRATION}))
            assert(db:execute("INSERT INTO _migrations(id, description) VALUES ('app.progress:migration', 'installed app')"))
            test.is_nil(guard.check(db, "/isolated/person/bee", "0.2.0", {[MIGRATION] = true}, {"bee.approvals.migrations:"}))
            db:release()
        end)
        test.it("records the Bee writer when an app database migrates after boot", function()
            local db = reset()
            db:release()
            local prepared, problem = guard.prepare(DATABASE)
            test.is_true(prepared == true, tostring(problem))
            db = assert(sql.get(DATABASE))
            local rows = assert(db:query("SELECT description FROM _migrations WHERE id = ?", {guard.WRITER}))
            test.eq(#rows, 1)
            test.is_true(tostring(rows[1].description):find('"version"', 1, true) ~= nil)
            db:release()
        end)
        test.it("refuses a newer app writer without changing its ledger", function()
            local db = reset()
            assert(guard.record(db, "999.0.0", "future", {}))
            local before = assert(db:query("SELECT description FROM _migrations WHERE id = ?", {guard.WRITER}))[1].description
            db:release()
            local prepared, problem = guard.prepare(DATABASE)
            test.is_nil(prepared)
            test.is_true(tostring(problem):find("Install Bee 999.0.0 or newer", 1, true) ~= nil)
            db = assert(sql.get(DATABASE))
            test.eq(assert(db:query("SELECT description FROM _migrations WHERE id = ?", {guard.WRITER}))[1].description, before)
            db:release()
        end)
        test.it("runs before the migration bootloader", function()
            local entry = assert(registry.get("bee.persist:state_guard_bootloader"))
            local migration = assert(registry.get("wippy.migration:migration_bootloader"))
            test.is_true(entry.meta.order < migration.meta.order)
        end)
        test.it("completes its startup check before the bootloader starts", function()
            local gate = assert(registry.get("bee.persist:state_guard_service"))
            local bootloader = assert(registry.get("wippy.bootloader:bootloader.service"))
            test.eq(gate.data.lifecycle.startup, "complete")
            test.eq(gate.data.host, "bee:workers")
            test.eq(gate.data.lifecycle.restart.max_attempts, 1)
            test.eq(bootloader.data.lifecycle.requires[1], "bee.persist:state_guard_service")
        end)
    end)
end
return test.run_cases(define_tests)
