-- MIT. The model, pure: names are bounded aliases, a node that leaves
-- membership is retained as unavailable, presence and stats fold in as
-- the owner answered, an attach intent exists only for an opened
-- reachable desktop, control is refused where a controller is known, and
-- the checkpoint restores selection by identity against later reports.
local test = require("test")
local model = require("model")
local directory = require("directory")
local types = require("types")
type Object = {[string]: unknown}
local function members(ids: {string}, local_id: string): {directory.Member}
    local list: {directory.Member} = {}
    for _, id in ipairs(ids) do list[#list + 1] = {node_id = id, is_local = id == local_id, addr = id == local_id and "" or "10.0.0.2:7946"} end
    return list
end
local function catalog(controller: string): directory.Catalog
    return {available = true, reason = "", owner_generation = "gen-1", desktops = {{workspace_id = "ws1", desktop_id = "d1", label = "main", controller = controller, observers = 0},
        {workspace_id = "ws1", desktop_id = "d2", label = "second", controller = "", observers = 0}}}
end
local function define_tests()
    test.describe("Hive Manager model", function()
        test.it("keeps advertised display clients separate from service health and rejects stale service replies", function()
            local state = model.new("live", "", {})
            model.apply_members(state, {{node_id = "ordinary-name", is_local = false, addr = "", client_only = true},
                {node_id = "bee-client-not-a-role", is_local = true, addr = ""}})
            test.is_true(state.index["ordinary-name"].client_only)
            test.is_false(state.index["bee-client-not-a-role"].client_only)
            model.apply_presence(state, "ordinary-name", types.reply_error("r", types.fault("UNAVAILABLE", "not configured")))
            test.eq(state.index["ordinary-name"].detail, "")
            model.apply_presence(state, "ordinary-name", types.reply_ok("r", {role = "leader", cluster_size = 2}))
            test.eq(state.index["ordinary-name"].status, "unknown")
            model.apply_catalog(state, "ordinary-name", catalog(""))
            test.is_nil(state.catalogs["ordinary-name"])
        end)
        test.it("bounds friendly names and treats them as display aliases only", function()
            local names = model.names({forge = "Forge", laptop = string.rep("x", 200), bad = "a\27b", [""] = "empty", attic = 7})
            test.eq(names["forge"], "Forge")
            test.is_nil(names["laptop"])
            test.is_nil(names["bad"])
            test.is_nil(names["attic"])
            test.eq(model.text("run \27[31mred\27[0m\r\n", 8), "run  [31…")
            local state = model.new("live", "", names)
            model.apply_members(state, members({"laptop", "forge"}, "forge"))
            test.eq(state.nodes[1].node_id, "forge")
            test.eq(state.nodes[1].label, "Forge")
            test.eq(state.nodes[2].label, "laptop")
            test.eq(state.selected_node, "forge")
        end)
        test.it("retains a node that leaves membership as unavailable and folds presence in as answered", function()
            local state = model.new("live", "", {})
            model.set_supervisor(state, false, "supervisor is not running")
            test.eq(state.hive, "unavailable")
            model.set_supervisor(state, true, "")
            test.eq(state.hive, "running")
            test.eq(state.hive_detail, "")
            model.set_supervisor(state, false, "lookup timed out")
            test.eq(state.hive, "unavailable")
            test.eq(state.hive_detail, "lookup timed out")
            model.apply_members(state, members({"forge", "laptop"}, "forge"), nil)
            model.apply_presence(state, "laptop", types.reply_ok("r", {role = "follower", cluster_size = 2, sampled_at = "2026-09-09T00:00:00.000Z"}))
            test.eq(state.index["laptop"].status, "reachable")
            test.eq(state.index["laptop"].cluster_size, 2)
            model.apply_presence(state, "forge", types.reply_error("r", types.fault("UNAVAILABLE", "no supervisor to ask")))
            test.eq(state.index["forge"].status, "unavailable")
            test.eq(state.index["forge"].detail, "UNAVAILABLE: no supervisor to ask")
            model.apply_members(state, members({"forge"}, "forge"), "membership lists more than 64 nodes")
            test.eq(#state.nodes, 2)
            test.eq(state.index["laptop"].status, "unavailable")
            test.eq(state.index["laptop"].detail, "left membership; retained until it returns")
            test.is_false(state.index["laptop"].member)
            test.eq(state.membership_detail, "membership lists more than 64 nodes")
            model.apply_stats(state, "forge", types.reply_ok("r", {memory = {heap_alloc = 2048}, goroutines = 12}))
            test.eq(state.index["forge"].heap, 2048)
            test.eq(state.index["forge"].goroutines, 12)
            model.apply_stats(state, "forge", types.reply_error("r", types.fault("UNAVAILABLE", "gone")))
            test.is_nil(state.index["forge"].heap)
            model.select_node(state, "nowhere")
            test.eq(state.selected_node, "forge")
        end)
        test.it("builds an attach intent only for an opened reachable desktop and refuses control where a controller is known", function()
            local state = model.new("live", "", {})
            local _, no_node = model.attach_intent(state, "observe", "key-1")
            test.eq(no_node, "select a node first")
            model.apply_members(state, members({"forge", "laptop"}, "forge"))
            model.select_node(state, "laptop")
            local _, unreachable = model.attach_intent(state, "observe", "key-1")
            test.is_true(tostring(unreachable):find("laptop is unknown", 1, true) ~= nil)
            model.apply_presence(state, "laptop", types.reply_ok("r", {role = "follower", cluster_size = 2}))
            local _, unopened = model.attach_intent(state, "observe", "key-1")
            test.eq(unopened, "open the node's desktops first")
            model.apply_catalog(state, "laptop", {available = false, reason = "desktop catalog is admitted to native clients only", owner_generation = "", desktops = {}})
            local _, unavailable = model.attach_intent(state, "observe", "key-1")
            test.eq(unavailable, "desktop catalog is admitted to native clients only")
            model.apply_catalog(state, "laptop", catalog("bee.client.laptop"))
            local _, unselected = model.attach_intent(state, "observe", "key-1")
            test.eq(unselected, "select a desktop first")
            model.set_pane(state, "desktops")
            model.move(state, 1)
            test.eq(state.selected_desktop, model.desktop_key("ws1", "d1"))
            test.is_false(model.can_control(state))
            local _, controlled = model.attach_intent(state, "control", "key-2")
            test.eq(controlled, "desktop is controlled by bee.client.laptop; choose observe")
            local intent = model.attach_intent(state, "observe", "key-1")
            if not intent then error("intent") end
            test.eq(intent.node_id, "laptop")
            test.eq(intent.desktop_id, "d1")
            test.eq(intent.mode, "observe")
            test.eq(intent.owner_generation, "gen-1")
            test.eq(intent.idempotency_key, "key-1")
            test.eq(model.pending_intent(state), intent)
            model.apply_outcome(state, intent, {ok = false, code = "UNCERTAIN", message = "no reply after dispatch"})
            test.eq(model.pending_intent(state), intent)
            test.is_true(state.outcome:find("replayed on retry", 1, true) ~= nil)
            local _, busy = model.attach_intent(state, "observe", "key-1")
            test.eq(busy, "a desktop request is already pending")
            model.apply_outcome(state, intent, {ok = true, code = "", message = "", session_id = "s-1", mode = "observe"})
            test.is_nil(state.pending)
            test.eq(state.sessions[model.desktop_key("ws1", "d1")].session_id, "s-1")
            test.is_true(state.outcome:find("Attached observe session s-1", 1, true) ~= nil)
            model.move(state, 1)
            test.is_true(model.can_control(state))
            local second = model.attach_intent(state, "control", "key-2")
            if not second then error("second") end
            model.apply_outcome(state, second, {ok = false, code = "UNSUPPORTED_CAPABILITY", message = "not wired\27"})
            test.eq(state.outcome, "UNSUPPORTED_CAPABILITY: not wired ")
            model.select_node(state, "forge")
            test.is_nil(state.selected_desktop)
            model.apply_catalog(state, "laptop", {available = true, reason = "", owner_generation = "gen-2", desktops = {}})
            model.select_node(state, "laptop")
            model.select_desktop(state, model.desktop_key("ws1", "d1"))
            model.apply_catalog(state, "laptop", {available = true, reason = "", owner_generation = "gen-2", desktops = {}})
            test.is_nil(state.selected_desktop)
        end)
        test.it("keeps the list within the display bound by dropping the earliest departed node, the selected one last", function()
            local state = model.new("live", "", {})
            local ids: {string} = {}
            for index = 1, model.MAX_NODES do ids[#ids + 1] = string.format("n%03d", index) end
            model.apply_members(state, members(ids, "n001"))
            test.eq(#state.nodes, model.MAX_NODES)
            local fewer: {string} = {}
            for index = 1, model.MAX_NODES - 3 do fewer[#fewer + 1] = ids[index] end
            model.apply_members(state, members(fewer, "n001"))
            test.eq(#state.nodes, model.MAX_NODES)
            test.eq(state.index["n064"].status, "unavailable")
            model.select_node(state, "n064")
            local later: {string} = {}
            for index = 1, model.MAX_NODES - 3 do later[#later + 1] = ids[index] end
            later[#later + 1] = "fresh-1"
            later[#later + 1] = "fresh-2"
            model.apply_members(state, members(later, "n001"))
            test.eq(#state.nodes, model.MAX_NODES)
            test.is_nil(state.index["n062"])
            test.is_nil(state.index["n063"])
            test.eq(state.selected_node, "n064")
            test.eq(state.index["n064"].status, "unavailable")
            later[#later + 1] = "fresh-3"
            model.apply_members(state, members(later, "n001"))
            test.eq(#state.nodes, model.MAX_NODES)
            test.is_nil(state.index["n064"])
            test.is_true(state.selected_node ~= nil and state.index[state.selected_node :: string] ~= nil)
        end)
        test.it("moves within the focused pane and toggles panes", function()
            local state = model.new("live", "", {})
            model.move(state, 1)
            model.apply_members(state, members({"a", "b", "c"}, "a"))
            model.move(state, 5)
            test.eq(state.selected_node, "c")
            model.move(state, -1)
            test.eq(state.selected_node, "b")
            model.toggle_pane(state)
            test.eq(state.pane, "desktops")
            model.move(state, 1)
            test.is_nil(state.selected_desktop)
            model.apply_catalog(state, "b", catalog(""))
            model.move(state, 1)
            test.eq(state.selected_desktop, model.desktop_key("ws1", "d1"))
            model.move(state, -3)
            test.eq(state.selected_desktop, model.desktop_key("ws1", "d1"))
            model.toggle_technical(state)
            test.is_true(state.technical)
        end)
        test.it("checkpoints selection by identity and resolves it against later reports", function()
            local state = model.new("live", "", {})
            model.apply_members(state, members({"forge", "laptop"}, "forge"))
            model.select_node(state, "laptop")
            model.apply_catalog(state, "laptop", catalog(""))
            model.select_desktop(state, model.desktop_key("ws1", "d2"))
            model.toggle_technical(state)
            local saved = model.checkpoint(state)
            local restored = model.new("live", "", {})
            test.is_true(model.restore(restored, saved))
            test.is_nil(restored.selected_node)
            test.is_true(restored.technical)
            model.apply_members(restored, members({"forge", "laptop"}, "forge"))
            test.eq(restored.selected_node, "laptop")
            test.is_nil(restored.selected_desktop)
            model.apply_catalog(restored, "laptop", catalog(""))
            test.eq(restored.selected_desktop, model.desktop_key("ws1", "d2"))
            test.is_nil(restored.wanted_desktop)
            test.is_false(model.restore(model.new("live", "", {}), "5"))
            test.is_false(model.restore(model.new("live", "", {}), '{"selected_node": 5}'))
            test.is_false(model.restore(model.new("live", "", {}), '{"selected_desktop": "' .. string.rep("x", 401) .. '"}'))
            test.is_false(model.restore(model.new("live", "", {}), '{"technical": "yes"}'))
            local partial = model.new("live", "", {})
            test.is_true(model.restore(partial, "{}"))
            model.apply_members(partial, members({"forge"}, "forge"))
            test.eq(partial.selected_node, "forge")
        end)
    end)
end
return require("test").run_cases(define_tests)
