-- MIT. The model, pure: names are bounded aliases, a node that leaves
-- membership is retained as unavailable, presence and stats fold in as
-- the owner answered, an attach intent exists only for a listed workspace
-- of a reachable node and the checkpoint restores selection by identity against later reports.
local test = require("test")
local model = require("model")
local directory = require("directory")
local types = require("types")
type Object = {[string]: unknown}
local function members(ids: {string}, local_id: string): {directory.Member}
    local list: {directory.Member} = {}
    for _, id in ipairs(ids) do list[#list + 1] = {node_id = id, is_local = id == local_id, addr = id == local_id and "" or "10.0.0.2:7946"} end
    return list
end
local function catalog(): directory.Catalog
    return {available = true, reason = "", owner_generation = "gen-1", workspaces = {{workspace_id = "ws1", label = "main", served = true},
        {workspace_id = "ws2", label = "second", served = false}}}
end
local function define_tests()
    test.describe("Hive Manager model", function()
        test.it("retires departed rows after 60s and cancels retirement on return or uncertain membership", function()
            local state = model.new({})
            local both = members({"forge", "display"}, "forge")
            local alone = members({"forge"}, "forge")
            model.apply_members(state, both, nil, 0)
            model.select_node(state, "display")
            model.apply_members(state, alone, nil, 1000)
            model.apply_members(state, alone, nil, 60999)
            test.is_true(state.index["display"] ~= nil)
            model.apply_members(state, both, nil, 61000)
            model.apply_members(state, alone, nil, 62000)
            model.apply_members(state, alone, "membership unavailable", 122000)
            test.is_true(state.index["display"] ~= nil)
            model.apply_members(state, alone, nil, 123000)
            model.apply_members(state, alone, nil, 182999)
            test.is_true(state.index["display"] ~= nil)
            model.apply_members(state, alone, nil, 183000)
            test.is_nil(state.index["display"])
            test.eq(state.selected_node, "forge")
            test.eq(#state.nodes, 1)
            model.apply_members(state, both, nil, 184000)
            test.is_true(state.index["display"].member)
        end)
        test.it("merges reported nodes from an uncertain sample without aging omitted rows", function()
            local state = model.new({})
            local both = members({"forge", "laptop", "tablet"}, "forge")
            model.apply_members(state, both, nil, 0)
            model.apply_presence(state, "laptop", types.reply_ok("r", {role = "follower", cluster_size = 3}))
            model.apply_members(state, members({"forge", "tablet"}, "forge"), nil, 1000)
            test.is_false(state.index["laptop"].member)
            model.apply_members(state, members({"forge", "tablet", "new-node"}, "forge"), "membership sample truncated", 70000)
            test.is_true(state.index["new-node"] ~= nil and state.index["new-node"].member)
            test.is_false(state.index["laptop"].member)
            test.is_true(state.index["laptop"].absent_since == nil)
            test.eq(state.index["laptop"].status, "unavailable")
            model.apply_members(state, members({"forge", "laptop", "tablet", "new-node"}, "forge"), nil, 70001)
            test.is_true(state.index["laptop"].member)
            test.eq(state.index["laptop"].status, "unknown")
            test.eq(state.index["laptop"].detail, "")
        end)
        test.it("preserves live statuses and clears only a returning node's leave status", function()
            local state = model.new({})
            model.apply_members(state, members({"forge", "laptop", "tablet"}, "forge"), nil, 0)
            model.apply_presence(state, "laptop", types.reply_ok("r", {role = "follower", cluster_size = 3}))
            model.apply_presence(state, "tablet", types.reply_error("r", types.fault("UNAVAILABLE", "probe failed")))
            model.apply_members(state, members({"forge", "tablet"}, "forge"), nil, 1000)
            model.apply_members(state, members({"forge", "laptop", "tablet"}, "forge"), nil, 2000)
            test.eq(state.index["laptop"].status, "unknown")
            test.eq(state.index["laptop"].detail, "")
            test.eq(state.index["tablet"].status, "unavailable")
            test.eq(state.index["tablet"].detail, "UNAVAILABLE: probe failed")
            model.apply_members(state, members({"forge", "laptop", "tablet"}, "forge"), nil, 3000)
            test.eq(state.index["laptop"].status, "unknown")
            test.eq(state.index["tablet"].status, "unavailable")
            test.eq(state.index["tablet"].detail, "UNAVAILABLE: probe failed")
        end)
        test.it("clears target state when selected or pending nodes are removed", function()
            local state = model.new({})
            model.apply_members(state, members({"forge", "laptop"}, "forge"), nil, 0)
            model.select_node(state, "laptop")
            model.apply_presence(state, "laptop", types.reply_ok("r", {role = "follower", cluster_size = 2}))
            model.apply_catalog(state, "laptop", catalog())
            model.set_pane(state, "workspaces")
            model.move(state, 1)
            local intent = model.attach_intent(state, "observe", "pending-key")
            if not intent then error("pending intent missing") end
            state.wanted_workspace = "ws1"
            model.apply_members(state, members({"forge"}, "forge"), nil, 1000)
            model.apply_members(state, members({"forge"}, "forge"), nil, 61000)
            test.is_nil(state.index["laptop"])
            test.is_nil(state.catalogs["laptop"])
            test.is_nil(state.sessions["laptop"])
            test.is_nil(state.pending)
            test.is_nil(state.wanted_workspace)
            test.eq(state.selected_node, "forge")
            model.apply_catalog(state, "forge", catalog())
            test.is_nil(state.selected_workspace)
        end)
        test.it("keeps advertised display clients separate from service health and rejects stale service replies", function()
            local state = model.new({})
            model.apply_members(state, {{node_id = "ordinary-name", is_local = false, addr = "", client_only = true},
                {node_id = "bee-client-not-a-role", is_local = true, addr = ""}})
            test.is_true(state.index["ordinary-name"].client_only)
            test.is_false(state.index["bee-client-not-a-role"].client_only)
            model.apply_presence(state, "ordinary-name", types.reply_error("r", types.fault("UNAVAILABLE", "not configured")))
            test.eq(state.index["ordinary-name"].detail, "")
            model.apply_presence(state, "ordinary-name", types.reply_ok("r", {role = "leader", cluster_size = 2}))
            test.eq(state.index["ordinary-name"].status, "unknown")
            model.apply_catalog(state, "ordinary-name", catalog())
            test.is_nil(state.catalogs["ordinary-name"])
        end)
        test.it("bounds friendly names and treats them as display aliases only", function()
            local names = model.names({forge = "Forge", laptop = string.rep("x", 200), bad = "a\27b", [""] = "empty", attic = 7})
            test.eq(names["forge"], "Forge")
            test.is_nil(names["laptop"])
            test.is_nil(names["bad"])
            test.is_nil(names["attic"])
            test.eq(model.text("run \27[31mred\27[0m\r\n", 8), "run  [31…")
            local state = model.new(names)
            model.apply_members(state, members({"laptop", "forge"}, "forge"))
            test.eq(state.nodes[1].node_id, "forge")
            test.eq(state.nodes[1].label, "Forge")
            test.eq(state.nodes[2].label, "laptop")
            test.eq(state.selected_node, "forge")
        end)
        test.it("retains a node that leaves membership as unavailable and folds presence in as answered", function()
            local state = model.new({})
            model.set_supervisor(state, false, "supervisor is not running")
            test.eq(state.hive, "unavailable")
            model.set_supervisor(state, true, "")
            test.eq(state.hive, "running")
            test.eq(state.hive_detail, "")
            model.set_supervisor(state, false, "lookup timed out")
            test.eq(state.hive, "unavailable")
            test.eq(state.hive_detail, "lookup timed out")
            model.apply_members(state, members({"forge", "laptop"}, "forge"), nil)
            model.apply_presence(state, "laptop", types.reply_ok("r", {role = "follower", cluster_size = 2, sampled_at = "2026-09-09T00:00:00.000Z"}))
            test.eq(state.index["laptop"].status, "reachable")
            test.eq(state.index["laptop"].cluster_size, 2)
            model.apply_presence(state, "forge", types.reply_error("r", types.fault("UNAVAILABLE", "no supervisor to ask")))
            test.eq(state.index["forge"].status, "unavailable")
            test.eq(state.index["forge"].detail, "UNAVAILABLE: no supervisor to ask")
            model.apply_members(state, members({"forge"}, "forge"), nil)
            test.eq(#state.nodes, 2)
            test.eq(state.index["laptop"].status, "unavailable")
            test.eq(state.index["laptop"].detail, "left membership; retiring after 60s")
            test.is_false(state.index["laptop"].member)
            test.eq(state.membership_detail, "")
            model.apply_stats(state, "forge", types.reply_ok("r", {memory = {heap_alloc = 2048}, goroutines = 12}))
            test.eq(state.index["forge"].heap, 2048)
            test.eq(state.index["forge"].goroutines, 12)
            model.apply_stats(state, "forge", types.reply_error("r", types.fault("UNAVAILABLE", "gone")))
            test.is_nil(state.index["forge"].heap)
            model.select_node(state, "nowhere")
            test.eq(state.selected_node, "forge")
        end)
        test.it("builds an attach intent only for a listed workspace of a reachable node", function()
            local state = model.new({})
            local _, no_node = model.attach_intent(state, "observe", "key-1")
            test.eq(no_node, "select a node first")
            model.apply_members(state, members({"forge", "laptop"}, "forge"))
            model.select_node(state, "laptop")
            local _, unreachable = model.attach_intent(state, "observe", "key-1")
            test.is_true(tostring(unreachable):find("laptop is unknown", 1, true) ~= nil)
            model.apply_presence(state, "laptop", types.reply_ok("r", {role = "follower", cluster_size = 2}))
            local _, unopened = model.attach_intent(state, "observe", "key-1")
            test.eq(unopened, "open the node's workspaces first")
            model.apply_catalog(state, "laptop", {available = false, reason = "workspace catalog is unavailable", owner_generation = "", workspaces = {}})
            local _, unavailable = model.attach_intent(state, "observe", "key-1")
            test.eq(unavailable, "workspace catalog is unavailable")
            model.apply_catalog(state, "laptop", catalog())
            local _, unselected = model.attach_intent(state, "observe", "key-1")
            test.eq(unselected, "select a workspace first")
            model.set_pane(state, "workspaces")
            model.move(state, 1)
            test.eq(state.selected_workspace, "ws1")
            test.is_true(model.can_control(state))
            local intent = model.attach_intent(state, "observe", "key-1")
            if not intent then error("intent") end
            test.eq(intent.node_id, "laptop")
            test.eq(intent.workspace_id, "ws1")
            test.eq(intent.mode, "observe")
            test.eq(intent.owner_generation, "gen-1")
            test.eq(intent.idempotency_key, "key-1")
            test.eq(model.pending_intent(state), intent)
            model.apply_outcome(state, intent, {ok = false, code = "UNCERTAIN", message = "no reply after dispatch"})
            test.eq(model.pending_intent(state), intent)
            test.is_true(state.outcome:find("replayed on retry", 1, true) ~= nil)
            local _, busy = model.attach_intent(state, "observe", "key-1")
            test.eq(busy, "a desktop request is already pending")
            model.apply_outcome(state, intent, {ok = true, code = "", message = "", session_id = "s-1", mode = "observe"})
            test.is_nil(state.pending)
            local remembered = model.session(state, "laptop", "ws1")
            if not remembered then error("session missing") end
            test.eq(remembered.session_id, "s-1")
            test.is_true(state.outcome:find("Attached observe session s-1", 1, true) ~= nil)
            -- The session ends with the view presenting it.
            model.end_session(state, "laptop", "ws1")
            test.is_nil(model.session(state, "laptop", "ws1"))
            model.move(state, 1)
            test.is_true(model.can_control(state))
            local second = model.attach_intent(state, "control", "key-2")
            if not second then error("second") end
            model.apply_outcome(state, second, {ok = false, code = "UNSUPPORTED_CAPABILITY", message = "not wired\27"})
            test.eq(state.outcome, "UNSUPPORTED_CAPABILITY: not wired ")
            model.select_node(state, "forge")
            test.is_nil(state.selected_workspace)
            model.apply_catalog(state, "laptop", {available = true, reason = "", owner_generation = "gen-2", workspaces = {}})
            model.select_node(state, "laptop")
            model.select_workspace(state, "ws1")
            model.apply_catalog(state, "laptop", {available = true, reason = "", owner_generation = "gen-2", workspaces = {}})
            test.is_nil(state.selected_workspace)
        end)
        test.it("binds confirmation to the displayed identity without making an unconfirmed request replayable", function()
            local state = model.new({})
            model.apply_members(state, members({"forge"}, "forge"))
            model.apply_presence(state, "forge", types.reply_ok("r", {role = "leader", cluster_size = 1}))
            model.apply_catalog(state, "forge", catalog())
            model.set_pane(state, "workspaces")
            model.move(state, 1)
            local shown = model.preview_intent(state, "control", "confirmed-key")
            if not shown then error("preview missing") end
            test.is_nil(model.pending_intent(state))
            model.move(state, 1)
            local redirected = model.confirm_intent(state, shown)
            test.is_nil(redirected)
            test.is_nil(model.pending_intent(state))
            model.move(state, -1)
            local replacement = catalog()
            replacement.owner_generation = "gen-2"
            model.apply_catalog(state, "forge", replacement)
            test.is_nil(model.confirm_intent(state, shown))
            test.is_nil(model.pending_intent(state))
            local fresh = model.preview_intent(state, "control", "fresh-key")
            if not fresh then error("fresh preview missing") end
            local accepted = model.confirm_intent(state, fresh)
            if not accepted then error("confirmation missing") end
            test.eq(accepted.workspace_id, "ws1")
            test.eq(accepted.owner_generation, "gen-2")
            test.eq(accepted.idempotency_key, "fresh-key")
            model.apply_outcome(state, accepted, {ok = false, code = "UNCERTAIN", message = "lost reply"})
            test.eq(model.pending_intent(state), accepted)
        end)
        test.it("keeps one workspace identity on different nodes and replacement owners separate", function()
            local state = model.new({})
            model.apply_members(state, members({"forge", "laptop"}, "forge"))
            for _, id in ipairs({"forge", "laptop"}) do
                model.apply_presence(state, id, types.reply_ok("r", {role = "follower", cluster_size = 2}))
                model.apply_catalog(state, id, catalog())
            end
            model.set_pane(state, "workspaces")
            model.move(state, 1)
            local intent = model.attach_intent(state, "control", "key")
            if not intent then error("intent missing") end
            model.apply_outcome(state, intent, {ok = true, code = "", message = "", session_id = "forge-session", mode = "control"})
            test.is_true(model.session(state, "forge", "ws1") ~= nil)
            model.select_node(state, "laptop")
            model.apply_catalog(state, "laptop", catalog())
            model.move(state, 1)
            test.is_nil(model.session(state, "laptop", "ws1"))
            local replacement = catalog()
            replacement.owner_generation = "gen-2"
            model.apply_catalog(state, "forge", replacement)
            test.is_nil(model.session(state, "forge", "ws1"))
            model.apply_outcome(state, intent, {ok = true, code = "", message = "", session_id = "late-old-session", mode = "control"})
            test.is_nil(model.session(state, "forge", "ws1"))
            test.is_true(state.outcome:find("earlier catalog", 1, true) ~= nil)
        end)
        test.it("keeps the list within the display bound by dropping the earliest departed node, the selected one last", function()
            local state = model.new({})
            local ids: {string} = {}
            for index = 1, model.MAX_NODES do ids[#ids + 1] = string.format("n%03d", index) end
            model.apply_members(state, members(ids, "n001"))
            test.eq(#state.nodes, model.MAX_NODES)
            local fewer: {string} = {}
            for index = 1, model.MAX_NODES - 3 do fewer[#fewer + 1] = ids[index] end
            model.apply_members(state, members(fewer, "n001"))
            test.eq(#state.nodes, model.MAX_NODES)
            test.eq(state.index["n064"].status, "unavailable")
            model.select_node(state, "n064")
            local later: {string} = {}
            for index = 1, model.MAX_NODES - 3 do later[#later + 1] = ids[index] end
            later[#later + 1] = "fresh-1"
            later[#later + 1] = "fresh-2"
            model.apply_members(state, members(later, "n001"))
            test.eq(#state.nodes, model.MAX_NODES)
            test.is_nil(state.index["n062"])
            test.is_nil(state.index["n063"])
            test.eq(state.selected_node, "n064")
            test.eq(state.index["n064"].status, "unavailable")
            later[#later + 1] = "fresh-3"
            model.apply_members(state, members(later, "n001"))
            test.eq(#state.nodes, model.MAX_NODES)
            test.is_nil(state.index["n064"])
            test.is_true(state.selected_node ~= nil and state.index[state.selected_node :: string] ~= nil)
        end)
        test.it("keeps the list bounded across changing truncated prefixes", function()
            local state = model.new({})
            local ids: {string} = {}
            for index = 1, model.MAX_NODES do ids[#ids + 1] = string.format("n%03d", index) end
            model.apply_members(state, members(ids, "n001"), nil, 0)
            model.select_node(state, "n001")
            for round = 1, 12 do
                local sample: {string} = {}
                for index = round, round + model.MAX_NODES - 2 do
                    sample[#sample + 1] = ids[((index - 1) % #ids) + 1]
                end
                sample[#sample + 1] = "partial-" .. tostring(round)
                model.apply_members(state, members(sample, "n001"), "membership sample truncated", round * 1000)
                test.eq(#state.nodes, model.MAX_NODES)
                test.eq(state.selected_node, "n001")
                test.is_true(state.index["n001"].member)
                test.is_true(state.index["partial-" .. tostring(round)] ~= nil)
            end
        end)
        test.it("moves within the focused pane and toggles panes", function()
            local state = model.new({})
            model.move(state, 1)
            model.apply_members(state, members({"a", "b", "c"}, "a"))
            model.move(state, 5)
            test.eq(state.selected_node, "c")
            model.move(state, -1)
            test.eq(state.selected_node, "b")
            model.toggle_pane(state)
            test.eq(state.pane, "workspaces")
            model.move(state, 1)
            test.is_nil(state.selected_workspace)
            model.apply_catalog(state, "b", catalog())
            model.move(state, 1)
            test.eq(state.selected_workspace, "ws1")
            model.move(state, -3)
            test.eq(state.selected_workspace, "ws1")
            model.toggle_technical(state)
            test.is_true(state.technical)
        end)
        test.it("checkpoints selection by identity and resolves it against later reports", function()
            local state = model.new({})
            model.apply_members(state, members({"forge", "laptop"}, "forge"))
            model.select_node(state, "laptop")
            model.apply_catalog(state, "laptop", catalog())
            model.select_workspace(state, "ws2")
            model.toggle_technical(state)
            local saved = model.checkpoint(state)
            local restored = model.new({})
            test.is_true(model.restore(restored, saved))
            test.is_nil(restored.selected_node)
            test.is_true(restored.technical)
            model.apply_members(restored, members({"forge", "laptop"}, "forge"))
            test.eq(restored.selected_node, "laptop")
            test.is_nil(restored.selected_workspace)
            model.apply_catalog(restored, "laptop", catalog())
            test.eq(restored.selected_workspace, "ws2")
            test.is_nil(restored.wanted_workspace)
            test.is_false(model.restore(model.new({}), "5"))
            test.is_false(model.restore(model.new({}), '{"selected_node": 5}'))
            test.is_false(model.restore(model.new({}), '{"selected_workspace": "' .. string.rep("x", 401) .. '"}'))
            test.is_false(model.restore(model.new({}), '{"technical": "yes"}'))
            local partial = model.new({})
            test.is_true(model.restore(partial, "{}"))
            model.apply_members(partial, members({"forge"}, "forge"))
            test.eq(partial.selected_node, "forge")
        end)
        test.it("pages a node's workspaces by cursor and searches from the first page", function()
            local state = model.new({})
            model.apply_members(state, {{node_id = "forge", is_local = false, addr = "", client_only = false}}, nil, 0)
            model.select_node(state, "forge")
            model.apply_catalog(state, "forge", {available = true, reason = "", owner_generation = "forge", next_after = "cursor-2", workspaces = {
                {workspace_id = "ws1", label = "one", served = false}}})
            test.is_nil(model.query(state, "forge").after)
            test.is_false(model.page(state, -1), "paged back from the first page")
            test.is_true(model.page(state, 1))
            test.eq(model.query(state, "forge").after, "cursor-2")
            test.eq(model.page_number(state, "forge"), 2)
            model.apply_catalog(state, "forge", {available = true, reason = "", owner_generation = "forge", next_after = nil, workspaces = {}})
            test.is_false(model.page(state, 1), "paged past the last page")
            test.is_true(model.page(state, -1))
            test.is_nil(model.query(state, "forge").after)
            model.edit(state, true)
            model.type_text(state, "rex")
            model.type_text(state, "\27[2J")
            model.erase(state)
            model.type_text(state, "tained")
            test.is_true(model.submit(state))
            test.is_false(state.editing)
            local query = model.query(state, "forge")
            test.eq(query.label, "retained")
            test.is_nil(query.after)
            test.eq(model.page_number(state, "forge"), 1)
        end)
    end)
end
return require("test").run_cases(define_tests)
