-- MIT. The display's workspace menu shows one answered page at a time, pages
-- and searches through its owner, marks the workspace shown and asks to switch
-- only to another one.
local test = require("test")
local tty = require("tty")
local appearance = require("appearance")
local workspace_menu = require("workspace_menu")
local CURRENT = string.rep("a", 32)
local OTHER = string.rep("b", 32)
local function key(key_type: string, text: string?): {[string]: unknown}
    return {type = "key", key_type = key_type, key = text or "", action = "press"}
end
local function define_tests()
    test.describe("Display workspace menu", function()
        test.it("applies only the answer to its pending page and switches to another workspace", function()
            local menu = workspace_menu.new(CURRENT)
            local first = workspace_menu.request(menu, "page-1")
            test.is_nil(first.label)
            test.is_false(workspace_menu.apply(menu, {version = 1, request_id = "stale", items = {}}))
            test.is_true(workspace_menu.apply(menu, {version = 1, request_id = "page-1",
                items = {{workspace_id = CURRENT, label = ""}, {workspace_id = OTHER, label = "Other"}}, next_after = "cursor-1"}))
            test.eq(#menu.items, 2)
            test.eq(workspace_menu.label(menu.items[1]) ~= "", true)
            local same = workspace_menu.respond(menu, key("enter"), "switch-0")
            test.is_nil(same.switch)
            test.eq(menu.status, "This display shows that workspace")
            workspace_menu.respond(menu, key("down"), "unused")
            local chosen = workspace_menu.respond(menu, key("enter"), "switch-1")
            test.eq(chosen.switch, OTHER)
            test.eq(menu.switching, "switch-1")
            test.is_false(workspace_menu.switched(menu, {version = 1, request_id = "other", error_code = "", error = ""}))
            test.is_true(workspace_menu.switched(menu, {version = 1, request_id = "switch-1", error_code = "BUSY", error = "pending"}))
            test.eq(menu.status, "Switch refused: pending")
            test.is_nil(menu.switching)
        end)
        test.it("pages forward and back and searches from the first page", function()
            local menu = workspace_menu.new(CURRENT)
            workspace_menu.request(menu, "page-1")
            workspace_menu.apply(menu, {version = 1, request_id = "page-1", items = {{workspace_id = OTHER, label = "Other"}}, next_after = "cursor-1"})
            local forward = workspace_menu.respond(menu, key("pgdown"), "page-2")
            test.eq(forward.page and forward.page.after, "cursor-1")
            workspace_menu.apply(menu, {version = 1, request_id = "page-2", items = {}})
            test.eq(menu.status, "No workspaces match")
            local back = workspace_menu.respond(menu, key("pgup"), "page-3")
            test.is_nil(back.page and back.page.after)
            test.not_nil(back.page)
            workspace_menu.apply(menu, {version = 1, request_id = "page-3", items = {}})
            workspace_menu.respond(menu, key("", "/"), "unused")
            test.is_true(menu.editing)
            workspace_menu.respond(menu, key("", "O"), "unused")
            workspace_menu.respond(menu, key("", "t"), "unused")
            local search = workspace_menu.respond(menu, key("enter"), "page-4")
            test.eq(search.page and search.page.label, "Ot")
            test.is_nil(search.page and search.page.after)
            test.is_true(workspace_menu.respond(menu, key("esc"), "unused").close)
        end)
        test.it("draws the page with the shown workspace marked", function()
            local menu = workspace_menu.new(CURRENT)
            workspace_menu.request(menu, "page-1")
            workspace_menu.apply(menu, {version = 1, request_id = "page-1",
                items = {{workspace_id = CURRENT, label = "Here"}, {workspace_id = OTHER, label = "Other"}}})
            local canvas = tty.canvas(80, 24)
            workspace_menu.draw(canvas, 80, 24, appearance.defaults(), menu)
            local text = table.concat(canvas:rows(), "\n"):gsub("\27%[[%d;]*m", "")
            test.is_true(text:find("WORKSPACES", 1, true) ~= nil)
            test.is_true(text:find("● Here", 1, true) ~= nil)
            test.is_true(text:find("Other", 1, true) ~= nil)
        end)
    end)
end
local cases = test.run_cases(define_tests)
return {run = function(options: unknown) return cases(options) end}
