-- SPDX-License-Identifier: MIT
local test = require("test")
local fixture = require("fixture")
local principals = require("principals")
local gateway_hooks = require("gateway_hooks")
local hook_records = require("hook_records")
local function define_tests()
    test.describe("OpenCode observer events", function()
        test.it("maps root lifecycle, tools, permissions and idle to admitted hooks", function()
            local capture = fixture.capture({prompt = "Peer request", answer = "Peer reply", tools = true, context = "Boundary context"})
            test.is_nil(capture.error)
            local rows = principals.objects(capture.rows)
            local names: {string} = {}
            local stored: {{[string]: unknown}} = {}
            for index, row in ipairs(rows) do
                names[index] = tostring(row.hook_event_name)
                local submission = assert(gateway_hooks.normalize(names[index], row))
                stored[index] = {event_id = "event-" .. tostring(index), event = submission.event, occurrence = submission.occurrence,
                    ambiguous = submission.ambiguous, provenance = "http", sequence = index, fields = submission.fields}
            end
            test.eq(table.concat(names, ","), "SessionStart,UserPromptSubmit,PreToolUse,PostToolUse,PostToolUseFailure,PermissionRequest,PermissionRequest,Stop,SessionEnd")
            test.eq(rows[2].prompt_id, "msg_prompt")
            test.eq(rows[3].tool_use_id, "call_1")
            test.eq(rows[6].tool_use_id, "call_3")
            test.eq(rows[7].tool_use_id, "call_4")
            test.eq(rows[8].last_assistant_message, "Peer reply")
            local batch = assert(hook_records.batch("binding-1", nil, stored))
            test.eq(#batch.records, #rows + 1)
            test.eq(batch.records[9].body.data.phase, "ended")
            test.eq(batch.activity, "Session ended")
        end)
        test.it("ends the root session when OpenCode disposes its server", function()
            local capture = fixture.capture({prompt = "Close", answer = "Done", dispose = true})
            test.is_nil(capture.error)
            local rows = principals.objects(capture.rows)
            test.eq(#rows, 4)
            test.eq(rows[4].hook_event_name, "SessionEnd")
            test.eq(rows[4].reason, "prompt_input_exit")
        end)
        test.it("records a failed turn without a successful reply", function()
            for _, flags in ipairs({{failed = true}, {errorEvent = true}}) do
                local capture = fixture.capture({prompt = "Fail", answer = "Wrong success", failed = flags.failed, errorEvent = flags.errorEvent})
                test.is_nil(capture.error)
                local rows = principals.objects(capture.rows)
                test.eq(rows[3].hook_event_name, "StopFailure")
                test.is_nil(rows[3].last_assistant_message)
                test.eq(#rows, 4)
            end
        end)
        test.it("refuses idle without a completed reply", function()
            local capture = fixture.capture({prompt = "Still running", answer = "Partial", incomplete = true})
            test.is_nil(capture.error)
            local logs = principals.objects(capture.logs)
            test.eq(#logs, 2)
            test.eq(logs[1].message, "Bee OpenCode callback: OpenCode idle omitted a completed reply")
            local rows = principals.objects(capture.rows)
            test.eq(#rows, 3)
            test.eq(rows[3].hook_event_name, "SessionEnd")
        end)
        test.it("records delivery failures without rejecting provider callbacks or poisoning later hooks", function()
            for _, failure in ipairs({"refused", "network"}) do
                local capture = fixture.capture({prompt = "Peer request", answer = "Peer reply", deliveryFailure = failure})
                test.is_nil(capture.error)
                local logs = principals.objects(capture.logs)
                test.eq(#logs, 1)
                test.eq(logs[1].level, "error")
                test.eq(logs[1].service, "bee-hooks")
                local rows = principals.objects(capture.rows)
                test.eq(#rows, 3)
                test.eq(rows[2].hook_event_name, "Stop")
                test.eq(rows[2].last_assistant_message, "Peer reply")
            end
        end)
    end)
end
return test.run_cases(define_tests)
