-- MIT. OpenCode launch tests: window TUI argv, headless run argv, resume,
-- quoting through the shared quoter, and prepare/dispatch validation. Flag
-- shapes verified against opencode 1.18.32 (`opencode --help`,
-- `opencode run --help`).
local test = require("test")
local launch = require("launch")
local prepare = require("prepare")
local dispatch = require("dispatch")
local quote = require("quote")
local function define_tests()
    test.describe("OpenCode launch", function()
        test.it("builds the headless run argv with the brief after a dash separator", function()
            local decoded, err = launch.decode({profile_id = "batch", brief = "research this"})
            if not decoded then error(tostring(err)) end
            local spec = launch.specification(decoded)
            test.eq(spec.executable, "opencode")
            test.eq(quote.line(spec.argv), "run --format json -- 'research this'")
            test.eq(spec.readiness, "protocol:thread.started")
            test.is_nil(spec.stdin)
            test.is_nil(spec.login)
        end)
        test.it("resumes a batch turn through --session", function()
            local decoded = assert(launch.decode({profile_id = "batch", brief = "continue", resume_ref = "ses_abc123"}))
            test.eq(quote.line(launch.specification(decoded).argv), "run --format json --session ses_abc123 -- continue")
        end)
        test.it("starts the window with no argv and prompts through --prompt", function()
            local empty = launch.specification(assert(launch.decode({profile_id = "window", brief = ""})))
            test.eq(#empty.argv, 0)
            test.eq(empty.readiness, "terminal:attached")
            local login = empty.login
            if not login then error("missing login declaration") end
            test.eq(login.provider, "opencode")
            test.eq(login.command, "opencode auth login")
            test.eq(#login.files, 1)
            test.eq(login.files[1].variable, "HOME")
            test.eq(login.files[1].path, ".local/share/opencode/auth.json")
            local prompted = launch.specification(assert(launch.decode({profile_id = "window", brief = "hello", resume_ref = "ses_abc123"})))
            test.eq(quote.line(prompted.argv), "--session ses_abc123 --prompt hello")
        end)
        test.it("refuses hook events, unknown profiles and option-like resume refs", function()
            local _, hooks_error = launch.decode({profile_id = "window", brief = "", gateway_hooks = {"Stop"}})
            test.eq(hooks_error, "opencode declares no hook transport for gateway hooks")
            local _, profile_error = launch.decode({profile_id = "session", brief = "hi"})
            test.eq(profile_error, "profile_id is not one Bee admits")
            local _, brief_error = launch.decode({profile_id = "batch", brief = ""})
            test.eq(brief_error, "brief must be nonempty bounded text")
            local _, resume_error = launch.decode({profile_id = "batch", brief = "hi", resume_ref = "--session"})
            test.eq(resume_error, "resume_ref must not be a command-line option")
            local _, tools_error = launch.decode({profile_id = "batch", brief = "hi", gateway_tools = {"bad-tool!"}})
            test.eq(tools_error, "gateway_tools names a tool that is not a plain identifier")
            local _, unknown_error = launch.decode({profile_id = "batch", brief = "hi", model = "x/y"})
            test.eq(unknown_error, "unknown field model")
            test.is_nil(launch.decode(nil))
        end)
        test.it("handles prepare and dispatch methods", function()
            local prep_ok = prepare.handle({profile_id = "batch", brief = "prepare test"})
            test.is_true(prep_ok.ok)
            test.not_nil(prep_ok.launch)
            local prep_bad = prepare.handle({profile_id = "other", brief = "prepare test"})
            test.is_false(prep_bad.ok)
            test.not_nil(prep_bad.error)
            local disp_missing = dispatch.handle({profile_id = "batch", brief = "dispatch test"})
            test.is_false(disp_missing.ok)
            test.eq(disp_missing.error, "a dispatched turn needs resume_ref")
            local disp_ok = dispatch.handle({profile_id = "batch", brief = "dispatch test", resume_ref = "ses_42"})
            test.is_true(disp_ok.ok)
            test.not_nil(disp_ok.launch)
            test.is_true(table.concat(disp_ok.launch.argv, " "):find("--session ses_42", 1, true) ~= nil)
        end)
    end)
end
return test.run_cases(define_tests)
