-- MIT. The inbox model, pure: hostile text is bounded and stripped, pages
-- fold in by revision, a decision is asked only of an opened pending
-- request at the viewed revision, a conflict shows what the owner
-- committed, an unknown answer is recovered by reading, and the
-- checkpoint carries selection only.
local test = require("test")
local bounds = require("bounds")
local json = require("json")
local model = require("model")
local inbox = require("inbox")
local caller = require("caller")
type Object = {[string]: unknown}
local function view(id: string, revision: integer, state: string, extra: Object?): Object
    local item: Object = {approval_id = id, workspace_id = "ws-1", requester_id = "bee.test.requester", request_kind = "permission", policy = "inbox-test",
        proposal = {kind = "attempt", ref = "attempt-" .. id, revision = "r1", action_id = "action-" .. id, payload = {tool_name = "Bash", correlation_id = "c-1", adapter_ref = "bee.driver.claude.permission:permission_adapter"}},
        proposal_digest = string.rep("a", 64), prompt = {text = "touch proof.txt"}, revision = revision, state = state, owner_node = "node-1", owner_incarnation = 3,
        expires_at = "2026-09-09T10:00:00.000Z", created_at = "2026-09-09T09:0" .. tostring(#id % 10) .. ":00.000Z"}
    for key, value in pairs(extra or {}) do item[key] = value end
    return item
end
local function reply(raw: Object): model.Reply
    local decoded = model.decode_reply(raw)
    if not decoded then error("invalid approval reply fixture") end
    return decoded
end
local function page(changes: {Object}, next_seq: integer, more: boolean): model.Reply
    return reply({ok = true, error = nil, value = {changes = changes, next_seq = next_seq, more = more}, replayed = false})
end
local function define_tests()
    test.describe("Inbox model", function()
        test.it("combines a requester's pending permissions and caps the whole duration choice", function()
            local state = model.new({"ws-1"})
            local one = view("window-one", 1, "pending", {window_max_ttl_ms = 14400000, reallow = true})
            local two = view("window-two", 1, "pending", {window_max_ttl_ms = 1800000})
            assert(bounds.object(one.proposal)).action_id = "one-person-action"
            assert(bounds.object(two.proposal)).action_id = "one-person-action"
            model.apply_inbox(state, "ws-1", page({{seq = 1, request = one}, {seq = 2, request = two}}, 2, false))
            model.select(state, "window-one")
            model.apply_read(state, "window-one", reply({ok = true, value = one}))
            test.eq(#model.decision_group(state), 2)
            test.eq(model.window_cap(state), 1800000)
            local intent = assert(model.combined_intent(state, "choose-window", "approved", 1800000))
            test.eq(intent.target, "bee.approvals.binding:decide_batch")
            test.eq(intent.request.window_ttl_ms, 1800000)
            test.eq(#assert(bounds.array(intent.request.decisions, 16)), 2)
            local answer = {decisions = {view("window-one", 2, "decided", {decision = "approved"}), view("window-two", 2, "decided", {decision = "approved"})}}
            model.apply_answer(state, "choose-window", reply({ok = true, value = answer}))
            test.is_nil(state.pending)
            test.eq(state.rows["window-two"].decision, "approved")
        end)

        test.it("decodes inbox-specific reset and conflict data without widening generic caller replies", function()
            local reset_raw: Object = {ok = false, error = {code = "RESET_REQUIRED", message = "compacted", retryable = true}, value = {oldest_seq = 7}, replayed = false}
            local reset = model.decode_reply(reset_raw)
            test.not_nil(reset)
            if not reset then error("reset reply was rejected") end
            test.eq(reset.kind, "reset")
            if reset.kind == "reset" then
                test.eq(reset.oldest_seq, 7)
                test.is_true(reset.retryable == true)
            end

            local conflict_raw: Object = {ok = false, error = {code = "CONFLICT", message = "already decided", retryable = false},
                value = view("r1", 2, "decided", {decision = "approved", decider_id = "bee.test.alice"}), replayed = false}
            local conflict = model.decode_reply(conflict_raw)
            test.not_nil(conflict)
            if not conflict then error("conflict reply was rejected") end
            test.eq(conflict.kind, "conflict")
            if conflict.kind == "conflict" then
                test.eq(conflict.request.approval_id, "r1")
                test.is_true(conflict.retryable == false)
            end
            test.is_nil(caller.decode(conflict_raw))

            local settled = model.decode_reply({ok = false, error = {code = "INVALID_STATE", message = "request expired"},
                value = view("r1", 3, "expired"), replayed = false})
            test.not_nil(settled)
            if settled and settled.kind == "settled" then
                test.eq(settled.request.state, "expired")
            else
                error("settled reply was not decoded")
            end

            test.is_nil(model.decode_reply({ok = false, error = {code = "DENIED", message = "no"}, value = {oldest_seq = 7}}))
            test.is_nil(model.decode_reply({ok = false, error = {code = "DENIED", message = "no", retryable = "yes"}, value = nil}))
            test.is_nil(model.decode_reply({ok = false, error = {code = "RESET_REQUIRED", message = "compacted"}, value = {oldest_seq = 1, cursor = 4}}))
            test.is_nil(model.decode_reply({ok = true, error = nil, value = view("r1", 1, "pending"), unknown = true}))
        end)
        test.it("preserves a decision's uncertain outcome and exact transport cause", function()
            local state = model.new({"ws-1"})
            local item = view("unknown-window", 1, "pending")
            model.apply_inbox(state, "ws-1", page({{seq = 1, request = item}}, 1, false))
            model.select(state, "unknown-window")
            model.apply_read(state, "unknown-window", reply({ok = true, value = item}))
            assert(model.decision_intent(state, "unknown-call", "approved"))
            model.apply_answer(state, "unknown-call", {kind = "failure", code = "UNKNOWN_OUTCOME", message = "peer disconnected before acknowledgement"})
            test.not_nil(state.pending)
            test.eq(state.notice, "UNKNOWN_OUTCOME: peer disconnected before acknowledgement")
        end)
        test.it("bounds text and replaces every control character, cutting on a character boundary", function()
            local hostile = "run \27[31mred\27[0m\r\nnow\7 " .. string.rep("é", 400)
            local cleaned = model.text(hostile, 64)
            test.is_nil((cleaned:find("\27", 1, true)))
            test.is_nil((cleaned:find("[%c]")))
            test.is_true(#cleaned <= 64 + 3)
            test.eq(cleaned:sub(-3), "…")
            test.is_true(cleaned:sub(1, 4) == "run ")
            test.eq(model.text(nil), "")
            test.eq(model.text("plain"), "plain")
        end)
        test.it("folds pages in by revision, restarts a compacted cursor and marks a refused workspace unavailable", function()
            local state = model.new({"ws-1"})
            test.eq(model.inbox_intent(state, "ws-1").request.after_seq, 0)
            local more = model.apply_inbox(state, "ws-1", page({{seq = 1, approval_id = "r1", revision = 1, request = view("r1", 1, "pending")}, {seq = 2, approval_id = "r2", revision = 1, request = view("r2", 1, "pending")}}, 2, true))
            test.is_true(more)
            test.eq(model.inbox_intent(state, "ws-1").request.after_seq, 2)
            model.apply_inbox(state, "ws-1", page({{seq = 3, approval_id = "r1", revision = 2, request = view("r1", 2, "decided", {decision = "approved", decider_id = "bee.test.alice"})}}, 3, false))
            test.eq(state.rows["r1"].revision, 2)
            test.eq(state.rows["r1"].state, "decided")
            model.apply_inbox(state, "ws-1", page({{seq = 1, approval_id = "r1", revision = 1, request = view("r1", 1, "pending")}}, 3, false))
            test.eq(state.rows["r1"].revision, 2)
            local rows = model.rows(state)
            test.eq(rows[1].approval_id, "r2")
            test.eq(rows[1].effect, "Bash")
            test.eq(rows[1].target, "attempt-r2 action action-r2")
            test.is_true(model.apply_inbox(state, "ws-1", reply({ok = false, error = {code = "RESET_REQUIRED", message = "compacted"}, value = {oldest_seq = 7}, replayed = false})))
            test.eq(model.inbox_intent(state, "ws-1").request.after_seq, 6)
            test.is_false(model.apply_inbox(state, "ws-1", reply({ok = false, error = {code = "DENIED", message = "caller may not read the inbox"}, value = nil, replayed = false})))
            test.is_true(tostring(state.unavailable["ws-1"]):find("DENIED", 1, true) ~= nil)
        end)
        test.it("asks a decision only of an opened pending request at the viewed revision, one at a time", function()
            local state = model.new({"ws-1"})
            model.apply_inbox(state, "ws-1", page({{seq = 1, approval_id = "r1", revision = 1, request = view("r1", 1, "pending")}}, 1, false))
            local _, unopened = model.decision_intent(state, "q1", "approved")
            test.eq(unopened, "open the request before deciding")
            model.select(state, "r1")
            model.apply_read(state, "r1", reply({ok = true, error = nil, value = view("r1", 1, "pending"), replayed = false}))
            test.not_nil(state.detail)
            local _, bad = model.decision_intent(state, "q1", "maybe")
            test.eq(bad, "decision must be approved or denied")
            local intent = model.decision_intent(state, "q1", "approved")
            if not intent then error("no intent") end
            test.eq(intent.target, "bee.approvals.binding:decide")
            test.eq(intent.request.expected_revision, 1)
            test.eq(intent.request.proposal_digest, string.rep("a", 64))
            local _, busy = model.decision_intent(state, "q2", "denied")
            test.eq(busy, "a request is already awaiting the owner")
            model.apply_answer(state, "q1", reply({ok = true, error = nil, value = view("r1", 2, "decided", {decision = "approved", decider_id = "bee.test.alice"}), replayed = false}))
            test.is_nil(state.pending)
            test.eq(state.rows["r1"].state, "decided")
            test.eq(state.notice, "Recorded: approved by bee.test.alice")
            local _, settled = model.decision_intent(state, "q3", "denied")
            test.eq(settled, "the request is decided")
        end)
        test.it("shows the committed outcome on a conflict and never resubmits", function()
            local state = model.new({"ws-1"})
            model.apply_inbox(state, "ws-1", page({{seq = 1, approval_id = "r1", revision = 1, request = view("r1", 1, "pending")}}, 1, false))
            model.select(state, "r1")
            model.apply_read(state, "r1", reply({ok = true, error = nil, value = view("r1", 1, "pending"), replayed = false}))
            local intent = model.decision_intent(state, "q1", "denied")
            test.not_nil(intent)
            model.apply_answer(state, "q1", reply({ok = false, error = {code = "CONFLICT", message = "request was decided approved by bee.test.bob"}, value = view("r1", 2, "decided", {decision = "approved", decider_id = "bee.test.bob"}), replayed = false}))
            test.is_nil(state.pending)
            test.eq(state.notice, "CONFLICT: approved by bee.test.bob at revision 2")
            test.eq((assert(bounds.object(state.detail))).decision, "approved")
            test.eq(state.rows["r1"].decider_id, "bee.test.bob")
            local _, refused = model.decision_intent(state, "q2", "denied")
            test.eq(refused, "the request is decided")
        end)
        test.it("recovers an unknown answer from the owner's record and ignores answers to other requests", function()
            local state = model.new({"ws-1"})
            model.apply_inbox(state, "ws-1", page({{seq = 1, approval_id = "r1", revision = 1, request = view("r1", 1, "pending")}}, 1, false))
            model.select(state, "r1")
            model.apply_read(state, "r1", reply({ok = true, error = nil, value = view("r1", 1, "pending"), replayed = false}))
            test.not_nil(model.decision_intent(state, "q1", "approved"))
            model.apply_answer(state, "other", reply({ok = true, error = nil, value = view("r1", 2, "decided"), replayed = false}))
            test.not_nil(state.pending)
            model.apply_answer(state, "q1", nil)
            test.not_nil(state.pending)
            local recovery = model.recovery_intent(state)
            if not recovery then error("no recovery intent") end
            test.eq(recovery.target, "bee.approvals.binding:read")
            model.apply_recovery(state, reply({ok = true, error = nil, value = view("r1", 2, "decided", {decision = "approved", decider_id = "bee.test.alice"}), replayed = false}))
            test.is_nil(state.pending)
            test.eq(state.notice, "Recovered: approved by bee.test.alice")
            test.not_nil(model.decision_intent(state, "q4", "approved") == nil)
        end)
        test.it("pins confirmation to the exact viewed owner revision and digest", function()
            local state = model.new({"ws-1"})
            model.select(state, "r1")
            model.apply_read(state, "r1", reply({ok = true, value = view("r1", 1, "pending")}))
            local asked = model.confirmation(state)
            if not asked then error("missing confirmation") end
            test.is_true(model.confirmation_matches(state, asked))
            model.apply_read(state, "r1", reply({ok = true, value = view("r1", 2, "pending")}))
            test.is_false(model.confirmation_matches(state, asked))
            model.apply_read(state, "r1", reply({ok = true, value = view("r1", 2, "pending", {proposal_digest = string.rep("b", 64)})}))
            test.is_false(model.confirmation_matches(state, asked))
            model.select(state, "r2")
            test.is_false(model.confirmation_matches(state, asked))
        end)
        test.it("keeps an unknown decision pending when recovery is unavailable", function()
            local state = model.new({"ws-1"})
            model.select(state, "r1")
            model.apply_read(state, "r1", reply({ok = true, value = view("r1", 1, "pending")}))
            test.not_nil(model.decision_intent(state, "q1", "approved"))
            model.apply_answer(state, "q1", nil)
            model.apply_recovery(state, reply({ok = false, error = {code = "UNAVAILABLE", message = "offline"}, value = nil}))
            test.not_nil(state.pending)
            test.is_nil(model.decision_intent(state, "q2", "denied"))
            model.apply_recovery(state, reply({ok = true, value = view("r1", 1, "pending")}))
            test.not_nil(state.pending)
            test.is_nil(model.decision_intent(state, "q3", "denied"))
            model.apply_recovery(state, reply({ok = true, value = view("r1", 2, "decided", {decision = "approved"})}))
            test.is_nil(state.pending)
        end)
        test.it("renders a proposal payload only as bounded sorted lines and keeps the checkpoint to selection", function()
            local lines = model.payload_lines(view("r1", 1, "pending", {proposal = {kind = "attempt", ref = "a", revision = "r1", payload = {zeta = "\27[2Jz", alpha = {nested = true}, mid = 7}}}))
            test.eq(#lines, 3)
            test.eq(lines[1], 'alpha: {"nested":true}')
            test.eq(lines[2], "mid: 7")
            test.is_nil((lines[3]:find("\27", 1, true)))
            local state = model.new({"ws-1"})
            model.select(state, "r1")
            model.toggle_technical(state)
            local saved = model.checkpoint(state)
            local restored = model.new({"ws-1"})
            test.is_true(model.restore(restored, saved))
            test.eq(restored.selected, "r1")
            test.is_true(restored.technical)
            test.is_false(model.restore(model.new({}), json.encode({selected = 7}) or ""))
            test.is_false(model.restore(model.new({}), "nonsense"))
        end)
        test.it("treats a transport failure as an unknown answer and admits only bounded workspace ids", function()
            local owner = caller.new(function(target: string, request: unknown): (unknown, string?) return nil, "no handler" end)
            test.is_nil(owner:invoke("bee.approvals.binding:read", {approval_id = "r1"}))
            local answered = caller.new(function(target: string, request: unknown): (unknown, string?) return {ok = false, error = {code = "DENIED", message = "no"}, value = nil}, nil end)
            local reply = answered:invoke("bee.approvals.binding:read", {})
            test.eq(reply and reply.error and reply.error.code, "DENIED")
            local list = inbox.workspaces("ws-launch", {"ws-2", "ws-launch", "bad\nid", 7, "ws-3"})
            test.eq(table.concat(list, ","), "ws-launch,ws-2,ws-3")
        end)
    end)
end
return test.run_cases(define_tests)
