-- MIT. Comparison uses effective operation and scope, including template meaning.
local test = require("test")
local principals = require("principals")
local bounds = require("bounds")
local containment = require("capability_containment")
type Object = {[string]: unknown}
local function grant(capability: string, operation: string, resource: string, scope: Object, revision: integer): Object
    return {capability = capability, template_revision = revision, operation = operation,
        resource = resource, scope = scope, parameters = scope}
end
local function compare(old: {Object}, new: {Object}): Object
    return assert(bounds.object(assert(containment.compare(old, new))))
end
local function define_tests()
    test.describe("Capability containment", function()
        test.it("classifies added, removed and prefix path narrowing without sibling leakage", function()
            local old = grant("workspace.files.read", "files.read", "workspace-1", {subpath = "docs"}, 1)
            local child = grant("workspace.files.read", "files.read", "workspace-1", {subpath = "docs/api"}, 1)
            local sibling = grant("workspace.files.read", "files.read", "workspace-1", {subpath = "docs2"}, 1)
            test.eq(#(principals.items(compare({old}, {child}).narrowed)), 1)
            test.eq(#(principals.items(compare({child}, {old}).widened)), 1)
            test.eq(#(principals.items(compare({old}, {sibling}).added)), 1)
            test.eq(#(principals.items(compare({old}, {sibling}).removed)), 1)
            test.eq(#(principals.items(compare({}, {old}).added)), 1)
            test.eq(#(principals.items(compare({old}, {}).removed)), 1)
        end)
        test.it("compares method and definition sets at exact identities", function()
            local old = grant("contract.call", "contract.call", "app:binding", {methods = {"get"}}, 1)
            local wide = grant("contract.call", "contract.call", "app:binding", {methods = {"get", "put"}}, 1)
            test.eq(#(principals.items(compare({old}, {wide}).widened)), 1)
            test.eq(#(principals.items(compare({wide}, {old}).narrowed)), 1)
            local other = grant("contract.call", "contract.call", "other:binding", {methods = {"get"}}, 1)
            test.eq(#(principals.items(compare({old}, {other}).added)), 1)
            local agents = grant("agents.launch", "agents.launch", "workspace-1", {definitions = {"a:one"}}, 1)
            local more = grant("agents.launch", "agents.launch", "workspace-1", {definitions = {"a:one", "a:two"}}, 1)
            test.eq(#(principals.items(compare({agents}, {more}).widened)), 1)
        end)
        test.it("compares the union of effective grants without treating redundant requests as widening", function()
            local broad = grant("workspace.files.read", "files.read", "workspace-1", {subpath = "docs"}, 1)
            local child = grant("workspace.files.read", "files.read", "workspace-1", {subpath = "docs/api"}, 1)
            local paths = compare({broad}, {broad, child})
            test.eq(#(principals.items(paths.added)), 0)
            test.eq(#(principals.items(paths.narrowed)), 0)
            test.is_false(paths.requires_approval)
            local both = grant("contract.call", "contract.call", "app:binding", {methods = {"get", "put"}}, 1)
            local get = grant("contract.call", "contract.call", "app:binding", {methods = {"get"}}, 1)
            local put = grant("contract.call", "contract.call", "app:binding", {methods = {"put"}}, 1)
            local split = compare({both}, {get, put})
            test.eq(#(principals.items(split.added)), 0)
            test.eq(#(principals.items(split.removed)), 0)
            test.eq(#(principals.items(split.narrowed)), 0)
        end)
        test.it("treats origin changes and template revisions as changed meaning", function()
            local old = grant("http.api", "http.request", "https://one.example", {methods = {"GET"}, path_prefix = "/v1"}, 1)
            local new = grant("http.api", "http.request", "https://two.example", {methods = {"GET"}, path_prefix = "/v1"}, 1)
            test.eq(#(principals.items(compare({old}, {new}).added)), 1)
            test.eq(#(principals.items(compare({old}, {new}).removed)), 1)
            new.resource = old.resource
            new.template_revision = 2
            local replaced = compare({old}, {new})
            test.eq(#(principals.items(replaced.changed)), 1)
            test.eq(#(principals.items(replaced.removed)), 1)
            local revocation = assert(bounds.object(replaced.revocation))
            local revoked = principals.objects(revocation.grants)
            test.eq(#revoked, 1)
            test.eq(revoked[1].template_revision, 1)
            test.is_true(replaced.requires_approval)
        end)
        test.it("contains HTTP methods and path prefixes only within one origin", function()
            local old = grant("http.api", "http.request", "https://api.example.com",
                {methods = {"GET", "POST"}, path_prefix = "/v1"}, 1)
            local narrow = grant("http.api", "http.request", "https://api.example.com",
                {methods = {"GET"}, path_prefix = "/v1/users"}, 1)
            test.eq(#(principals.items(compare({old}, {narrow}).narrowed)), 1)
            test.eq(#(principals.items(compare({narrow}, {old}).widened)), 1)
            local sibling = grant("http.api", "http.request", "https://api.example.com",
                {methods = {"GET"}, path_prefix = "/v11"}, 1)
            test.eq(#(principals.items(compare({old}, {sibling}).added)), 1)
            local other_workspace = grant("workspace.files.read", "files.read", "workspace-2",
                {subpath = "docs"}, 1)
            local first_workspace = grant("workspace.files.read", "files.read", "workspace-1",
                {subpath = "docs"}, 1)
            test.eq(#(principals.items(compare({first_workspace}, {other_workspace}).added)), 1)
        end)
        test.it("rejects malformed sets before comparing", function()
            local bad = grant("http.api", "http.request", "https://one.example", {methods = {"GET", "GET"}}, 1)
            test.is_nil(containment.compare({bad}, {}))
            bad.scope = {path_prefix = "/api/../private", methods = {"GET"}}
            test.is_nil(containment.compare({bad}, {}))
        end)
        test.it("uses the same containment and revocation values for MCP and resource grants", function()
            local mcp = assert(containment.traits("binding-one", {"research:read", "research:write"}))
            local mcp_narrow = assert(containment.traits("binding-one", {"research:read"}))
            local mcp_other = assert(containment.traits("binding-two", {"research:read"}))
            test.is_true(containment.contains(mcp, mcp_narrow))
            test.is_false(containment.contains(mcp_narrow, mcp))
            test.is_false(containment.contains(mcp, mcp_other))
            local resource = assert(containment.resource("workspace-one", "project", "docs", "write"))
            local resource_narrow = assert(containment.resource("workspace-one", "project", "docs/api", "read"))
            test.is_true(containment.contains(resource, resource_narrow))
            test.is_false(containment.contains(resource_narrow, resource))
            local report = assert(containment.revocation_report({mcp, resource}, {"attempt-z", "attempt-a", "attempt-z"}))
            local grants = principals.objects(report.grants)
            local attempts = principals.strings(report.fenced_attempts)
            test.eq(#grants, 2)
            test.eq(#attempts, 2)
            test.eq(attempts[1], "attempt-a")
            test.eq(attempts[2], "attempt-z")
        end)
    end)
end
return test.run_cases(define_tests)
