-- MIT. Authoring request schemas never accept authority or execution flags.
local test = require("test")
local protocol = require("protocol")
local function define_tests()
    test.describe("Governance authoring protocol", function()
        test.it("decodes text and canonical binary writes", function()
            local text = protocol.decode({operation = "put", workspace_id = "demo", expected_revision = 1, idempotency_key = "write", path = "child/service.lua", content = "return true"})
            test.not_nil(text)
            if text then test.eq(text.content, "return true") end
            local binary = protocol.decode({operation = "put", workspace_id = "demo", expected_revision = 1, idempotency_key = "binary", path = "a.wasm", content_base64 = "AP8="})
            test.not_nil(binary)
            if binary then test.eq(binary.content, "\0\255") end
        end)
        test.it("requires an exact offset and optionally checks the assembled digest", function()
            local digest = string.rep("a", 64)
            local request = protocol.decode_overlay({operation = "append", overlay_id = "demo", expected_revision = 2,
                idempotency_key = "append-1", path = "entries.json", offset = 65536, content = "more", result_digest = digest})
            test.not_nil(request)
            test.eq(request and request.offset, 65536)
            test.eq(request and request.result_digest, digest)
            test.not_nil(protocol.decode_overlay({operation = "append", overlay_id = "demo", expected_revision = 2,
                idempotency_key = "append-1", path = "entries.json", offset = 65536, content = "more"}))
            test.is_nil(protocol.decode_overlay({operation = "append", overlay_id = "demo", expected_revision = 2,
                idempotency_key = "append-1", path = "entries.json", offset = -1, content = "more", result_digest = digest}))
        end)
        test.it("bounds read windows for files larger than a carrier frame", function()
            local request = protocol.decode_overlay({operation = "read", overlay_id = "demo",
                path = "entries.json", offset = 16384, limit = 8192})
            test.eq(request and request.offset, 16384)
            test.eq(request and request.limit, 8192)
            test.is_nil(protocol.decode_overlay({operation = "read", overlay_id = "demo",
                path = "entries.json", limit = 16385}))
        end)
        test.it("translates the public overlay identity and keeps workspace private", function()
            local _, internal_operation = protocol.decode({operation = "publish", workspace_id = "demo"})
            test.eq(internal_operation, "unknown workspace operation")
            local request, request_error = protocol.decode_overlay({operation = "put", overlay_id = "demo", expected_revision = 1,
                idempotency_key = "write", path = "child/service.lua", content = "return true"})
            test.not_nil(request)
            test.is_nil(request_error)
            test.eq(request and request.workspace_id, "demo")
            test.is_nil(request and (request :: {[string]: unknown}).overlay_id)
            local _, old_field = protocol.decode_overlay({operation = "put", workspace_id = "demo", expected_revision = 1,
                idempotency_key = "write", path = "child/service.lua", content = "return true"})
            test.eq(old_field, "unknown field workspace_id")
            local _, unknown_operation = protocol.decode_overlay({operation = "publish", overlay_id = "demo"})
            test.eq(unknown_operation, "unknown overlay operation")
            local owned, owned_error = protocol.decode_overlay({operation = "list"})
            test.is_nil(owned_error)
            test.is_true(owned and owned.owned)
            local guide, guide_error = protocol.decode_overlay({operation = "guide"})
            test.not_nil(guide)
            test.is_nil(guide_error)
            test.eq(guide and guide.operation, "guide")
            test.eq(guide and guide.workspace_id, "")
            local _, guide_identity = protocol.decode_overlay({operation = "guide", overlay_id = "demo"})
            test.eq(guide_identity, "guide names no overlay_id")
        end)
        test.it("rejects authority fields and fields inappropriate to the operation", function()
            test.not_nil(protocol.decode({operation = "list", workspace_id = "demo", snapshot_digest = string.rep("a", 64)}))
            test.is_nil(protocol.decode({operation = "list", workspace_id = "demo", snapshot_digest = "latest"}))
            test.is_nil(protocol.decode({operation = "list", workspace_id = "demo", actor = "admin"}))
            test.is_nil(protocol.decode({operation = "list", workspace_id = "demo", expected_revision = 1}))
            test.is_nil(protocol.decode({operation = "freeze", workspace_id = "demo", expected_revision = 1, idempotency_key = "freeze", approved = true}))
            test.is_nil(protocol.decode({operation = "activate", workspace_id = "demo"}))
            test.is_nil(protocol.decode({operation = "create", workspace_id = "demo", expected_revision = 1, idempotency_key = "create"}))
        end)
        test.it("requires CAS and refuses ambiguous encodings and escaping paths", function()
            test.is_nil(protocol.decode({operation = "put", workspace_id = "demo", path = "entry", content = "x"}))
            for _, path in ipairs({"../x", "/x", "a//b", "a/", "C:entry", "a\\b"}) do
                test.is_nil(protocol.decode({operation = "read", workspace_id = "demo", path = path}))
            end
            test.is_nil(protocol.decode({operation = "put", workspace_id = "demo", expected_revision = 1, idempotency_key = "x", path = "entry", content = "x", content_base64 = "eA=="}))
            test.is_nil(protocol.decode({operation = "put", workspace_id = "demo", expected_revision = 1, idempotency_key = "x", path = "entry", content_base64 = "eA==\n"}))
        end)
    end)
end
return test.run_cases(define_tests)
