-- SPDX-License-Identifier: MIT
local test = require("test")
local state = require("demand_state")
local function define_tests()
    test.describe("Supervised demand", function()
        test.it("starts an absent owner and delivers only after readiness", function()
            local owner = state.new()
            test.eq(state.wake(owner), "start")
            test.eq(state.wake(owner), "wait")
            test.eq(state.ready(owner, "pid"), 2)
            test.eq(owner.phase, "ready")
        end)
        test.it("restarts an enqueue during quiet stop after the stop completes", function()
            local owner = state.new()
            state.wake(owner)
            state.ready(owner, "old")
            test.eq(state.quiet(owner, "old", 1), true)
            test.eq(state.wake(owner), "wait")
            test.eq(state.stopped(owner), "start")
            test.eq(state.ready(owner, "new"), 2)
            test.eq(state.quiet(owner, "old", 2), false)
        end)
        test.it("rejects a stale drain and recovers work after an owner exit", function()
            local owner = state.new()
            state.wake(owner)
            state.ready(owner, "old")
            state.wake(owner)
            test.eq(state.quiet(owner, "old", 1), false)
            test.eq(state.stopped(owner), "start")
        end)
        test.it("keeps a drained owner stopped until fresh demand", function()
            local owner = state.new()
            state.wake(owner)
            state.ready(owner, "old")
            test.eq(state.quiet(owner, "old", 1), true)
            test.eq(state.stopped(owner), "wait")
            test.eq(state.wake(owner), "start")
        end)
    end)
end
return test.run_cases(define_tests)
