-- SPDX-License-Identifier: MIT
local test = require("test")
local task = require("task")
local function define_tests()
    test.describe("Guarded owner tasks", function()
        test.it("becomes quiet only after its pass completes", function()
            local work = task.new("probe", function(): boolean return true end)
            task.advance(work)
            test.eq(task.quiet(work), false)
            local quiet, open = work.completed:receive()
            test.eq(open, true)
            task.finish(work, quiet == true)
            test.eq(task.quiet(work), true)
        end)
        test.it("keeps a retry active and runs it only at its deadline", function()
            local calls = 0
            local work = task.new("retry", function(): boolean
                calls = calls + 1
                return calls > 1
            end)
            task.advance(work)
            local first, open = work.completed:receive()
            test.eq(open, true)
            task.finish(work, first == true)
            test.eq(task.quiet(work), false)
            test.is_true(work.due ~= nil)
            task.advance(work)
            test.eq(calls, 1)
            local deadline = assert(task.deadline(work))
            deadline:receive()
            task.advance(work)
            local quiet, finished = work.completed:receive()
            test.eq(finished, true)
            task.finish(work, quiet == true)
            test.eq(calls, 2)
            test.eq(task.quiet(work), true)
        end)
        test.it("retains a wake received while a task completes", function()
            local work = task.new("wake", function(): boolean return true end)
            task.advance(work)
            task.wake(work)
            local quiet, open = work.completed:receive()
            test.eq(open, true)
            task.finish(work, quiet == true)
            test.eq(task.quiet(work), false)
            task.advance(work)
            quiet, open = work.completed:receive()
            test.eq(open, true)
            task.finish(work, quiet == true)
            test.eq(task.quiet(work), true)
        end)
    end)
end
return test.run_cases(define_tests)
