local STATEMENTS = {
    [[PRAGMA defer_foreign_keys = ON]],
    [[DROP INDEX bee_approval_requests_pending]],
    [[DROP INDEX bee_approval_requests_workspace]],
    [[DROP INDEX bee_approval_requests_effects]],
    [[DROP INDEX bee_approval_outbox_due]],
    [[ALTER TABLE bee_approval_history RENAME TO bee_approval_history_prev]],
    [[ALTER TABLE bee_approval_outbox RENAME TO bee_approval_outbox_prev]],
    [[ALTER TABLE bee_approval_requests RENAME TO bee_approval_requests_prev]],
    [[CREATE TABLE "bee_approval_requests" ( approval_id TEXT PRIMARY KEY, owner_node TEXT NOT NULL, owner_incarnation INTEGER NOT NULL, workspace_id TEXT NOT NULL, requester_id TEXT NOT NULL, requester_key TEXT NOT NULL, request_digest TEXT NOT NULL, request_kind TEXT NOT NULL CHECK (request_kind IN ('permission', 'question')), policy TEXT NOT NULL, proposal_json TEXT NOT NULL CHECK (length(CAST(proposal_json AS BLOB)) <= 8192), proposal_digest TEXT NOT NULL, prompt_json TEXT NOT NULL, response_schema_json TEXT NOT NULL CHECK (length(CAST(response_schema_json AS BLOB)) <= 4096), thread_id TEXT, binding_json TEXT, revision INTEGER NOT NULL CHECK (revision > 0), state TEXT NOT NULL CHECK (state IN ('pending', 'decided', 'expired', 'withdrawn', 'superseded', 'invalidated')), decision TEXT CHECK (decision IN ('approved', 'denied')), decider_id TEXT, decided_at TEXT, response_json TEXT, validated_incarnation INTEGER, validated_by TEXT, validated_at TEXT, consumer_id TEXT, consumed_effect TEXT, consumed_at TEXT, expires_ms INTEGER NOT NULL, expires_at TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, effect_completed_at TEXT, effect_result_json TEXT, window_grant_id TEXT, allowed_by_grant TEXT, contract_version INTEGER NOT NULL DEFAULT 1, contract_json TEXT, reviewed_digest TEXT, effect_admission_ms INTEGER, UNIQUE (requester_id, requester_key) )]],
    [[CREATE TABLE bee_approval_history ( approval_id TEXT NOT NULL REFERENCES bee_approval_requests(approval_id), revision INTEGER NOT NULL, state TEXT NOT NULL, decision TEXT, actor_id TEXT NOT NULL, reason TEXT NOT NULL, at TEXT NOT NULL, PRIMARY KEY (approval_id, revision) )]],
    [[CREATE TABLE "bee_approval_outbox" ( event_id TEXT PRIMARY KEY, approval_id TEXT NOT NULL REFERENCES bee_approval_requests(approval_id), revision INTEGER NOT NULL, thread_id TEXT NOT NULL, kind TEXT NOT NULL CHECK (kind IN ('approval.request', 'approval.transition', 'message')), body_json TEXT NOT NULL CHECK (length(CAST(body_json AS BLOB)) <= 16384), context_json TEXT, attempts INTEGER NOT NULL DEFAULT 0, next_attempt_ms INTEGER NOT NULL, lease_owner TEXT, lease_until_ms INTEGER, acknowledged_at TEXT, exhausted_at TEXT, last_error TEXT, created_at TEXT NOT NULL )]],
    [[INSERT INTO bee_approval_requests (approval_id, owner_node, owner_incarnation, workspace_id, requester_id, requester_key, request_digest, request_kind, policy, proposal_json, proposal_digest, prompt_json, response_schema_json, thread_id, binding_json, revision, state, decision, decider_id, decided_at, response_json, validated_incarnation, validated_by, validated_at, consumer_id, consumed_effect, consumed_at, expires_ms, expires_at, created_at, updated_at, effect_completed_at, effect_result_json, window_grant_id, allowed_by_grant) SELECT approval_id, owner_node, owner_incarnation, workspace_id, requester_id, requester_key, request_digest, request_kind, policy, proposal_json, proposal_digest, prompt_json, response_schema_json, thread_id, binding_json, revision, state, decision, decider_id, decided_at, response_json, validated_incarnation, validated_by, validated_at, consumer_id, consumed_effect, consumed_at, expires_ms, expires_at, created_at, updated_at, effect_completed_at, effect_result_json, window_grant_id, allowed_by_grant FROM bee_approval_requests_prev]],
    [[INSERT INTO bee_approval_history SELECT * FROM bee_approval_history_prev]],
    [[INSERT INTO bee_approval_outbox SELECT * FROM bee_approval_outbox_prev]],
    [[DROP TABLE bee_approval_history_prev]],
    [[DROP TABLE bee_approval_outbox_prev]],
    [[DROP TABLE bee_approval_requests_prev]],
    [[CREATE INDEX bee_approval_requests_workspace ON bee_approval_requests (workspace_id, state)]],
    [[CREATE INDEX bee_approval_requests_effects ON bee_approval_requests (state, decision, effect_completed_at, approval_id)]],
    [[CREATE TABLE bee_approval_decisions (decision_id TEXT PRIMARY KEY, approval_id TEXT NOT NULL REFERENCES bee_approval_requests(approval_id), revision INTEGER NOT NULL, kind TEXT NOT NULL CHECK(kind IN ('allow_once','allow_grant','deny','answer')), decider_json TEXT NOT NULL, reviewed_digest TEXT NOT NULL, reviewed_revision INTEGER NOT NULL, reason TEXT NOT NULL, assurance_json TEXT NOT NULL, response_json TEXT, created_at TEXT NOT NULL, UNIQUE(approval_id, revision))]],
    [[CREATE INDEX bee_approval_outbox_due ON bee_approval_outbox (acknowledged_at, exhausted_at, next_attempt_ms)]],
    [[CREATE TABLE bee_approval_grants (grant_id TEXT PRIMARY KEY, approval_id TEXT NOT NULL REFERENCES bee_approval_requests(approval_id), decision_id TEXT NOT NULL REFERENCES bee_approval_decisions(decision_id), subject_json TEXT NOT NULL, scope_json TEXT NOT NULL, terms_json TEXT NOT NULL, state TEXT NOT NULL CHECK(state IN ('active','revoked','expired','exhausted')), revision INTEGER NOT NULL, used INTEGER NOT NULL DEFAULT 0, until_ms INTEGER, max_uses INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL)]],
    [[CREATE TABLE bee_approval_effects (approval_id TEXT PRIMARY KEY REFERENCES bee_approval_requests(approval_id), effect_id TEXT NOT NULL, destination TEXT, context_json TEXT NOT NULL, state TEXT NOT NULL CHECK(state IN ('waiting','authorized','reserved','admitted','started','succeeded','failed','canceled','uncertain')), revision INTEGER NOT NULL DEFAULT 1, consumer_id TEXT, owner_incarnation INTEGER, receipt_json TEXT, updated_at TEXT NOT NULL, UNIQUE(destination, effect_id))]],
    [[CREATE TABLE bee_approval_events (seq INTEGER PRIMARY KEY AUTOINCREMENT, event_id TEXT NOT NULL UNIQUE, approval_id TEXT NOT NULL REFERENCES bee_approval_requests(approval_id), revision INTEGER NOT NULL, kind TEXT NOT NULL, destination TEXT NOT NULL, body_json TEXT NOT NULL, acknowledged_at TEXT, created_at TEXT NOT NULL)]],
    [[CREATE INDEX bee_approval_events_due ON bee_approval_events(destination, acknowledged_at, seq)]],
    [[UPDATE bee_approval_requests SET reviewed_digest = proposal_digest, effect_admission_ms = expires_ms, contract_json = json_object('requester',json_object('actor_id',requester_id),'subject',json_object('principal_id',requester_id),'provenance',json_object('kind','legacy'),'scope',json_object('type','exact','parameters',json(proposal_json)),'action_digest',proposal_digest,'evidence',json('[]'),'presentation','inbox')]],
    [[INSERT INTO bee_approval_decisions SELECT approval_id || ':decision:' || revision, approval_id, revision, CASE WHEN decision = 'denied' THEN 'deny' WHEN request_kind = 'question' THEN 'answer' WHEN window_grant_id IS NOT NULL THEN 'allow_grant' ELSE 'allow_once' END, json_object('actor_id',decider_id,'provenance','legacy'), proposal_digest, revision - 1, 'legacy decision', '{"kind":"legacy"}', response_json, decided_at FROM bee_approval_requests WHERE state = 'decided' ]],
    [[INSERT INTO bee_approval_grants SELECT approval_id || ':grant', approval_id, approval_id || ':decision:' || revision, json_object('principal_id',requester_id), json_object('type','exact','parameters',json(proposal_json)), '{"kind":"once","time_basis":"absolute"}', CASE WHEN consumed_effect IS NOT NULL THEN 'exhausted' WHEN expires_ms <= CAST(strftime('%s','now') AS INTEGER)*1000 THEN 'expired' ELSE 'active' END, 1, CASE WHEN consumed_effect IS NULL THEN 0 ELSE 1 END, expires_ms, 1, decided_at FROM bee_approval_requests WHERE state = 'decided' AND decision = 'approved' ]],
    [[INSERT INTO bee_approval_effects SELECT approval_id, COALESCE(consumed_effect, approval_id), NULL, '{}', CASE WHEN effect_completed_at IS NOT NULL THEN CASE WHEN state <> 'decided' OR decision = 'denied' THEN 'canceled' ELSE 'succeeded' END WHEN consumed_effect IS NOT NULL THEN 'admitted' WHEN state = 'decided' AND decision = 'approved' THEN 'authorized' WHEN state <> 'pending' THEN 'canceled' ELSE 'waiting' END, 1, consumer_id, validated_incarnation, effect_result_json, updated_at FROM bee_approval_requests]],
    [[INSERT INTO bee_approval_events(event_id,approval_id,revision,kind,destination,body_json,created_at) SELECT approval_id || ':' || revision || ':notification',approval_id,revision,CASE WHEN state = 'pending' THEN 'approval.requested' ELSE 'approval.' || CASE WHEN state = 'decided' THEN decision ELSE state END END, 'requester:' || requester_id, json_object('contract_version',1,'approval_id',approval_id,'revision',revision,'state',state,'decision',decision,'provenance','legacy'),updated_at FROM bee_approval_requests]],
}
return require("migration").define(function()
    migration("Versioned approval lifecycle, exact legacy authority and durable events", function()
        database("sqlite", function()
            up(function(db)
                for _, statement in ipairs(STATEMENTS) do
                    local _, err = db:execute(statement)
                    if err then error(err) end
                end
            end)
        end)
    end)
end)
