-- SPDX-License-Identifier: MIT
local test = require("test")
local drain = require("drain")
local fixture = require("fixture")
local function define_tests()
    test.describe("Activation demand drain", function()
        test.it("drains every bounded batch before becoming quiet", function()
            fixture.reset(3, false, false)
            test.eq(drain.drain(), true)
            test.eq(fixture.calls, 3)
            test.eq(fixture.follows, 1)
        end)
        test.it("retains a failed effect and still reconciles following", function()
            fixture.reset(3, true, false)
            test.eq(drain.drain(), false)
            test.eq(fixture.calls, 1)
            test.eq(fixture.pending(), true)
            test.eq(fixture.follows, 1)
        end)
        test.it("keeps following retries active after the effect queues drain", function()
            fixture.reset(1, false, true)
            test.eq(drain.drain(), false)
            test.eq(fixture.pending(), false)
        end)
    end)
end
return test.run_cases(define_tests)
