local test = require("test")
local sql = require("sql")
local funcs = require("funcs")
local json = require("json")
local bounds = require("bounds")
local DATABASE = "bee.tests.gov:grant_migration_db"
local function migrate(name: string)
    local id = "bee.gov.migrations:" .. name
    local result, err = funcs.call(id,{target_db = "bee:db",database_id = DATABASE,direction = "up",id = id})
    assert(not err,tostring(err))
    local reply = assert(bounds.object(result))
    assert(reply.status ~= "error",tostring(reply.error))
end
local function define_tests()
    test.describe("Governance grant migration",function()
        test.it("preserves legacy envelope limits, reserved admissions, revocations and follow progress",function()
            for _, name in ipairs({"staging","plans","activations","complete","uninstall","plan_author","activation_endings","follow_source"}) do migrate(name) end
            local db = assert(sql.get(DATABASE))
            assert(db:execute([[INSERT INTO bee_governance_leases VALUES ('node','workspace','lease','target','[]',?,'approval',?,1,'person','2026-10-01T00:00:00Z','2026-10-02T00:00:00Z',3,2,7,'active',NULL,NULL)]],{string.rep("a",64),string.rep("b",64)}))
            assert(db:execute([[INSERT INTO bee_governance_lease_uses VALUES ('node','workspace','lease','reserved','approval',?,'[]',?,'reserved','2026-10-01T00:00:00Z',NULL)]],{string.rep("b",64),string.rep("c",64)}))
            assert(db:execute([[INSERT INTO bee_governance_lease_uses VALUES ('node','workspace','lease','admitted','approval',?,'[]',?,'admitted','2026-10-01T00:00:00Z','2026-10-01T00:01:00Z')]],{string.rep("b",64),string.rep("d",64)}))
            local progress = {source_node = "source",source_workspace = "source-workspace",component = "component",mode = "following",revision = 6,cursor = 81,version = "1.0.0",artifact_digest = string.rep("e",64),last_outcome = "applied"}
            assert(db:execute("INSERT INTO bee_governance_follow VALUES ('node','workspace','source','source-workspace','component',?)",{json.encode(progress)}))
            migrate("grants")
            migrate("follow_grants")
            migrate("grants")
            migrate("follow_grants")
            local rows = assert(db:query("SELECT * FROM bee_approval_grants WHERE domain = 'governance_lease'"))
            test.eq(#rows,1)
            test.eq(rows[1].revision,7)
            test.eq(rows[1].max_uses,3)
            test.eq(rows[1].used,1)
            test.eq(rows[1].reserved,1)
            test.eq(rows[1].until_ms,1790899200000)
            test.eq(assert(bounds.object(json.decode(rows[1].provenance_json))).kind,"legacy")
            test.eq(#assert(db:query("SELECT * FROM bee_approval_grant_uses WHERE grant_id = ?",{rows[1].grant_id})),2)
            local consent = assert(db:query("SELECT * FROM bee_approval_grants WHERE domain = 'follow_source'"))[1]
            test.eq(consent.until_ms,nil)
            test.eq(consent.max_uses,nil)
            local provenance = assert(bounds.object(json.decode(consent.provenance_json)))
            test.eq(provenance.kind,"legacy")
            test.eq(provenance.consenting_actor,"unrecorded")
            local restored = assert(bounds.object(json.decode(assert(db:query("SELECT state_json FROM bee_governance_follow_progress"))[1].state_json)))
            test.eq(restored.mode,nil)
            test.eq(restored.cursor,81)
            test.eq(restored.grant_id,consent.grant_id)
            test.eq(#assert(db:query("SELECT name FROM sqlite_master WHERE type = 'table' AND name IN ('bee_governance_leases','bee_governance_follow')")),0)
            test.eq(#assert(db:query("PRAGMA foreign_key_check")),0)
            db:release()
        end)
    end)
end
return test.run_cases(define_tests)
