local test = require("test")
local lifecycle = require("lifecycle")
local contract = require("contract")
local catalog = require("catalog")
local function define_tests()
    test.describe("Application ownership boundaries", function()
        test.it("does not publish open before ready or close before EXIT", function()
            local state = lifecycle.start(10)
            local next_state, effect = lifecycle.reduce(state, "tick", 12)
            test.eq(effect, "none")
            state, effect = lifecycle.reduce(next_state, "ready", 12)
            test.eq(effect, "opened")
            state, effect = lifecycle.reduce(state, "stop", 12)
            test.eq(effect, "close")
            test.eq(state.phase, "stopping")
            state, effect = lifecycle.reduce(state, "tick", 12.25)
            test.eq(effect, "terminate")
            test.eq(state.phase, "terminating")
            state, effect = lifecycle.reduce(state, "ready", 12.3)
            test.eq(effect, "none")
            state, effect = lifecycle.reduce(state, "exit", 12.4)
            test.eq(effect, "closed")
            state, effect = lifecycle.reduce(state, "exit", 12.5)
            test.eq(effect, "none")
        end)
        test.it("retains failed startup until EXIT and allows force retry", function()
            local state, effect = lifecycle.reduce(lifecycle.start(0), "tick", 3)
            test.eq(state.failure, "startup_timeout")
            test.eq(effect, "terminate")
            state.deadline = 0
            state, effect = lifecycle.reduce(state, "force_stop", 4)
            test.eq(effect, "terminate")
            test.eq(state.deadline, 5)
            state, effect = lifecycle.reduce(state, "exit", 4.1)
            test.eq(effect, "failed")
            test.eq(state.failure, "startup_timeout")
        end)
        test.it("classifies an exit before close begins as an application failure", function()
            local state = lifecycle.start(0)
            state = lifecycle.reduce(state, "ready", 0)
            local stopped, effect = lifecycle.reduce(state, "unexpected_exit", 1)
            test.eq(effect, "failed")
            test.eq(stopped.phase, "stopped")
        end)
        test.it("classifies a ready exit by its result", function()
            local ready = lifecycle.reduce(lifecycle.start(0), "ready", 0)
            test.eq(lifecycle.exit_event(ready, false), "exit")
            test.eq(lifecycle.exit_event(ready, true), "unexpected_exit")
            local closed, effect = lifecycle.reduce(ready, lifecycle.exit_event(ready, false), 1)
            test.eq(effect, "closed")
            test.eq(closed.failure, "")
            local stopping = lifecycle.reduce(ready, "stop", 1)
            test.eq(lifecycle.exit_event(stopping, true), "exit")
        end)
        test.it("replaces only compatible automatic definition revisions", function()
            local function descriptor(revision: string, schema: string, policy: string)
                return assert(contract.descriptor("test:app", {api_version = 1, lifetime = "view", title = "Test",
                    revision = revision, instance_policy = "singleton", resume_schema = schema,
                    restart_policy = policy}))
            end
            local running = descriptor("1", "state.v1", "automatic")
            test.is_false(catalog.replaces(running, running))
            test.is_true(catalog.replaces(running, descriptor("2", "state.v1", "automatic")))
            test.is_false(catalog.replaces(running, descriptor("2", "state.v2", "automatic")))
            test.is_false(catalog.replaces(running, descriptor("2", "state.v1", "manual")))
            test.is_false(catalog.replaces(running, nil))
        end)
        test.it("keeps negotiated close alive until an explicit decision", function()
            local state = lifecycle.start(0)
            state = lifecycle.reduce(state, "ready", 0)
            local effect
            state, effect = lifecycle.reduce(state, "request_close", 1)
            test.eq(effect, "query_close")
            test.eq(state.phase, "close_requested")
            local duplicate, duplicate_effect = lifecycle.reduce(state, "request_close", 2)
            test.eq(duplicate, state)
            test.eq(duplicate_effect, "none")
            test.eq(duplicate.deadline, 3)
            state, effect = lifecycle.reduce(state, "confirm_close", 2)
            test.eq(state.phase, "close_confirming")
            test.eq(state.deadline, 0)
            state, effect = lifecycle.reduce(state, "tick", 1000)
            test.eq(effect, "none")
            state, effect = lifecycle.reduce(state, "stop", 1001)
            test.eq(effect, "none")
            state, effect = lifecycle.reduce(state, "cancel_close", 1002)
            test.eq(effect, "close_cancelled")
            test.eq(state.phase, "ready")
            state, effect = lifecycle.reduce(state, "accept_close", 1003)
            test.eq(effect, "none")
            state = lifecycle.reduce(state, "request_close", 1004)
            state, effect = lifecycle.reduce(state, "accept_close", 1005)
            test.eq(effect, "close")
            test.eq(state.phase, "stopping")
            test.eq(state.deadline, 1005.25)
            state, effect = lifecycle.reduce(state, "cancel_close", 1005.1)
            test.eq(effect, "none")
            state, effect = lifecycle.reduce(state, "tick", 1005.25)
            test.eq(effect, "terminate")
        end)
        test.it("uses the host-selected cooperative close grace", function()
            local state = lifecycle.start(0)
            state = lifecycle.reduce(state, "ready", 0)
            state = lifecycle.reduce(state, "request_close", 1)
            local effect
            state, effect = lifecycle.reduce(state, "accept_close", 2, 3200)
            test.eq(state.phase, "stopping")
            test.eq(state.deadline, 5.2)
            test.eq(effect, "close")
            local forced, force_effect = lifecycle.reduce(state, "force_stop", 2.1, 60000)
            test.eq(force_effect, "terminate")
            test.eq(forced.phase, "terminating")
            test.eq(forced.deadline, 3.1)
            state, effect = lifecycle.reduce(state, "tick", 5.19, 3200)
            test.eq(state.phase, "stopping")
            test.eq(effect, "none")
            state, effect = lifecycle.reduce(state, "tick", 5.2, 3200)
            test.eq(state.phase, "terminating")
            test.eq(effect, "terminate")
            local stopped = lifecycle.reduce(lifecycle.start(0), "stop", 1, 3200)
            test.eq(stopped.phase, "stopping")
            test.eq(stopped.deadline, 4.2)
        end)
        test.it("reports an unanswered close without automatically destroying work", function()
            local state = lifecycle.start(0)
            state = lifecycle.reduce(state, "ready", 0)
            state = lifecycle.reduce(state, "request_close", 1)
            local effect
            state, effect = lifecycle.reduce(state, "tick", 3)
            test.eq(effect, "close_timeout")
            test.eq(state.phase, "close_unresponsive")
            test.eq(state.deadline, 0)
            state, effect = lifecycle.reduce(state, "tick", 999)
            test.eq(effect, "none")
            state, effect = lifecycle.reduce(state, "accept_close", 1000)
            test.eq(effect, "none")
            state, effect = lifecycle.reduce(state, "force_stop", 1001)
            test.eq(effect, "terminate")
            state, effect = lifecycle.reduce(state, "exit", 1002)
            test.eq(effect, "closed")
        end)
        test.it("allows app exit or explicit force stop while a confirmation is pending", function()
            local state = lifecycle.start(0)
            state = lifecycle.reduce(state, "ready", 0)
            state = lifecycle.reduce(state, "request_close", 1)
            state = lifecycle.reduce(state, "confirm_close", 1.1)
            local exited, effect = lifecycle.reduce(state, "exit", 2)
            test.eq(effect, "closed")
            test.eq(exited.phase, "stopped")
            local forced, force_effect = lifecycle.reduce(state, "force_stop", 2)
            test.eq(force_effect, "terminate")
            test.eq(forced.phase, "terminating")
        end)
        test.it("rejects malformed requests and self-selected grants", function()
            test.is_nil(contract.request({version = 1, op = "bind", request_id = "1", id = "view"}))
            test.is_nil(contract.request({version = 1, op = "bind", request_id = "1", instance_id = "instance"}))
            test.not_nil(contract.request({version = 1, op = "bind", request_id = "1", id = "view", instance_id = "instance"}))
            test.not_nil(contract.request({version = 1, op = "bind", request_id = "1"}))
            test.is_nil(contract.request({version = 1, op = "unbind", request_id = "1"}))
            test.is_nil(contract.request({version = 1, op = "unbind", request_id = "1", recipient = "client", id = "view"}))
            test.not_nil(contract.request({version = 1, op = "unbind", request_id = "1", recipient = "client"}))
            test.is_nil(contract.request({op = "open", request_id = "1", definition_id = "test:app"}))
            test.is_nil(contract.request({version = 1, op = "open", request_id = "", definition_id = "test:app"}))
            test.is_nil(contract.request({version = 1, op = "open", request_id = "1", definition_id = "test:\27app"}))
            test.is_nil(contract.binding({definition_id = "test:app", policies = {[2] = "test:policy"}}))
            test.is_nil(contract.binding({definition_id = "test:app", policies = {}, appearance_write = "true"}))
            local descriptor = contract.descriptor("test:app", {api_version = 1, lifetime = "view", title = "Test",
                revision = "1", instance_policy = "multiple", policies = {"root"}, appearance_write = true})
            test.not_nil(descriptor)
            local binding = contract.binding({definition_id = "test:app", policies = {}})
            test.not_nil(binding)
            if binding then
                test.is_false(binding.appearance_write)
                test.is_false(binding.application_stop)
                test.eq(binding.close_grace_ms, 250)
            end
        end)
    end)
end
local cases = test.run_cases(define_tests)
return {run = function(options) return cases(options) end}
