local test = require("test")
local lifecycle = require("lifecycle")
local contract = require("contract")
local function define_tests()
    test.describe("Application ownership boundaries", function()
        test.it("does not publish open before ready or close before EXIT", function()
            local state = lifecycle.start(10)
            local next_state, effect = lifecycle.reduce(state, "tick", 12)
            test.eq(effect, "none")
            state, effect = lifecycle.reduce(next_state, "ready", 12)
            test.eq(effect, "opened")
            state, effect = lifecycle.reduce(state, "stop", 12)
            test.eq(effect, "close")
            test.eq(state.phase, "stopping")
            state, effect = lifecycle.reduce(state, "tick", 12.25)
            test.eq(effect, "terminate")
            test.eq(state.phase, "terminating")
            state, effect = lifecycle.reduce(state, "ready", 12.3)
            test.eq(effect, "none")
            state, effect = lifecycle.reduce(state, "exit", 12.4)
            test.eq(effect, "closed")
            state, effect = lifecycle.reduce(state, "exit", 12.5)
            test.eq(effect, "none")
        end)
        test.it("retains failed startup until EXIT and allows force retry", function()
            local state, effect = lifecycle.reduce(lifecycle.start(0), "tick", 3)
            test.eq(state.failure, "startup_timeout")
            test.eq(effect, "terminate")
            state.deadline = 0
            state, effect = lifecycle.reduce(state, "force_stop", 4)
            test.eq(effect, "terminate")
            test.eq(state.deadline, 5)
            state, effect = lifecycle.reduce(state, "exit", 4.1)
            test.eq(effect, "failed")
            test.eq(state.failure, "startup_timeout")
        end)
        test.it("keeps negotiated close alive until an explicit decision", function()
            local state = lifecycle.start(0)
            state = lifecycle.reduce(state, "ready", 0)
            local effect
            state, effect = lifecycle.reduce(state, "request_close", 1)
            test.eq(effect, "query_close")
            test.eq(state.phase, "close_requested")
            local duplicate, duplicate_effect = lifecycle.reduce(state, "request_close", 2)
            test.eq(duplicate, state)
            test.eq(duplicate_effect, "none")
            test.eq(duplicate.deadline, 3)
            state, effect = lifecycle.reduce(state, "confirm_close", 2)
            test.eq(state.phase, "close_confirming")
            test.eq(state.deadline, 0)
            state, effect = lifecycle.reduce(state, "tick", 1000)
            test.eq(effect, "none")
            state, effect = lifecycle.reduce(state, "stop", 1001)
            test.eq(effect, "none")
            state, effect = lifecycle.reduce(state, "cancel_close", 1002)
            test.eq(effect, "close_cancelled")
            test.eq(state.phase, "ready")
            state, effect = lifecycle.reduce(state, "accept_close", 1003)
            test.eq(effect, "none")
            state = lifecycle.reduce(state, "request_close", 1004)
            state, effect = lifecycle.reduce(state, "accept_close", 1005)
            test.eq(effect, "close")
            test.eq(state.phase, "stopping")
            test.eq(state.deadline, 1005.25)
            state, effect = lifecycle.reduce(state, "cancel_close", 1005.1)
            test.eq(effect, "none")
            state, effect = lifecycle.reduce(state, "tick", 1005.25)
            test.eq(effect, "terminate")
        end)
        test.it("reports an unanswered close without automatically destroying work", function()
            local state = lifecycle.start(0)
            state = lifecycle.reduce(state, "ready", 0)
            state = lifecycle.reduce(state, "request_close", 1)
            local effect
            state, effect = lifecycle.reduce(state, "tick", 3)
            test.eq(effect, "close_timeout")
            test.eq(state.phase, "close_unresponsive")
            test.eq(state.deadline, 0)
            state, effect = lifecycle.reduce(state, "tick", 999)
            test.eq(effect, "none")
            state, effect = lifecycle.reduce(state, "accept_close", 1000)
            test.eq(effect, "none")
            state, effect = lifecycle.reduce(state, "force_stop", 1001)
            test.eq(effect, "terminate")
            state, effect = lifecycle.reduce(state, "exit", 1002)
            test.eq(effect, "closed")
        end)
        test.it("allows app exit or explicit force stop while a confirmation is pending", function()
            local state = lifecycle.start(0)
            state = lifecycle.reduce(state, "ready", 0)
            state = lifecycle.reduce(state, "request_close", 1)
            state = lifecycle.reduce(state, "confirm_close", 1.1)
            local exited, effect = lifecycle.reduce(state, "exit", 2)
            test.eq(effect, "closed")
            test.eq(exited.phase, "stopped")
            local forced, force_effect = lifecycle.reduce(state, "force_stop", 2)
            test.eq(force_effect, "terminate")
            test.eq(forced.phase, "terminating")
        end)
        test.it("rejects malformed requests and self-selected grants", function()
            test.is_nil(contract.request({op = "open", request_id = "1", definition_id = "test:app"}))
            test.is_nil(contract.request({version = 1, op = "open", request_id = "", definition_id = "test:app"}))
            test.is_nil(contract.request({version = 1, op = "open", request_id = "1", definition_id = "test:\27app"}))
            test.is_nil(contract.binding({definition_id = "test:app", policies = {[2] = "test:policy"}}))
            test.is_nil(contract.binding({definition_id = "test:app", policies = {}, appearance_write = "true"}))
            local descriptor = contract.descriptor("test:app", {api_version = 1, lifetime = "view", title = "Test",
                revision = "1", instance_policy = "multiple", policies = {"root"}, appearance_write = true})
            test.not_nil(descriptor)
            local binding = contract.binding({definition_id = "test:app", policies = {}})
            test.not_nil(binding)
            if binding then test.is_false(binding.appearance_write); test.is_false(binding.application_stop) end
        end)
    end)
end
local cases = test.run_cases(define_tests)
return {run = function(options) return cases(options) end}
