local test = require("test")
local lifecycle = require("lifecycle")
local contract = require("contract")
local function define_tests()
    test.describe("Application ownership boundaries", function()
        test.it("does not publish open before ready or close before EXIT", function()
            local state = lifecycle.start(10)
            local next_state, effect = lifecycle.reduce(state, "tick", 12)
            test.eq(effect, "none")
            state, effect = lifecycle.reduce(next_state, "ready", 12)
            test.eq(effect, "opened")
            state, effect = lifecycle.reduce(state, "stop", 12)
            test.eq(effect, "close")
            test.eq(state.phase, "stopping")
            state, effect = lifecycle.reduce(state, "tick", 12.25)
            test.eq(effect, "terminate")
            test.eq(state.phase, "terminating")
            state, effect = lifecycle.reduce(state, "ready", 12.3)
            test.eq(effect, "none")
            state, effect = lifecycle.reduce(state, "exit", 12.4)
            test.eq(effect, "closed")
            state, effect = lifecycle.reduce(state, "exit", 12.5)
            test.eq(effect, "none")
        end)
        test.it("retains failed startup until EXIT and allows force retry", function()
            local state, effect = lifecycle.reduce(lifecycle.start(0), "tick", 3)
            test.eq(state.failure, "startup_timeout")
            test.eq(effect, "terminate")
            state.deadline = 0
            state, effect = lifecycle.reduce(state, "force_stop", 4)
            test.eq(effect, "terminate")
            test.eq(state.deadline, 5)
            state, effect = lifecycle.reduce(state, "exit", 4.1)
            test.eq(effect, "failed")
            test.eq(state.failure, "startup_timeout")
        end)
        test.it("rejects malformed requests and self-selected grants", function()
            test.is_nil(contract.request({op = "open", request_id = "1", definition_id = "test:app"}))
            test.is_nil(contract.request({version = 1, op = "open", request_id = "", definition_id = "test:app"}))
            test.is_nil(contract.request({version = 1, op = "open", request_id = "1", definition_id = "test:\27app"}))
            test.is_nil(contract.binding({definition_id = "test:app", policies = {[2] = "test:policy"}}))
            test.is_nil(contract.binding({definition_id = "test:app", policies = {}, appearance_write = "true"}))
            local descriptor = contract.descriptor("test:app", {api_version = 1, lifetime = "view", title = "Test",
                revision = "1", instance_policy = "multiple", policies = {"root"}, appearance_write = true})
            test.not_nil(descriptor)
            local binding = contract.binding({definition_id = "test:app", policies = {}})
            test.not_nil(binding)
            if binding then test.is_false(binding.appearance_write); test.is_false(binding.application_stop) end
        end)
    end)
end
local cases = test.run_cases(define_tests)
return {run = function(options) return cases(options) end}
