-- MIT. Immutable schema ledger for the owner-local synchronized projection.
local M = {}
type Migration = {id: integer, name: string, sql: string, rebuild: boolean}
local INITIAL = [[
CREATE TABLE bee_sync_feeds (
  owner_id TEXT NOT NULL,
  feed TEXT NOT NULL,
  head_sequence INTEGER NOT NULL CHECK(head_sequence >= 0),
  earliest_sequence INTEGER NOT NULL CHECK(earliest_sequence >= 1),
  event_capacity INTEGER NOT NULL CHECK(event_capacity BETWEEN 1 AND 1024),
  receipt_capacity INTEGER NOT NULL CHECK(receipt_capacity BETWEEN 1 AND 8192),
  PRIMARY KEY(owner_id, feed)
);
CREATE TABLE bee_sync_projections (
  owner_id TEXT NOT NULL,
  feed TEXT NOT NULL,
  projection_key TEXT NOT NULL,
  revision INTEGER NOT NULL CHECK(revision > 0),
  value_json TEXT,
  tombstone INTEGER NOT NULL CHECK(tombstone IN (0,1)),
  last_sequence INTEGER NOT NULL CHECK(last_sequence > 0),
  updated_at TEXT NOT NULL,
  PRIMARY KEY(owner_id, feed, projection_key),
  FOREIGN KEY(owner_id, feed) REFERENCES bee_sync_feeds(owner_id, feed),
  CHECK((tombstone = 1 AND value_json IS NULL) OR (tombstone = 0 AND value_json IS NOT NULL)),
  CHECK(value_json IS NULL OR length(CAST(value_json AS BLOB)) <= 16384)
);
CREATE TABLE bee_sync_events (
  owner_id TEXT NOT NULL,
  feed TEXT NOT NULL,
  sequence INTEGER NOT NULL CHECK(sequence > 0),
  event_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  payload_json TEXT NOT NULL CHECK(length(CAST(payload_json AS BLOB)) <= 16384),
  projection_key TEXT NOT NULL,
  projection_revision INTEGER NOT NULL CHECK(projection_revision > 0),
  tombstone INTEGER NOT NULL CHECK(tombstone IN (0,1)),
  committed_at TEXT NOT NULL,
  PRIMARY KEY(owner_id, feed, sequence),
  UNIQUE(owner_id, feed, event_id),
  FOREIGN KEY(owner_id, feed, projection_key) REFERENCES bee_sync_projections(owner_id, feed, projection_key)
);
CREATE TABLE bee_sync_receipts (
  owner_id TEXT NOT NULL,
  feed TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  event_id TEXT NOT NULL,
  request_json TEXT NOT NULL CHECK(length(CAST(request_json AS BLOB)) <= 16384),
  sequence INTEGER NOT NULL CHECK(sequence > 0),
  projection_key TEXT NOT NULL,
  projection_revision INTEGER NOT NULL CHECK(projection_revision > 0),
  PRIMARY KEY(owner_id, feed, idempotency_key),
  UNIQUE(owner_id, feed, event_id),
  FOREIGN KEY(owner_id, feed) REFERENCES bee_sync_feeds(owner_id, feed)
);
CREATE INDEX bee_sync_events_window ON bee_sync_events(owner_id, feed, sequence);
CREATE INDEX bee_sync_projection_snapshot ON bee_sync_projections(owner_id, feed, projection_key);
]]
local LAYOUT_REFERENCES_SQL = [[
UPDATE bee_sync_projections SET value_json = (
  WITH RECURSIVE identity_moves(position, prior, current) AS (VALUES
    (1, '"bee.driver.wippy:run"', '"bee.driver.wippy.binding:run"'),
    (2, '"bee.gateway:address"', '"bee.gateway.binding:address"'),
    (3, '"bee.git.worktree:cleanup"', '"bee.git.worktree.binding:cleanup"'),
    (4, '"bee.git.worktree:plan"', '"bee.git.worktree.binding:plan"'),
    (5, '"bee.git.worktree:setup"', '"bee.git.worktree.binding:setup"'),
    (6, '"bee.git_worktree"', '"bee.git.worktree"'),
    (7, '"bee.git_worktree:binding"', '"bee.git.worktree:binding"'),
    (8, '"bee.git_worktree:cleanup"', '"bee.git.worktree.binding:cleanup"'),
    (9, '"bee.git_worktree:definition"', '"bee.git.worktree:definition"'),
    (10, '"bee.git_worktree:dependency_driver"', '"bee.git.worktree:dependency_driver"'),
    (11, '"bee.git_worktree:dependency_placement"', '"bee.git.worktree:dependency_placement"'),
    (12, '"bee.git_worktree:dependency_threads"', '"bee.git.worktree:dependency_threads"'),
    (13, '"bee.git_worktree:executor_ref"', '"bee.git.worktree:executor_ref"'),
    (14, '"bee.git_worktree:git_executor"', '"bee.git.worktree:git_executor"'),
    (15, '"bee.git_worktree:git_roots"', '"bee.git.worktree:git_roots"'),
    (16, '"bee.git_worktree:host_files"', '"bee.git.worktree:host_files"'),
    (17, '"bee.git_worktree:host_files_ref"', '"bee.git.worktree:host_files_ref"'),
    (18, '"bee.git_worktree:plan"', '"bee.git.worktree.binding:plan"'),
    (19, '"bee.git_worktree:protected_namespace"', '"bee.git.worktree:protected_namespace"'),
    (20, '"bee.git_worktree:setup"', '"bee.git.worktree.binding:setup"'),
    (21, '"bee.git_worktree:target_executor"', '"bee.git.worktree:target_executor"'),
    (22, '"bee.git_worktree:target_host_files"', '"bee.git.worktree:target_host_files"'),
    (23, '"bee.git_worktree:worktree"', '"bee.git.worktree:worktree"'),
    (24, '"bee.git_worktree:worktree_policy"', '"bee.git.worktree:worktree_policy"'),
    (25, '"bee.harness.carrier:capabilities"', '"bee.harness.binding:capabilities"'),
    (26, '"bee.harness.carrier:process"', '"bee.harness.service:carrier"'),
    (27, '"bee.harness.carrier:types"', '"bee.harness:types"'),
    (28, '"bee.harness.launch:admit"', '"bee.harness.binding:admit"'),
    (29, '"bee.harness.launch:locate_probe"', '"bee.harness.binding:locate_probe"'),
    (30, '"bee.harness.launch:present"', '"bee.harness.binding:present"'),
    (31, '"bee.harness.launch:resolve"', '"bee.harness.binding:resolve"'),
    (32, '"bee.harness.launch:setup"', '"bee.harness.binding:setup"'),
    (33, '"bee.harness.launch:setup_backend"', '"bee.harness.binding:setup_backend"'),
    (34, '"bee.harness.launch:start"', '"bee.harness.binding:start"'),
    (35, '"bee.harness.profiles:call"', '"bee.harness.binding:call"'),
    (36, '"bee.harness.profiles:contract"', '"bee.harness:profiles"'),
    (37, '"bee.harness.profiles:local"', '"bee.harness:profiles_local"'),
    (38, '"bee.hive.telemetry:catalog_list"', '"bee.hive.telemetry.binding:catalog_list"'),
    (39, '"bee.hive.telemetry:cluster"', '"bee.hive.telemetry.binding:cluster"'),
    (40, '"bee.hive.telemetry:holdings"', '"bee.hive.telemetry.binding:holdings"'),
    (41, '"bee.hive.telemetry:presence"', '"bee.hive.telemetry.binding:presence"'),
    (42, '"bee.hive.telemetry:stats"', '"bee.hive.telemetry.binding:stats"'),
    (43, '"bee.hive:invoke_check"', '"bee.hive.binding:invoke_check"'),
    (44, '"bee.placement.native:process_runner"', '"bee.placement.native.service:process_runner"'),
    (45, '"bee.sync.hive:admit"', '"bee.sync.binding:admit"'),
    (46, '"bee.threads.approvals:append"', '"bee.threads.binding:append"'),
    (47, '"bee.threads.carrier:cancel_intent"', '"bee.threads.binding:cancel_intent"'),
    (48, '"bee.threads.carrier:cancel_status"', '"bee.threads.binding:cancel_status"'),
    (49, '"bee.threads.carrier:checkpoint"', '"bee.threads.binding:checkpoint"'),
    (50, '"bee.threads.carrier:claim"', '"bee.threads.binding:claim"'),
    (51, '"bee.threads.carrier:commit"', '"bee.threads.binding:commit"'),
    (52, '"bee.threads.delivery:ack"', '"bee.threads.binding:ack"'),
    (53, '"bee.threads.delivery:ack_page"', '"bee.threads.binding:ack_page"'),
    (54, '"bee.threads.delivery:claim"', '"bee.threads.binding:delivery_claim"'),
    (55, '"bee.threads.delivery:close_subscription"', '"bee.threads.binding:close_subscription"'),
    (56, '"bee.threads.delivery:dispatch"', '"bee.threads.binding:dispatch"'),
    (57, '"bee.threads.delivery:expire"', '"bee.threads.binding:expire"'),
    (58, '"bee.threads.delivery:forget_subscription"', '"bee.threads.binding:forget_subscription"'),
    (59, '"bee.threads.delivery:page"', '"bee.threads.binding:page"'),
    (60, '"bee.threads.delivery:reconcile"', '"bee.threads.binding:reconcile"'),
    (61, '"bee.threads.delivery:release"', '"bee.threads.binding:release"'),
    (62, '"bee.threads.delivery:resume"', '"bee.threads.binding:resume"'),
    (63, '"bee.threads.delivery:subscribe"', '"bee.threads.binding:subscribe"'),
    (64, '"bee.threads.delivery:unsubscribe"', '"bee.threads.binding:unsubscribe"'),
    (65, '"bee.threads.delivery:wait"', '"bee.threads.binding:wait"'),
    (66, '"bee.threads.delivery:waiter"', '"bee.threads.service:waiter"'),
    (67, '"bee.threads.delivery:waiter_service"', '"bee.threads.service:waiter_service"'),
    (68, '"bee.threads.delivery:watch"', '"bee.threads.binding:watch"'),
    (69, '"bee.threads.projection:recap_read"', '"bee.threads.binding:recap_read"'),
    (70, '"bee.threads.projection:recap_rebuild"', '"bee.threads.binding:recap_rebuild"'),
    (71, '"bee.threads.projection:recap_update"', '"bee.threads.binding:recap_update"'),
    (72, '"bee.threads.projection:status_read"', '"bee.threads.binding:status_read"'),
    (73, '"bee.threads.projection:status_rebuild"', '"bee.threads.binding:status_rebuild"'),
    (74, '"bee.threads.projection:status_update"', '"bee.threads.binding:status_update"'),
    (75, '"bee.threads.records:types"', '"bee.threads:record_types"'),
    (76, '"bee.threads.service:admit_action"', '"bee.threads.binding:admit_action"'),
    (77, '"bee.threads.service:close"', '"bee.threads.binding:close"'),
    (78, '"bee.threads.service:create"', '"bee.threads.binding:create"'),
    (79, '"bee.threads.service:end_turn"', '"bee.threads.binding:end_turn"'),
    (80, '"bee.threads.service:feed_read"', '"bee.threads.binding:feed_read"'),
    (81, '"bee.threads.service:fence_app"', '"bee.threads.binding:fence_app"'),
    (82, '"bee.threads.service:get"', '"bee.threads.binding:get"'),
    (83, '"bee.threads.service:inbox_accept"', '"bee.threads.binding:inbox_accept"'),
    (84, '"bee.threads.service:inbox_ack"', '"bee.threads.binding:inbox_ack"'),
    (85, '"bee.threads.service:inbox_describe"', '"bee.threads.binding:inbox_describe"'),
    (86, '"bee.threads.service:inbox_list"', '"bee.threads.binding:inbox_list"'),
    (87, '"bee.threads.service:inbox_offer"', '"bee.threads.binding:inbox_offer"'),
    (88, '"bee.threads.service:inbox_outbox_claim"', '"bee.threads.binding:inbox_outbox_claim"'),
    (89, '"bee.threads.service:inbox_outbox_settle"', '"bee.threads.binding:inbox_outbox_settle"'),
    (90, '"bee.threads.service:inbox_reply"', '"bee.threads.binding:inbox_reply"'),
    (91, '"bee.threads.service:inbox_resolve"', '"bee.threads.binding:inbox_resolve"'),
    (92, '"bee.threads.service:inbox_send"', '"bee.threads.binding:inbox_send"'),
    (93, '"bee.threads.service:inbox_transport"', '"bee.threads.binding:inbox_transport"'),
    (94, '"bee.threads.service:join"', '"bee.threads.binding:join"'),
    (95, '"bee.threads.service:leave"', '"bee.threads.binding:leave"'),
    (96, '"bee.threads.service:list"', '"bee.threads.binding:list"'),
    (97, '"bee.threads.service:list_workspace"', '"bee.threads.binding:list_workspace"'),
    (98, '"bee.threads.service:notify"', '"bee.threads.binding:notify"'),
    (99, '"bee.threads.service:operation_describe"', '"bee.threads.binding:operation_describe"'),
    (100, '"bee.threads.service:operation_lookup"', '"bee.threads.binding:operation_lookup"'),
    (101, '"bee.threads.service:prepare_attempt"', '"bee.threads.binding:prepare_attempt"'),
    (102, '"bee.threads.service:read_after"', '"bee.threads.binding:read_after"'),
    (103, '"bee.threads.service:receipt"', '"bee.threads.binding:receipt"'),
    (104, '"bee.threads.service:record"', '"bee.threads.binding:record"'),
    (105, '"bee.threads.service:register_app_alias"', '"bee.threads.binding:register_app_alias"'),
    (106, '"bee.threads.service:request_turn"', '"bee.threads.binding:request_turn"'),
    (107, '"bee.threads.service:retire_app_alias"', '"bee.threads.binding:retire_app_alias"'),
    (108, '"bee.threads.service:send"', '"bee.threads.binding:send"'),
    (109, '"bee.threads.service:send_status"', '"bee.threads.binding:send_status"'),
    (110, '"bee.threads.service:session_attach"', '"bee.threads.binding:session_attach"'),
    (111, '"bee.threads.service:session_create"', '"bee.threads.binding:session_create"'),
    (112, '"bee.threads.service:session_describe"', '"bee.threads.binding:session_describe"'),
    (113, '"bee.threads.service:session_scan"', '"bee.threads.binding:session_scan"'),
    (114, '"bee.threads.service:session_transition"', '"bee.threads.binding:session_transition"'),
    (115, '"bee.threads.service:start_attempt"', '"bee.threads.binding:start_attempt"'),
    (116, '"bee.threads.service:turn_accept"', '"bee.threads.binding:turn_accept"'),
    (117, '"bee.threads.service:turn_observation"', '"bee.threads.binding:turn_observation"'),
    (118, '"bee.threads.service:turn_pull"', '"bee.threads.binding:turn_pull"'),
    (119, '"bee.threads.service:turn_recover"', '"bee.threads.binding:turn_recover"'),
    (120, '"bee.threads.service:turn_reserve"', '"bee.threads.binding:turn_reserve"'),
    (121, '"bee.threads.service:types"', '"bee.threads:types"'),
    (122, '"bee.threads.service:work_cancel"', '"bee.threads.binding:work_cancel"'),
    (123, '"bee.threads.service:work_describe"', '"bee.threads.binding:work_describe"'),
    (124, '"bee.threads.service:work_history"', '"bee.threads.binding:work_history"'),
    (125, '"bee.threads.service:work_scan"', '"bee.threads.binding:work_scan"'),
    (126, '"bee.threads.service:work_send"', '"bee.threads.binding:work_send"'),
    (127, '"bee.threads.service:work_settle"', '"bee.threads.binding:work_settle"'),
    (128, '"bee.threads.service:work_uncertain"', '"bee.threads.binding:work_uncertain"'),
    (129, '"bee.threads:capabilities"', '"bee.threads.binding:capabilities"'),
    (130, '"bee.threads:owner"', '"bee.threads.service:owner"'),
    (131, '"bee.threads:owner_service"', '"bee.threads.service:owner_service"')),
  rewritten(position, value) AS (
    SELECT 0, value_json
    UNION ALL
    SELECT identity_moves.position, replace(rewritten.value, identity_moves.prior, identity_moves.current)
    FROM rewritten JOIN identity_moves ON identity_moves.position = rewritten.position + 1
  )
  SELECT value FROM rewritten ORDER BY position DESC LIMIT 1
) WHERE json_valid(value_json) AND (instr(value_json, 'bee.driver.wippy') > 0 OR instr(value_json, 'bee.gateway') > 0 OR instr(value_json, 'bee.git.worktree') > 0 OR instr(value_json, 'bee.git_worktree') > 0 OR instr(value_json, 'bee.harness.carrier') > 0 OR instr(value_json, 'bee.harness.launch') > 0 OR instr(value_json, 'bee.harness.profiles') > 0 OR instr(value_json, 'bee.hive') > 0 OR instr(value_json, 'bee.hive.telemetry') > 0 OR instr(value_json, 'bee.placement.native') > 0 OR instr(value_json, 'bee.sync.hive') > 0 OR instr(value_json, 'bee.threads') > 0 OR instr(value_json, 'bee.threads.approvals') > 0 OR instr(value_json, 'bee.threads.carrier') > 0 OR instr(value_json, 'bee.threads.delivery') > 0 OR instr(value_json, 'bee.threads.projection') > 0 OR instr(value_json, 'bee.threads.records') > 0 OR instr(value_json, 'bee.threads.service') > 0);
UPDATE bee_sync_events SET payload_json = (
  WITH RECURSIVE identity_moves(position, prior, current) AS (VALUES
    (1, '"bee.driver.wippy:run"', '"bee.driver.wippy.binding:run"'),
    (2, '"bee.gateway:address"', '"bee.gateway.binding:address"'),
    (3, '"bee.git.worktree:cleanup"', '"bee.git.worktree.binding:cleanup"'),
    (4, '"bee.git.worktree:plan"', '"bee.git.worktree.binding:plan"'),
    (5, '"bee.git.worktree:setup"', '"bee.git.worktree.binding:setup"'),
    (6, '"bee.git_worktree"', '"bee.git.worktree"'),
    (7, '"bee.git_worktree:binding"', '"bee.git.worktree:binding"'),
    (8, '"bee.git_worktree:cleanup"', '"bee.git.worktree.binding:cleanup"'),
    (9, '"bee.git_worktree:definition"', '"bee.git.worktree:definition"'),
    (10, '"bee.git_worktree:dependency_driver"', '"bee.git.worktree:dependency_driver"'),
    (11, '"bee.git_worktree:dependency_placement"', '"bee.git.worktree:dependency_placement"'),
    (12, '"bee.git_worktree:dependency_threads"', '"bee.git.worktree:dependency_threads"'),
    (13, '"bee.git_worktree:executor_ref"', '"bee.git.worktree:executor_ref"'),
    (14, '"bee.git_worktree:git_executor"', '"bee.git.worktree:git_executor"'),
    (15, '"bee.git_worktree:git_roots"', '"bee.git.worktree:git_roots"'),
    (16, '"bee.git_worktree:host_files"', '"bee.git.worktree:host_files"'),
    (17, '"bee.git_worktree:host_files_ref"', '"bee.git.worktree:host_files_ref"'),
    (18, '"bee.git_worktree:plan"', '"bee.git.worktree.binding:plan"'),
    (19, '"bee.git_worktree:protected_namespace"', '"bee.git.worktree:protected_namespace"'),
    (20, '"bee.git_worktree:setup"', '"bee.git.worktree.binding:setup"'),
    (21, '"bee.git_worktree:target_executor"', '"bee.git.worktree:target_executor"'),
    (22, '"bee.git_worktree:target_host_files"', '"bee.git.worktree:target_host_files"'),
    (23, '"bee.git_worktree:worktree"', '"bee.git.worktree:worktree"'),
    (24, '"bee.git_worktree:worktree_policy"', '"bee.git.worktree:worktree_policy"'),
    (25, '"bee.harness.carrier:capabilities"', '"bee.harness.binding:capabilities"'),
    (26, '"bee.harness.carrier:process"', '"bee.harness.service:carrier"'),
    (27, '"bee.harness.carrier:types"', '"bee.harness:types"'),
    (28, '"bee.harness.launch:admit"', '"bee.harness.binding:admit"'),
    (29, '"bee.harness.launch:locate_probe"', '"bee.harness.binding:locate_probe"'),
    (30, '"bee.harness.launch:present"', '"bee.harness.binding:present"'),
    (31, '"bee.harness.launch:resolve"', '"bee.harness.binding:resolve"'),
    (32, '"bee.harness.launch:setup"', '"bee.harness.binding:setup"'),
    (33, '"bee.harness.launch:setup_backend"', '"bee.harness.binding:setup_backend"'),
    (34, '"bee.harness.launch:start"', '"bee.harness.binding:start"'),
    (35, '"bee.harness.profiles:call"', '"bee.harness.binding:call"'),
    (36, '"bee.harness.profiles:contract"', '"bee.harness:profiles"'),
    (37, '"bee.harness.profiles:local"', '"bee.harness:profiles_local"'),
    (38, '"bee.hive.telemetry:catalog_list"', '"bee.hive.telemetry.binding:catalog_list"'),
    (39, '"bee.hive.telemetry:cluster"', '"bee.hive.telemetry.binding:cluster"'),
    (40, '"bee.hive.telemetry:holdings"', '"bee.hive.telemetry.binding:holdings"'),
    (41, '"bee.hive.telemetry:presence"', '"bee.hive.telemetry.binding:presence"'),
    (42, '"bee.hive.telemetry:stats"', '"bee.hive.telemetry.binding:stats"'),
    (43, '"bee.hive:invoke_check"', '"bee.hive.binding:invoke_check"'),
    (44, '"bee.placement.native:process_runner"', '"bee.placement.native.service:process_runner"'),
    (45, '"bee.sync.hive:admit"', '"bee.sync.binding:admit"'),
    (46, '"bee.threads.approvals:append"', '"bee.threads.binding:append"'),
    (47, '"bee.threads.carrier:cancel_intent"', '"bee.threads.binding:cancel_intent"'),
    (48, '"bee.threads.carrier:cancel_status"', '"bee.threads.binding:cancel_status"'),
    (49, '"bee.threads.carrier:checkpoint"', '"bee.threads.binding:checkpoint"'),
    (50, '"bee.threads.carrier:claim"', '"bee.threads.binding:claim"'),
    (51, '"bee.threads.carrier:commit"', '"bee.threads.binding:commit"'),
    (52, '"bee.threads.delivery:ack"', '"bee.threads.binding:ack"'),
    (53, '"bee.threads.delivery:ack_page"', '"bee.threads.binding:ack_page"'),
    (54, '"bee.threads.delivery:claim"', '"bee.threads.binding:delivery_claim"'),
    (55, '"bee.threads.delivery:close_subscription"', '"bee.threads.binding:close_subscription"'),
    (56, '"bee.threads.delivery:dispatch"', '"bee.threads.binding:dispatch"'),
    (57, '"bee.threads.delivery:expire"', '"bee.threads.binding:expire"'),
    (58, '"bee.threads.delivery:forget_subscription"', '"bee.threads.binding:forget_subscription"'),
    (59, '"bee.threads.delivery:page"', '"bee.threads.binding:page"'),
    (60, '"bee.threads.delivery:reconcile"', '"bee.threads.binding:reconcile"'),
    (61, '"bee.threads.delivery:release"', '"bee.threads.binding:release"'),
    (62, '"bee.threads.delivery:resume"', '"bee.threads.binding:resume"'),
    (63, '"bee.threads.delivery:subscribe"', '"bee.threads.binding:subscribe"'),
    (64, '"bee.threads.delivery:unsubscribe"', '"bee.threads.binding:unsubscribe"'),
    (65, '"bee.threads.delivery:wait"', '"bee.threads.binding:wait"'),
    (66, '"bee.threads.delivery:waiter"', '"bee.threads.service:waiter"'),
    (67, '"bee.threads.delivery:waiter_service"', '"bee.threads.service:waiter_service"'),
    (68, '"bee.threads.delivery:watch"', '"bee.threads.binding:watch"'),
    (69, '"bee.threads.projection:recap_read"', '"bee.threads.binding:recap_read"'),
    (70, '"bee.threads.projection:recap_rebuild"', '"bee.threads.binding:recap_rebuild"'),
    (71, '"bee.threads.projection:recap_update"', '"bee.threads.binding:recap_update"'),
    (72, '"bee.threads.projection:status_read"', '"bee.threads.binding:status_read"'),
    (73, '"bee.threads.projection:status_rebuild"', '"bee.threads.binding:status_rebuild"'),
    (74, '"bee.threads.projection:status_update"', '"bee.threads.binding:status_update"'),
    (75, '"bee.threads.records:types"', '"bee.threads:record_types"'),
    (76, '"bee.threads.service:admit_action"', '"bee.threads.binding:admit_action"'),
    (77, '"bee.threads.service:close"', '"bee.threads.binding:close"'),
    (78, '"bee.threads.service:create"', '"bee.threads.binding:create"'),
    (79, '"bee.threads.service:end_turn"', '"bee.threads.binding:end_turn"'),
    (80, '"bee.threads.service:feed_read"', '"bee.threads.binding:feed_read"'),
    (81, '"bee.threads.service:fence_app"', '"bee.threads.binding:fence_app"'),
    (82, '"bee.threads.service:get"', '"bee.threads.binding:get"'),
    (83, '"bee.threads.service:inbox_accept"', '"bee.threads.binding:inbox_accept"'),
    (84, '"bee.threads.service:inbox_ack"', '"bee.threads.binding:inbox_ack"'),
    (85, '"bee.threads.service:inbox_describe"', '"bee.threads.binding:inbox_describe"'),
    (86, '"bee.threads.service:inbox_list"', '"bee.threads.binding:inbox_list"'),
    (87, '"bee.threads.service:inbox_offer"', '"bee.threads.binding:inbox_offer"'),
    (88, '"bee.threads.service:inbox_outbox_claim"', '"bee.threads.binding:inbox_outbox_claim"'),
    (89, '"bee.threads.service:inbox_outbox_settle"', '"bee.threads.binding:inbox_outbox_settle"'),
    (90, '"bee.threads.service:inbox_reply"', '"bee.threads.binding:inbox_reply"'),
    (91, '"bee.threads.service:inbox_resolve"', '"bee.threads.binding:inbox_resolve"'),
    (92, '"bee.threads.service:inbox_send"', '"bee.threads.binding:inbox_send"'),
    (93, '"bee.threads.service:inbox_transport"', '"bee.threads.binding:inbox_transport"'),
    (94, '"bee.threads.service:join"', '"bee.threads.binding:join"'),
    (95, '"bee.threads.service:leave"', '"bee.threads.binding:leave"'),
    (96, '"bee.threads.service:list"', '"bee.threads.binding:list"'),
    (97, '"bee.threads.service:list_workspace"', '"bee.threads.binding:list_workspace"'),
    (98, '"bee.threads.service:notify"', '"bee.threads.binding:notify"'),
    (99, '"bee.threads.service:operation_describe"', '"bee.threads.binding:operation_describe"'),
    (100, '"bee.threads.service:operation_lookup"', '"bee.threads.binding:operation_lookup"'),
    (101, '"bee.threads.service:prepare_attempt"', '"bee.threads.binding:prepare_attempt"'),
    (102, '"bee.threads.service:read_after"', '"bee.threads.binding:read_after"'),
    (103, '"bee.threads.service:receipt"', '"bee.threads.binding:receipt"'),
    (104, '"bee.threads.service:record"', '"bee.threads.binding:record"'),
    (105, '"bee.threads.service:register_app_alias"', '"bee.threads.binding:register_app_alias"'),
    (106, '"bee.threads.service:request_turn"', '"bee.threads.binding:request_turn"'),
    (107, '"bee.threads.service:retire_app_alias"', '"bee.threads.binding:retire_app_alias"'),
    (108, '"bee.threads.service:send"', '"bee.threads.binding:send"'),
    (109, '"bee.threads.service:send_status"', '"bee.threads.binding:send_status"'),
    (110, '"bee.threads.service:session_attach"', '"bee.threads.binding:session_attach"'),
    (111, '"bee.threads.service:session_create"', '"bee.threads.binding:session_create"'),
    (112, '"bee.threads.service:session_describe"', '"bee.threads.binding:session_describe"'),
    (113, '"bee.threads.service:session_scan"', '"bee.threads.binding:session_scan"'),
    (114, '"bee.threads.service:session_transition"', '"bee.threads.binding:session_transition"'),
    (115, '"bee.threads.service:start_attempt"', '"bee.threads.binding:start_attempt"'),
    (116, '"bee.threads.service:turn_accept"', '"bee.threads.binding:turn_accept"'),
    (117, '"bee.threads.service:turn_observation"', '"bee.threads.binding:turn_observation"'),
    (118, '"bee.threads.service:turn_pull"', '"bee.threads.binding:turn_pull"'),
    (119, '"bee.threads.service:turn_recover"', '"bee.threads.binding:turn_recover"'),
    (120, '"bee.threads.service:turn_reserve"', '"bee.threads.binding:turn_reserve"'),
    (121, '"bee.threads.service:types"', '"bee.threads:types"'),
    (122, '"bee.threads.service:work_cancel"', '"bee.threads.binding:work_cancel"'),
    (123, '"bee.threads.service:work_describe"', '"bee.threads.binding:work_describe"'),
    (124, '"bee.threads.service:work_history"', '"bee.threads.binding:work_history"'),
    (125, '"bee.threads.service:work_scan"', '"bee.threads.binding:work_scan"'),
    (126, '"bee.threads.service:work_send"', '"bee.threads.binding:work_send"'),
    (127, '"bee.threads.service:work_settle"', '"bee.threads.binding:work_settle"'),
    (128, '"bee.threads.service:work_uncertain"', '"bee.threads.binding:work_uncertain"'),
    (129, '"bee.threads:capabilities"', '"bee.threads.binding:capabilities"'),
    (130, '"bee.threads:owner"', '"bee.threads.service:owner"'),
    (131, '"bee.threads:owner_service"', '"bee.threads.service:owner_service"')),
  rewritten(position, value) AS (
    SELECT 0, payload_json
    UNION ALL
    SELECT identity_moves.position, replace(rewritten.value, identity_moves.prior, identity_moves.current)
    FROM rewritten JOIN identity_moves ON identity_moves.position = rewritten.position + 1
  )
  SELECT value FROM rewritten ORDER BY position DESC LIMIT 1
) WHERE json_valid(payload_json) AND (instr(payload_json, 'bee.driver.wippy') > 0 OR instr(payload_json, 'bee.gateway') > 0 OR instr(payload_json, 'bee.git.worktree') > 0 OR instr(payload_json, 'bee.git_worktree') > 0 OR instr(payload_json, 'bee.harness.carrier') > 0 OR instr(payload_json, 'bee.harness.launch') > 0 OR instr(payload_json, 'bee.harness.profiles') > 0 OR instr(payload_json, 'bee.hive') > 0 OR instr(payload_json, 'bee.hive.telemetry') > 0 OR instr(payload_json, 'bee.placement.native') > 0 OR instr(payload_json, 'bee.sync.hive') > 0 OR instr(payload_json, 'bee.threads') > 0 OR instr(payload_json, 'bee.threads.approvals') > 0 OR instr(payload_json, 'bee.threads.carrier') > 0 OR instr(payload_json, 'bee.threads.delivery') > 0 OR instr(payload_json, 'bee.threads.projection') > 0 OR instr(payload_json, 'bee.threads.records') > 0 OR instr(payload_json, 'bee.threads.service') > 0);
UPDATE bee_sync_receipts SET request_json = (
  WITH RECURSIVE identity_moves(position, prior, current) AS (VALUES
    (1, '"bee.driver.wippy:run"', '"bee.driver.wippy.binding:run"'),
    (2, '"bee.gateway:address"', '"bee.gateway.binding:address"'),
    (3, '"bee.git.worktree:cleanup"', '"bee.git.worktree.binding:cleanup"'),
    (4, '"bee.git.worktree:plan"', '"bee.git.worktree.binding:plan"'),
    (5, '"bee.git.worktree:setup"', '"bee.git.worktree.binding:setup"'),
    (6, '"bee.git_worktree"', '"bee.git.worktree"'),
    (7, '"bee.git_worktree:binding"', '"bee.git.worktree:binding"'),
    (8, '"bee.git_worktree:cleanup"', '"bee.git.worktree.binding:cleanup"'),
    (9, '"bee.git_worktree:definition"', '"bee.git.worktree:definition"'),
    (10, '"bee.git_worktree:dependency_driver"', '"bee.git.worktree:dependency_driver"'),
    (11, '"bee.git_worktree:dependency_placement"', '"bee.git.worktree:dependency_placement"'),
    (12, '"bee.git_worktree:dependency_threads"', '"bee.git.worktree:dependency_threads"'),
    (13, '"bee.git_worktree:executor_ref"', '"bee.git.worktree:executor_ref"'),
    (14, '"bee.git_worktree:git_executor"', '"bee.git.worktree:git_executor"'),
    (15, '"bee.git_worktree:git_roots"', '"bee.git.worktree:git_roots"'),
    (16, '"bee.git_worktree:host_files"', '"bee.git.worktree:host_files"'),
    (17, '"bee.git_worktree:host_files_ref"', '"bee.git.worktree:host_files_ref"'),
    (18, '"bee.git_worktree:plan"', '"bee.git.worktree.binding:plan"'),
    (19, '"bee.git_worktree:protected_namespace"', '"bee.git.worktree:protected_namespace"'),
    (20, '"bee.git_worktree:setup"', '"bee.git.worktree.binding:setup"'),
    (21, '"bee.git_worktree:target_executor"', '"bee.git.worktree:target_executor"'),
    (22, '"bee.git_worktree:target_host_files"', '"bee.git.worktree:target_host_files"'),
    (23, '"bee.git_worktree:worktree"', '"bee.git.worktree:worktree"'),
    (24, '"bee.git_worktree:worktree_policy"', '"bee.git.worktree:worktree_policy"'),
    (25, '"bee.harness.carrier:capabilities"', '"bee.harness.binding:capabilities"'),
    (26, '"bee.harness.carrier:process"', '"bee.harness.service:carrier"'),
    (27, '"bee.harness.carrier:types"', '"bee.harness:types"'),
    (28, '"bee.harness.launch:admit"', '"bee.harness.binding:admit"'),
    (29, '"bee.harness.launch:locate_probe"', '"bee.harness.binding:locate_probe"'),
    (30, '"bee.harness.launch:present"', '"bee.harness.binding:present"'),
    (31, '"bee.harness.launch:resolve"', '"bee.harness.binding:resolve"'),
    (32, '"bee.harness.launch:setup"', '"bee.harness.binding:setup"'),
    (33, '"bee.harness.launch:setup_backend"', '"bee.harness.binding:setup_backend"'),
    (34, '"bee.harness.launch:start"', '"bee.harness.binding:start"'),
    (35, '"bee.harness.profiles:call"', '"bee.harness.binding:call"'),
    (36, '"bee.harness.profiles:contract"', '"bee.harness:profiles"'),
    (37, '"bee.harness.profiles:local"', '"bee.harness:profiles_local"'),
    (38, '"bee.hive.telemetry:catalog_list"', '"bee.hive.telemetry.binding:catalog_list"'),
    (39, '"bee.hive.telemetry:cluster"', '"bee.hive.telemetry.binding:cluster"'),
    (40, '"bee.hive.telemetry:holdings"', '"bee.hive.telemetry.binding:holdings"'),
    (41, '"bee.hive.telemetry:presence"', '"bee.hive.telemetry.binding:presence"'),
    (42, '"bee.hive.telemetry:stats"', '"bee.hive.telemetry.binding:stats"'),
    (43, '"bee.hive:invoke_check"', '"bee.hive.binding:invoke_check"'),
    (44, '"bee.placement.native:process_runner"', '"bee.placement.native.service:process_runner"'),
    (45, '"bee.sync.hive:admit"', '"bee.sync.binding:admit"'),
    (46, '"bee.threads.approvals:append"', '"bee.threads.binding:append"'),
    (47, '"bee.threads.carrier:cancel_intent"', '"bee.threads.binding:cancel_intent"'),
    (48, '"bee.threads.carrier:cancel_status"', '"bee.threads.binding:cancel_status"'),
    (49, '"bee.threads.carrier:checkpoint"', '"bee.threads.binding:checkpoint"'),
    (50, '"bee.threads.carrier:claim"', '"bee.threads.binding:claim"'),
    (51, '"bee.threads.carrier:commit"', '"bee.threads.binding:commit"'),
    (52, '"bee.threads.delivery:ack"', '"bee.threads.binding:ack"'),
    (53, '"bee.threads.delivery:ack_page"', '"bee.threads.binding:ack_page"'),
    (54, '"bee.threads.delivery:claim"', '"bee.threads.binding:delivery_claim"'),
    (55, '"bee.threads.delivery:close_subscription"', '"bee.threads.binding:close_subscription"'),
    (56, '"bee.threads.delivery:dispatch"', '"bee.threads.binding:dispatch"'),
    (57, '"bee.threads.delivery:expire"', '"bee.threads.binding:expire"'),
    (58, '"bee.threads.delivery:forget_subscription"', '"bee.threads.binding:forget_subscription"'),
    (59, '"bee.threads.delivery:page"', '"bee.threads.binding:page"'),
    (60, '"bee.threads.delivery:reconcile"', '"bee.threads.binding:reconcile"'),
    (61, '"bee.threads.delivery:release"', '"bee.threads.binding:release"'),
    (62, '"bee.threads.delivery:resume"', '"bee.threads.binding:resume"'),
    (63, '"bee.threads.delivery:subscribe"', '"bee.threads.binding:subscribe"'),
    (64, '"bee.threads.delivery:unsubscribe"', '"bee.threads.binding:unsubscribe"'),
    (65, '"bee.threads.delivery:wait"', '"bee.threads.binding:wait"'),
    (66, '"bee.threads.delivery:waiter"', '"bee.threads.service:waiter"'),
    (67, '"bee.threads.delivery:waiter_service"', '"bee.threads.service:waiter_service"'),
    (68, '"bee.threads.delivery:watch"', '"bee.threads.binding:watch"'),
    (69, '"bee.threads.projection:recap_read"', '"bee.threads.binding:recap_read"'),
    (70, '"bee.threads.projection:recap_rebuild"', '"bee.threads.binding:recap_rebuild"'),
    (71, '"bee.threads.projection:recap_update"', '"bee.threads.binding:recap_update"'),
    (72, '"bee.threads.projection:status_read"', '"bee.threads.binding:status_read"'),
    (73, '"bee.threads.projection:status_rebuild"', '"bee.threads.binding:status_rebuild"'),
    (74, '"bee.threads.projection:status_update"', '"bee.threads.binding:status_update"'),
    (75, '"bee.threads.records:types"', '"bee.threads:record_types"'),
    (76, '"bee.threads.service:admit_action"', '"bee.threads.binding:admit_action"'),
    (77, '"bee.threads.service:close"', '"bee.threads.binding:close"'),
    (78, '"bee.threads.service:create"', '"bee.threads.binding:create"'),
    (79, '"bee.threads.service:end_turn"', '"bee.threads.binding:end_turn"'),
    (80, '"bee.threads.service:feed_read"', '"bee.threads.binding:feed_read"'),
    (81, '"bee.threads.service:fence_app"', '"bee.threads.binding:fence_app"'),
    (82, '"bee.threads.service:get"', '"bee.threads.binding:get"'),
    (83, '"bee.threads.service:inbox_accept"', '"bee.threads.binding:inbox_accept"'),
    (84, '"bee.threads.service:inbox_ack"', '"bee.threads.binding:inbox_ack"'),
    (85, '"bee.threads.service:inbox_describe"', '"bee.threads.binding:inbox_describe"'),
    (86, '"bee.threads.service:inbox_list"', '"bee.threads.binding:inbox_list"'),
    (87, '"bee.threads.service:inbox_offer"', '"bee.threads.binding:inbox_offer"'),
    (88, '"bee.threads.service:inbox_outbox_claim"', '"bee.threads.binding:inbox_outbox_claim"'),
    (89, '"bee.threads.service:inbox_outbox_settle"', '"bee.threads.binding:inbox_outbox_settle"'),
    (90, '"bee.threads.service:inbox_reply"', '"bee.threads.binding:inbox_reply"'),
    (91, '"bee.threads.service:inbox_resolve"', '"bee.threads.binding:inbox_resolve"'),
    (92, '"bee.threads.service:inbox_send"', '"bee.threads.binding:inbox_send"'),
    (93, '"bee.threads.service:inbox_transport"', '"bee.threads.binding:inbox_transport"'),
    (94, '"bee.threads.service:join"', '"bee.threads.binding:join"'),
    (95, '"bee.threads.service:leave"', '"bee.threads.binding:leave"'),
    (96, '"bee.threads.service:list"', '"bee.threads.binding:list"'),
    (97, '"bee.threads.service:list_workspace"', '"bee.threads.binding:list_workspace"'),
    (98, '"bee.threads.service:notify"', '"bee.threads.binding:notify"'),
    (99, '"bee.threads.service:operation_describe"', '"bee.threads.binding:operation_describe"'),
    (100, '"bee.threads.service:operation_lookup"', '"bee.threads.binding:operation_lookup"'),
    (101, '"bee.threads.service:prepare_attempt"', '"bee.threads.binding:prepare_attempt"'),
    (102, '"bee.threads.service:read_after"', '"bee.threads.binding:read_after"'),
    (103, '"bee.threads.service:receipt"', '"bee.threads.binding:receipt"'),
    (104, '"bee.threads.service:record"', '"bee.threads.binding:record"'),
    (105, '"bee.threads.service:register_app_alias"', '"bee.threads.binding:register_app_alias"'),
    (106, '"bee.threads.service:request_turn"', '"bee.threads.binding:request_turn"'),
    (107, '"bee.threads.service:retire_app_alias"', '"bee.threads.binding:retire_app_alias"'),
    (108, '"bee.threads.service:send"', '"bee.threads.binding:send"'),
    (109, '"bee.threads.service:send_status"', '"bee.threads.binding:send_status"'),
    (110, '"bee.threads.service:session_attach"', '"bee.threads.binding:session_attach"'),
    (111, '"bee.threads.service:session_create"', '"bee.threads.binding:session_create"'),
    (112, '"bee.threads.service:session_describe"', '"bee.threads.binding:session_describe"'),
    (113, '"bee.threads.service:session_scan"', '"bee.threads.binding:session_scan"'),
    (114, '"bee.threads.service:session_transition"', '"bee.threads.binding:session_transition"'),
    (115, '"bee.threads.service:start_attempt"', '"bee.threads.binding:start_attempt"'),
    (116, '"bee.threads.service:turn_accept"', '"bee.threads.binding:turn_accept"'),
    (117, '"bee.threads.service:turn_observation"', '"bee.threads.binding:turn_observation"'),
    (118, '"bee.threads.service:turn_pull"', '"bee.threads.binding:turn_pull"'),
    (119, '"bee.threads.service:turn_recover"', '"bee.threads.binding:turn_recover"'),
    (120, '"bee.threads.service:turn_reserve"', '"bee.threads.binding:turn_reserve"'),
    (121, '"bee.threads.service:types"', '"bee.threads:types"'),
    (122, '"bee.threads.service:work_cancel"', '"bee.threads.binding:work_cancel"'),
    (123, '"bee.threads.service:work_describe"', '"bee.threads.binding:work_describe"'),
    (124, '"bee.threads.service:work_history"', '"bee.threads.binding:work_history"'),
    (125, '"bee.threads.service:work_scan"', '"bee.threads.binding:work_scan"'),
    (126, '"bee.threads.service:work_send"', '"bee.threads.binding:work_send"'),
    (127, '"bee.threads.service:work_settle"', '"bee.threads.binding:work_settle"'),
    (128, '"bee.threads.service:work_uncertain"', '"bee.threads.binding:work_uncertain"'),
    (129, '"bee.threads:capabilities"', '"bee.threads.binding:capabilities"'),
    (130, '"bee.threads:owner"', '"bee.threads.service:owner"'),
    (131, '"bee.threads:owner_service"', '"bee.threads.service:owner_service"')),
  rewritten(position, value) AS (
    SELECT 0, request_json
    UNION ALL
    SELECT identity_moves.position, replace(rewritten.value, identity_moves.prior, identity_moves.current)
    FROM rewritten JOIN identity_moves ON identity_moves.position = rewritten.position + 1
  )
  SELECT value FROM rewritten ORDER BY position DESC LIMIT 1
) WHERE json_valid(request_json) AND (instr(request_json, 'bee.driver.wippy') > 0 OR instr(request_json, 'bee.gateway') > 0 OR instr(request_json, 'bee.git.worktree') > 0 OR instr(request_json, 'bee.git_worktree') > 0 OR instr(request_json, 'bee.harness.carrier') > 0 OR instr(request_json, 'bee.harness.launch') > 0 OR instr(request_json, 'bee.harness.profiles') > 0 OR instr(request_json, 'bee.hive') > 0 OR instr(request_json, 'bee.hive.telemetry') > 0 OR instr(request_json, 'bee.placement.native') > 0 OR instr(request_json, 'bee.sync.hive') > 0 OR instr(request_json, 'bee.threads') > 0 OR instr(request_json, 'bee.threads.approvals') > 0 OR instr(request_json, 'bee.threads.carrier') > 0 OR instr(request_json, 'bee.threads.delivery') > 0 OR instr(request_json, 'bee.threads.projection') > 0 OR instr(request_json, 'bee.threads.records') > 0 OR instr(request_json, 'bee.threads.service') > 0);
]]
function M.all(): {Migration}
    return {{id = 1, name = "owner_local_feed", sql = INITIAL, rebuild = false},
        {id = 2, name = "source_qualified_version_replicas", rebuild = false, sql = [[
CREATE TABLE bee_sync_replica_sources (
  source_owner TEXT NOT NULL,
  feed TEXT NOT NULL,
  cursor INTEGER NOT NULL CHECK(cursor >= 0),
  PRIMARY KEY(source_owner, feed)
);
CREATE TABLE bee_sync_replica_versions (
  source_owner TEXT NOT NULL,
  feed TEXT NOT NULL,
  version_key TEXT NOT NULL,
  descriptor_digest TEXT NOT NULL CHECK(length(descriptor_digest) = 64),
  descriptor_json TEXT NOT NULL CHECK(length(CAST(descriptor_json AS BLOB)) <= 16384),
  PRIMARY KEY(source_owner, feed, version_key),
  FOREIGN KEY(source_owner, feed) REFERENCES bee_sync_replica_sources(source_owner, feed)
);
]]},
        {id = 3, name = "resumable_replica_content", rebuild = false, sql = [[
CREATE TABLE bee_sync_replica_transfers (
  source_owner TEXT NOT NULL,
  feed TEXT NOT NULL,
  version_key TEXT NOT NULL,
  descriptor_digest TEXT NOT NULL CHECK(length(descriptor_digest) = 64),
  descriptor_json TEXT NOT NULL CHECK(length(CAST(descriptor_json AS BLOB)) <= 16384),
  content_digest TEXT NOT NULL CHECK(length(content_digest) = 64),
  total_bytes INTEGER NOT NULL CHECK(total_bytes BETWEEN 0 AND 16777216),
  received_bytes INTEGER NOT NULL CHECK(received_bytes BETWEEN 0 AND total_bytes),
  source_cursor INTEGER NOT NULL CHECK(source_cursor >= 0),
  state TEXT NOT NULL CHECK(state IN ('receiving', 'available')),
  PRIMARY KEY(source_owner, feed, version_key),
  FOREIGN KEY(source_owner, feed) REFERENCES bee_sync_replica_sources(source_owner, feed)
);
CREATE TABLE bee_sync_replica_chunks (
  source_owner TEXT NOT NULL,
  feed TEXT NOT NULL,
  version_key TEXT NOT NULL,
  byte_offset INTEGER NOT NULL CHECK(byte_offset >= 0),
  byte_count INTEGER NOT NULL CHECK(byte_count BETWEEN 0 AND 32768),
  content_sha256 TEXT NOT NULL CHECK(length(content_sha256) = 64),
  content_base64 TEXT NOT NULL CHECK(length(CAST(content_base64 AS BLOB)) <= 43692),
  PRIMARY KEY(source_owner, feed, version_key, byte_offset),
  FOREIGN KEY(source_owner, feed, version_key)
    REFERENCES bee_sync_replica_transfers(source_owner, feed, version_key)
);
CREATE INDEX bee_sync_replica_chunks_order
  ON bee_sync_replica_chunks(source_owner, feed, version_key, byte_offset);
]]},
        {id = 4, name = "destination_distribution_cursors", rebuild = false, sql = [[
CREATE TABLE bee_sync_distribution_cursors (
  source_owner TEXT NOT NULL,
  feed TEXT NOT NULL,
  destination_node TEXT NOT NULL,
  cursor INTEGER NOT NULL CHECK(cursor >= 0),
  PRIMARY KEY(source_owner, feed, destination_node)
);
]]},
        {id = 5, name = "owner_projection_data_migrations", rebuild = false, sql = [[
CREATE TABLE bee_sync_projection_migrations (
  owner_id TEXT NOT NULL,
  prefix TEXT NOT NULL,
  migration_id TEXT NOT NULL,
  completed_at TEXT NOT NULL,
  PRIMARY KEY(owner_id, prefix, migration_id)
);
]]},
        {id = 6, name = "projection_migration_diagnostics", rebuild = true, sql = [[
CREATE TABLE bee_sync_projections_next (
  owner_id TEXT NOT NULL,
  feed TEXT NOT NULL,
  projection_key TEXT NOT NULL,
  revision INTEGER NOT NULL CHECK(revision > 0),
  value_json TEXT,
  tombstone INTEGER NOT NULL CHECK(tombstone IN (0,1)),
  last_sequence INTEGER NOT NULL CHECK(last_sequence > 0),
  updated_at TEXT NOT NULL,
  PRIMARY KEY(owner_id, feed, projection_key),
  FOREIGN KEY(owner_id, feed) REFERENCES bee_sync_feeds(owner_id, feed),
  CHECK((tombstone = 1 AND value_json IS NULL) OR (tombstone = 0 AND value_json IS NOT NULL)),
  CHECK(value_json IS NULL OR length(CAST(value_json AS BLOB)) <= 65536)
);
INSERT INTO bee_sync_projections_next SELECT * FROM bee_sync_projections;
DROP TABLE bee_sync_projections;
ALTER TABLE bee_sync_projections_next RENAME TO bee_sync_projections;
CREATE INDEX bee_sync_projection_snapshot ON bee_sync_projections(owner_id, feed, projection_key);
]]},
        {id = 7, name = "app_sdk_references", rebuild = false, sql = [[
UPDATE bee_sync_projections SET value_json = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(value_json, '"bee.application:definition"', '"bee.app:definition"'), '"bee.application:dependency_threads"', '"bee.app:dependency_threads"'), '"bee.application:client"', '"bee.app:client"'), '"bee.application:sessions_protocol"', '"bee.app:sessions_protocol"'), '"bee.application:sessions"', '"bee.app:sessions"'), '"bee.application:arguments"', '"bee.app:arguments"'), '"bee.application:text"', '"bee.app:text"'), '"bee.application:caller"', '"bee.app:caller"'), '"bee.application:folder_picker"', '"bee.app:folder_picker"'), '"bee.application:agent_protocol"', '"bee.app:agent_protocol"'), '"bee.application:host_leases"', '"bee.app:host_leases"'), '"bee.application:status_reader"', '"bee.app:status_reader"'), '"bee.application:status_surface"', '"bee.app:status_surface"'), '"bee.application:interaction"', '"bee.app:interaction"'), '"bee.application:appearance"', '"bee.app:appearance"'), '"bee.application:frame"', '"bee.app:frame"'), '"bee.application:names"', '"bee.app:names"'), '"bee.application:thread_protocol"', '"bee.app:thread_protocol"'), '"bee.application:viz"', '"bee.app:viz"'), '"bee.application:forms"', '"bee.app:forms"'), '"bee.application:diagram"', '"bee.app:diagram"'), '"bee.application:runtime"', '"bee.app:runtime"') WHERE instr(value_json, 'bee.application:') > 0;
UPDATE bee_sync_events SET payload_json = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(payload_json, '"bee.application:definition"', '"bee.app:definition"'), '"bee.application:dependency_threads"', '"bee.app:dependency_threads"'), '"bee.application:client"', '"bee.app:client"'), '"bee.application:sessions_protocol"', '"bee.app:sessions_protocol"'), '"bee.application:sessions"', '"bee.app:sessions"'), '"bee.application:arguments"', '"bee.app:arguments"'), '"bee.application:text"', '"bee.app:text"'), '"bee.application:caller"', '"bee.app:caller"'), '"bee.application:folder_picker"', '"bee.app:folder_picker"'), '"bee.application:agent_protocol"', '"bee.app:agent_protocol"'), '"bee.application:host_leases"', '"bee.app:host_leases"'), '"bee.application:status_reader"', '"bee.app:status_reader"'), '"bee.application:status_surface"', '"bee.app:status_surface"'), '"bee.application:interaction"', '"bee.app:interaction"'), '"bee.application:appearance"', '"bee.app:appearance"'), '"bee.application:frame"', '"bee.app:frame"'), '"bee.application:names"', '"bee.app:names"'), '"bee.application:thread_protocol"', '"bee.app:thread_protocol"'), '"bee.application:viz"', '"bee.app:viz"'), '"bee.application:forms"', '"bee.app:forms"'), '"bee.application:diagram"', '"bee.app:diagram"'), '"bee.application:runtime"', '"bee.app:runtime"') WHERE instr(payload_json, 'bee.application:') > 0;
UPDATE bee_sync_receipts SET request_json = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(request_json, '"bee.application:definition"', '"bee.app:definition"'), '"bee.application:dependency_threads"', '"bee.app:dependency_threads"'), '"bee.application:client"', '"bee.app:client"'), '"bee.application:sessions_protocol"', '"bee.app:sessions_protocol"'), '"bee.application:sessions"', '"bee.app:sessions"'), '"bee.application:arguments"', '"bee.app:arguments"'), '"bee.application:text"', '"bee.app:text"'), '"bee.application:caller"', '"bee.app:caller"'), '"bee.application:folder_picker"', '"bee.app:folder_picker"'), '"bee.application:agent_protocol"', '"bee.app:agent_protocol"'), '"bee.application:host_leases"', '"bee.app:host_leases"'), '"bee.application:status_reader"', '"bee.app:status_reader"'), '"bee.application:status_surface"', '"bee.app:status_surface"'), '"bee.application:interaction"', '"bee.app:interaction"'), '"bee.application:appearance"', '"bee.app:appearance"'), '"bee.application:frame"', '"bee.app:frame"'), '"bee.application:names"', '"bee.app:names"'), '"bee.application:thread_protocol"', '"bee.app:thread_protocol"'), '"bee.application:viz"', '"bee.app:viz"'), '"bee.application:forms"', '"bee.app:forms"'), '"bee.application:diagram"', '"bee.app:diagram"'), '"bee.application:runtime"', '"bee.app:runtime"') WHERE instr(request_json, 'bee.application:') > 0;
]]},
        {id = 8, name = "layout_registry_references", sql = LAYOUT_REFERENCES_SQL, rebuild = false}}
end
return M
