-- MIT. Complete the governance store to its full schema: leases, plan selection and approval binding, application admission and the activation slot.
-- Tables whose definition changes are rebuilt with their rows; foreign keys
-- are checked when the migration commits.
local STATEMENTS = {
    [[PRAGMA defer_foreign_keys = ON]],
    [[CREATE TABLE bee_governance_plans_next ( owner_node TEXT NOT NULL, workspace_id TEXT NOT NULL, source_node TEXT NOT NULL, source_workspace TEXT NOT NULL, version TEXT NOT NULL, candidate_bytes BLOB NOT NULL CHECK(length(CAST(candidate_bytes AS BLOB)) BETWEEN 1 AND 1048576), candidate_digest TEXT NOT NULL CHECK(length(candidate_digest) = 64), artifact_bytes BLOB NOT NULL CHECK(length(CAST(artifact_bytes AS BLOB)) BETWEEN 1 AND 262144), artifact_digest TEXT NOT NULL CHECK(length(artifact_digest) = 64), preflight_bytes BLOB NOT NULL CHECK(length(CAST(preflight_bytes AS BLOB)) BETWEEN 1 AND 131072), preflight_digest TEXT NOT NULL CHECK(length(preflight_digest) = 64), plan_digest TEXT NOT NULL CHECK(length(plan_digest) = 64), revision INTEGER NOT NULL CHECK(revision >= 1), status TEXT NOT NULL CHECK(status IN ('staged', 'reviewed', 'rejected', 'approval_bound')), review_status TEXT, review_reason TEXT CHECK(review_reason IS NULL OR length(CAST(review_reason AS BLOB)) <= 8192), reviewer_id TEXT, approval_id TEXT, approval_digest TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, approval_proposal_digest TEXT CHECK(approval_proposal_digest IS NULL OR length(approval_proposal_digest) = 64), approval_owner_incarnation INTEGER CHECK(approval_owner_incarnation IS NULL OR approval_owner_incarnation >= 1), identity_digest_owner_node TEXT NOT NULL DEFAULT '', identity_digest_source_node TEXT NOT NULL DEFAULT '', PRIMARY KEY(owner_node, workspace_id, source_node, source_workspace, version), CHECK((status IN ('reviewed', 'rejected', 'approval_bound')) = (review_status IS NOT NULL)), CHECK(review_status IS NULL OR review_status IN ('accepted', 'rejected')), CHECK((status = 'approval_bound') = (approval_id IS NOT NULL)), CHECK(approval_digest IS NULL OR length(approval_digest) = 64) )]],
    [[INSERT INTO bee_governance_plans_next (owner_node, workspace_id, source_node, source_workspace, version, candidate_bytes, candidate_digest, artifact_bytes, artifact_digest, preflight_bytes, preflight_digest, plan_digest, revision, status, review_status, review_reason, reviewer_id, created_at, updated_at) SELECT owner_node, workspace_id, source_node, source_workspace, version, candidate_bytes, candidate_digest, artifact_bytes, artifact_digest, preflight_bytes, preflight_digest, plan_digest, revision, status, review_status, review_reason, reviewer_id, created_at, updated_at FROM bee_governance_plans]],
    [[DROP TABLE bee_governance_plans]],
    [[ALTER TABLE bee_governance_plans_next RENAME TO bee_governance_plans]],
    [[CREATE TABLE bee_governance_plan_selection ( owner_node TEXT NOT NULL, workspace_id TEXT NOT NULL, source_node TEXT NOT NULL, source_workspace TEXT NOT NULL, version TEXT NOT NULL, plan_revision INTEGER NOT NULL CHECK(plan_revision >= 1), selected_by TEXT NOT NULL, selected_at TEXT NOT NULL, PRIMARY KEY(owner_node, workspace_id), FOREIGN KEY(owner_node, workspace_id, source_node, source_workspace, version) REFERENCES bee_governance_plans(owner_node, workspace_id, source_node, source_workspace, version) )]],
    [[CREATE TABLE bee_governance_plan_receipts_next ( owner_node TEXT NOT NULL, workspace_id TEXT NOT NULL, idempotency_key TEXT NOT NULL, actor_id TEXT NOT NULL, operation TEXT NOT NULL CHECK(operation IN ('stage', 'record_review', 'select', 'bind_approval')), request_digest TEXT NOT NULL CHECK(length(request_digest) = 64), source_node TEXT NOT NULL, source_workspace TEXT NOT NULL, version TEXT NOT NULL, result_revision INTEGER NOT NULL CHECK(result_revision >= 1), PRIMARY KEY(owner_node, workspace_id, idempotency_key), FOREIGN KEY(owner_node, workspace_id, source_node, source_workspace, version) REFERENCES bee_governance_plans(owner_node, workspace_id, source_node, source_workspace, version) )]],
    [[INSERT INTO bee_governance_plan_receipts_next (owner_node, workspace_id, idempotency_key, actor_id, operation, request_digest, source_node, source_workspace, version, result_revision) SELECT owner_node, workspace_id, idempotency_key, actor_id, operation, request_digest, source_node, source_workspace, version, result_revision FROM bee_governance_plan_receipts]],
    [[DROP TABLE bee_governance_plan_receipts]],
    [[ALTER TABLE bee_governance_plan_receipts_next RENAME TO bee_governance_plan_receipts]],
    [[CREATE TABLE bee_governance_activation_intents_next ( owner_node TEXT NOT NULL, workspace_id TEXT NOT NULL, intent_id TEXT NOT NULL, actor_id TEXT NOT NULL, overlay_owner TEXT NOT NULL, source_node TEXT NOT NULL, source_workspace TEXT NOT NULL, version TEXT NOT NULL, plan_digest TEXT NOT NULL CHECK(length(plan_digest) = 64), plan_revision INTEGER NOT NULL CHECK(plan_revision >= 1), selection_revision INTEGER NOT NULL CHECK(selection_revision >= 1), artifact_bytes BLOB NOT NULL CHECK(length(CAST(artifact_bytes AS BLOB)) BETWEEN 1 AND 262144), artifact_digest TEXT NOT NULL CHECK(length(artifact_digest) = 64), resolution_bytes BLOB NOT NULL CHECK(length(CAST(resolution_bytes AS BLOB)) BETWEEN 1 AND 1048576), resolution_digest TEXT NOT NULL CHECK(length(resolution_digest) = 64), preflight_bytes BLOB NOT NULL CHECK(length(CAST(preflight_bytes AS BLOB)) BETWEEN 1 AND 131072), preflight_digest TEXT NOT NULL CHECK(length(preflight_digest) = 64), authorization_digest TEXT NOT NULL CHECK(length(authorization_digest) = 64), effect_key TEXT NOT NULL CHECK(length(effect_key) = 64), created_at TEXT NOT NULL, migration_work_bytes BLOB CHECK(migration_work_bytes IS NULL OR length(CAST(migration_work_bytes AS BLOB)) BETWEEN 1 AND 1048576), migration_work_digest TEXT CHECK(migration_work_digest IS NULL OR length(migration_work_digest) = 64), application_admission_bytes BLOB CHECK(application_admission_bytes IS NULL OR length(CAST(application_admission_bytes AS BLOB)) BETWEEN 1 AND 65536), application_admission_digest TEXT CHECK((application_admission_bytes IS NULL) = (application_admission_digest IS NULL)) CHECK(application_admission_digest IS NULL OR length(application_admission_digest) = 64), grant_predecessor_digest TEXT CHECK(grant_predecessor_digest IS NULL OR length(grant_predecessor_digest) = 64), application_admission_generation TEXT NOT NULL DEFAULT 'current' CHECK(application_admission_generation IN ('current', 'prior')), PRIMARY KEY(owner_node, workspace_id, intent_id), UNIQUE(owner_node, workspace_id, effect_key) )]],
    [[INSERT INTO bee_governance_activation_intents_next (owner_node, workspace_id, intent_id, actor_id, overlay_owner, source_node, source_workspace, version, plan_digest, plan_revision, selection_revision, artifact_bytes, artifact_digest, resolution_bytes, resolution_digest, preflight_bytes, preflight_digest, authorization_digest, effect_key, created_at, migration_work_bytes, migration_work_digest, grant_predecessor_digest) SELECT owner_node, workspace_id, intent_id, actor_id, overlay_owner, source_node, source_workspace, version, plan_digest, plan_revision, selection_revision, artifact_bytes, artifact_digest, resolution_bytes, resolution_digest, preflight_bytes, preflight_digest, authorization_digest, effect_key, created_at, migration_work_bytes, migration_work_digest, grant_predecessor_digest FROM bee_governance_activation_intents]],
    [[DROP TABLE bee_governance_activation_intents]],
    [[ALTER TABLE bee_governance_activation_intents_next RENAME TO bee_governance_activation_intents]],
    [[CREATE TABLE bee_governance_activation_execution_next ( owner_node TEXT NOT NULL, workspace_id TEXT NOT NULL, intent_id TEXT NOT NULL, revision INTEGER NOT NULL CHECK(revision >= 1), phase TEXT NOT NULL CHECK(phase IN ('prepared', 'approval_bound', 'consuming', 'authorized', 'applying', 'settled')), approval_id TEXT, approval_proposal_digest TEXT CHECK(approval_proposal_digest IS NULL OR length(approval_proposal_digest) = 64), approval_owner_incarnation INTEGER CHECK(approval_owner_incarnation IS NULL OR approval_owner_incarnation >= 1), consumed_consumer_id TEXT, consumed_proposal_digest TEXT CHECK(consumed_proposal_digest IS NULL OR length(consumed_proposal_digest) = 64), consumed_effect_key TEXT, outcome TEXT CHECK(outcome IS NULL OR outcome IN ('applied', 'blocked', 'failed', 'uncertain')), diagnostics TEXT CHECK(diagnostics IS NULL OR length(CAST(diagnostics AS BLOB)) <= 8192), updated_at TEXT NOT NULL, migrations_completed INTEGER NOT NULL DEFAULT 0 CHECK(migrations_completed IN (0, 1)), migration_receipt_bytes BLOB CHECK(migration_receipt_bytes IS NULL OR length(CAST(migration_receipt_bytes AS BLOB)) BETWEEN 1 AND 262144), migration_receipt_digest TEXT CHECK(migration_receipt_digest IS NULL OR length(migration_receipt_digest) = 64), grant_reuse_digest TEXT CHECK(grant_reuse_digest IS NULL OR length(grant_reuse_digest) = 64), PRIMARY KEY(owner_node, workspace_id, intent_id), FOREIGN KEY(owner_node, workspace_id, intent_id) REFERENCES bee_governance_activation_intents(owner_node, workspace_id, intent_id), CHECK((((phase IN ('approval_bound', 'consuming', 'authorized', 'applying', 'settled')) AND approval_id IS NOT NULL) OR ((phase = 'prepared') AND approval_id IS NULL))), CHECK((((phase IN ('authorized', 'applying', 'settled')) AND consumed_consumer_id IS NOT NULL AND consumed_proposal_digest IS NOT NULL AND consumed_effect_key IS NOT NULL) OR ((phase IN ('prepared', 'approval_bound', 'consuming')) AND consumed_consumer_id IS NULL AND consumed_proposal_digest IS NULL AND consumed_effect_key IS NULL))), CHECK(((phase = 'settled') AND outcome IS NOT NULL) OR ((phase <> 'settled') AND outcome IS NULL)) )]],
    [[INSERT INTO bee_governance_activation_execution_next (owner_node, workspace_id, intent_id, revision, phase, approval_id, approval_proposal_digest, approval_owner_incarnation, consumed_consumer_id, consumed_proposal_digest, consumed_effect_key, outcome, diagnostics, updated_at, migrations_completed, migration_receipt_bytes, migration_receipt_digest, grant_reuse_digest) SELECT owner_node, workspace_id, intent_id, revision, phase, approval_id, approval_proposal_digest, approval_owner_incarnation, consumed_consumer_id, consumed_proposal_digest, consumed_effect_key, outcome, diagnostics, updated_at, migrations_completed, migration_receipt_bytes, migration_receipt_digest, grant_reuse_digest FROM bee_governance_activation_execution]],
    [[DROP TABLE bee_governance_activation_execution]],
    [[ALTER TABLE bee_governance_activation_execution_next RENAME TO bee_governance_activation_execution]],
    [[CREATE TABLE bee_governance_activation_slot ( owner_node TEXT NOT NULL, workspace_id TEXT NOT NULL, revision INTEGER NOT NULL CHECK(revision >= 0), desired_intent_id TEXT, desired_execution_revision INTEGER CHECK(desired_execution_revision IS NULL OR desired_execution_revision >= 1), observed_intent_id TEXT, observed_execution_revision INTEGER CHECK(observed_execution_revision IS NULL OR observed_execution_revision >= 1), observed_artifact_digest TEXT CHECK(observed_artifact_digest IS NULL OR length(observed_artifact_digest) = 64), observed_outcome TEXT CHECK(observed_outcome IS NULL OR observed_outcome IN ('applied', 'blocked', 'failed', 'uncertain')), updated_at TEXT NOT NULL, PRIMARY KEY(owner_node, workspace_id), FOREIGN KEY(owner_node, workspace_id, desired_intent_id) REFERENCES bee_governance_activation_intents(owner_node, workspace_id, intent_id), FOREIGN KEY(owner_node, workspace_id, observed_intent_id) REFERENCES bee_governance_activation_intents(owner_node, workspace_id, intent_id), CHECK((desired_intent_id IS NULL) = (desired_execution_revision IS NULL)), CHECK((observed_intent_id IS NULL) = (observed_execution_revision IS NULL)) )]],
    [[CREATE TABLE bee_governance_activation_slots_next ( owner_node TEXT NOT NULL, workspace_id TEXT NOT NULL, overlay_owner TEXT NOT NULL, revision INTEGER NOT NULL CHECK(revision >= 0), desired_intent_id TEXT, desired_execution_revision INTEGER CHECK(desired_execution_revision IS NULL OR desired_execution_revision >= 1), observed_intent_id TEXT, observed_execution_revision INTEGER CHECK(observed_execution_revision IS NULL OR observed_execution_revision >= 1), observed_artifact_digest TEXT CHECK(observed_artifact_digest IS NULL OR length(observed_artifact_digest) = 64), observed_outcome TEXT CHECK(observed_outcome IS NULL OR observed_outcome IN ('applied', 'blocked', 'failed', 'uncertain')), updated_at TEXT NOT NULL, baseline_intent_id TEXT, baseline_execution_revision INTEGER CHECK(baseline_execution_revision IS NULL OR baseline_execution_revision >= 1), baseline_artifact_digest TEXT CHECK(baseline_artifact_digest IS NULL OR length(baseline_artifact_digest) = 64), PRIMARY KEY(owner_node, workspace_id, overlay_owner), FOREIGN KEY(owner_node, workspace_id, desired_intent_id) REFERENCES bee_governance_activation_intents(owner_node, workspace_id, intent_id), FOREIGN KEY(owner_node, workspace_id, observed_intent_id) REFERENCES bee_governance_activation_intents(owner_node, workspace_id, intent_id), CHECK((desired_intent_id IS NULL) = (desired_execution_revision IS NULL)), CHECK((observed_intent_id IS NULL) = (observed_execution_revision IS NULL)) )]],
    [[INSERT INTO bee_governance_activation_slots_next (owner_node, workspace_id, overlay_owner, revision, desired_intent_id, desired_execution_revision, observed_intent_id, observed_execution_revision, observed_artifact_digest, observed_outcome, updated_at, baseline_intent_id, baseline_execution_revision, baseline_artifact_digest) SELECT owner_node, workspace_id, overlay_owner, revision, desired_intent_id, desired_execution_revision, observed_intent_id, observed_execution_revision, observed_artifact_digest, observed_outcome, updated_at, baseline_intent_id, baseline_execution_revision, baseline_artifact_digest FROM bee_governance_activation_slots]],
    [[DROP TABLE bee_governance_activation_slots]],
    [[ALTER TABLE bee_governance_activation_slots_next RENAME TO bee_governance_activation_slots]],
    [[CREATE TABLE bee_governance_receipts_next ( owner_node TEXT NOT NULL, workspace_id TEXT NOT NULL, idempotency_key TEXT NOT NULL, actor_id TEXT NOT NULL, operation TEXT NOT NULL, expected_revision INTEGER NOT NULL CHECK(expected_revision >= 0), path TEXT, content_sha256 TEXT, result_revision INTEGER NOT NULL CHECK(result_revision >= 1), snapshot_digest TEXT, files_digest TEXT, file_count INTEGER, total_bytes INTEGER, PRIMARY KEY(owner_node, workspace_id, idempotency_key), FOREIGN KEY(owner_node, workspace_id) REFERENCES bee_governance_workspaces(owner_node, workspace_id), CHECK(operation IN ('create', 'put', 'append', 'remove', 'freeze')), CHECK((operation IN ('put', 'append') AND path IS NOT NULL AND content_sha256 IS NOT NULL) OR (operation = 'remove' AND path IS NOT NULL AND content_sha256 IS NULL) OR (operation IN ('create', 'freeze') AND path IS NULL AND content_sha256 IS NULL)), CHECK((operation = 'freeze' AND snapshot_digest IS NOT NULL AND files_digest IS NOT NULL AND file_count IS NOT NULL AND total_bytes IS NOT NULL) OR (operation <> 'freeze' AND snapshot_digest IS NULL AND files_digest IS NULL AND file_count IS NULL AND total_bytes IS NULL)) )]],
    [[INSERT INTO bee_governance_receipts_next (owner_node, workspace_id, idempotency_key, actor_id, operation, expected_revision, path, content_sha256, result_revision, snapshot_digest, files_digest, file_count, total_bytes) SELECT owner_node, workspace_id, idempotency_key, actor_id, operation, expected_revision, path, content_sha256, result_revision, snapshot_digest, files_digest, file_count, total_bytes FROM bee_governance_receipts]],
    [[DROP TABLE bee_governance_receipts]],
    [[ALTER TABLE bee_governance_receipts_next RENAME TO bee_governance_receipts]],
    [[CREATE TABLE bee_governance_activation_receipts_next ( owner_node TEXT NOT NULL, workspace_id TEXT NOT NULL, idempotency_key TEXT NOT NULL, actor_id TEXT NOT NULL, operation TEXT NOT NULL CHECK(operation IN ('prepare_activation', 'bind_approval', 'begin_consume', 'record_consumption', 'begin_apply', 'record_migrations', 'record_outcome', 'revert_activation')), request_digest TEXT NOT NULL CHECK(length(request_digest) = 64), intent_id TEXT NOT NULL, result_revision INTEGER NOT NULL CHECK(result_revision >= 1), PRIMARY KEY(owner_node, workspace_id, idempotency_key), FOREIGN KEY(owner_node, workspace_id, intent_id) REFERENCES bee_governance_activation_intents(owner_node, workspace_id, intent_id) )]],
    [[INSERT INTO bee_governance_activation_receipts_next (owner_node, workspace_id, idempotency_key, actor_id, operation, request_digest, intent_id, result_revision) SELECT owner_node, workspace_id, idempotency_key, actor_id, operation, request_digest, intent_id, result_revision FROM bee_governance_activation_receipts]],
    [[DROP TABLE bee_governance_activation_receipts]],
    [[ALTER TABLE bee_governance_activation_receipts_next RENAME TO bee_governance_activation_receipts]],
    [[CREATE TABLE bee_governance_leases ( owner_node TEXT NOT NULL, workspace_id TEXT NOT NULL, lease_id TEXT NOT NULL, target TEXT NOT NULL, envelope_bytes BLOB NOT NULL CHECK(length(CAST(envelope_bytes AS BLOB)) BETWEEN 1 AND 65536), envelope_digest TEXT NOT NULL CHECK(length(envelope_digest) = 64), source_approval_id TEXT NOT NULL, source_approval_proposal_digest TEXT NOT NULL CHECK(length(source_approval_proposal_digest) = 64), source_approval_owner_incarnation INTEGER NOT NULL CHECK(source_approval_owner_incarnation >= 1), granted_by TEXT NOT NULL, created_at TEXT NOT NULL, expires_at TEXT, max_applies INTEGER CHECK(max_applies IS NULL OR max_applies >= 1), applies_used INTEGER NOT NULL DEFAULT 0 CHECK(applies_used >= 0), revision INTEGER NOT NULL CHECK(revision >= 1), state TEXT NOT NULL CHECK(state IN ('active', 'revoked')), revoked_by TEXT, revoked_at TEXT, PRIMARY KEY(owner_node, workspace_id, lease_id), UNIQUE(owner_node, workspace_id, source_approval_id), CHECK(expires_at IS NOT NULL OR max_applies IS NOT NULL) )]],
    [[CREATE TABLE bee_governance_lease_receipts ( owner_node TEXT NOT NULL, workspace_id TEXT NOT NULL, idempotency_key TEXT NOT NULL, actor_id TEXT NOT NULL, operation TEXT NOT NULL CHECK(operation IN ('grant', 'use', 'revoke')), request_digest TEXT NOT NULL CHECK(length(request_digest) = 64), lease_id TEXT NOT NULL, result_revision INTEGER NOT NULL CHECK(result_revision >= 1), result_json TEXT, PRIMARY KEY(owner_node, workspace_id, idempotency_key) )]],
    [[CREATE TABLE "bee_governance_lease_uses" ( owner_node TEXT NOT NULL, workspace_id TEXT NOT NULL, lease_id TEXT NOT NULL, intent_id TEXT NOT NULL, approval_id TEXT NOT NULL, approval_proposal_digest TEXT NOT NULL CHECK(length(approval_proposal_digest) = 64), proposal_snapshot_bytes BLOB NOT NULL CHECK(length(CAST(proposal_snapshot_bytes AS BLOB)) BETWEEN 1 AND 65536), proposal_snapshot_digest TEXT NOT NULL CHECK(length(proposal_snapshot_digest) = 64), state TEXT NOT NULL CHECK(state IN ('reserved', 'admitted', 'fenced')), applied_at TEXT NOT NULL, admitted_at TEXT, PRIMARY KEY(owner_node, workspace_id, lease_id, intent_id), UNIQUE(owner_node, workspace_id, intent_id), FOREIGN KEY(owner_node, workspace_id, lease_id) REFERENCES bee_governance_leases(owner_node, workspace_id, lease_id) )]],
    [[CREATE INDEX IF NOT EXISTS bee_governance_workspaces_node ON bee_governance_workspaces(owner_node)]],
    [[CREATE INDEX IF NOT EXISTS bee_governance_workspace_files_list ON bee_governance_workspace_files(owner_node, workspace_id, path)]],
    [[CREATE INDEX IF NOT EXISTS bee_governance_plans_list ON bee_governance_plans(owner_node, workspace_id, source_node, source_workspace, version)]],
    [[CREATE INDEX IF NOT EXISTS bee_governance_plans_status ON bee_governance_plans(owner_node, workspace_id, status)]],
    [[CREATE INDEX IF NOT EXISTS bee_governance_activation_phase ON bee_governance_activation_execution(owner_node, workspace_id, phase)]],
    [[CREATE INDEX IF NOT EXISTS bee_governance_activation_slots_workspace ON bee_governance_activation_slots(owner_node, workspace_id, overlay_owner)]],
    [[CREATE INDEX IF NOT EXISTS bee_governance_applied_migrations_component ON bee_governance_applied_migrations(owner_node, workspace_id, component, target_db, ordinal)]],
    [[CREATE INDEX IF NOT EXISTS bee_governance_leases_target ON bee_governance_leases (owner_node, workspace_id, target, state)]],
}

return require("migration").define(function()
    migration("Complete the governance store to its full schema: leases, plan selection and approval binding, application admission and the activation slot", function()
        database("sqlite", function()
            up(function(db)
                for _, statement in ipairs(STATEMENTS) do
                    local _, err = db:execute(statement)
                    if err then error(err) end
                end
            end)
        end)
    end)
end)
