local test = require("test")
local confirmation = require("confirmation")
local fixture = require("fixture")
local dialog = require("dialog")
local bounds = require("bounds")
local function define_tests()
    test.describe("Shared confirmation presentation", function()
        test.it("records each inline keyboard gesture once and withdraws Escape", function()
            for _, action in ipairs({"library.review", "library.remove", "library.back", "hub.apply", "hub.recover", "app.stop",
                "close", "close_listed", "stop", "profile.remove", "docker.revoke", "mcp.revoke", "login.acknowledge"}) do
                local records = fixture.new()
                local state = confirmation.new({workspace_id = "workspace", origin = {instance_id = "origin-instance"}},
                    function(target, request) return fixture.ask(records, target, request) end)
                local target = {instance_id = "target-instance", revision = 7}
                test.is_true(confirmation.open(state, action, target, "inline", action, "Review this exact instance"))
                test.eq(records.requests[1].presentation, "inline")
                test.is_true(confirmation.accept(state, target, confirmation.gesture({type = "key", key_type = "enter"})))
                test.eq(#records.decisions, 1)
                test.eq(fixture.gesture(records, 1), "enter")
                test.is_false(confirmation.accept(state, target, "enter"))
                test.eq(#records.decisions, 1)
                test.is_true(confirmation.open(state, action, target, "inline", action, "Review this exact instance"))
                test.is_true(confirmation.cancel(state))
                test.eq(records.withdrawals, 1)
                test.eq(#records.decisions, 1)
            end
        end)
        test.it("fences a replaced instance and does not record a decision", function()
            local records = fixture.new()
            local state = confirmation.new({workspace_id = "workspace", origin = {}}, function(target, request) return fixture.ask(records, target, request) end)
            test.is_true(confirmation.open(state, "app.stop", {instance_id = "original"}, "inline", "Stop?", "Stop this app"))
            test.is_false(confirmation.accept(state, {instance_id = "replacement"}, "enter"))
            test.eq(#records.decisions, 0)
            test.eq(records.withdrawals, 1)
        end)
        test.it("preserves the dialog's cancel focus and keyboard acceptance flow", function()
            local records = fixture.new()
            local state = confirmation.new({workspace_id = "workspace", origin = {}}, function(target, request) return fixture.ask(records, target, request) end)
            local target = {instance_id = "desktop-instance"}
            test.is_true(confirmation.open(state, "desktop.close", target, "dialog", "Close desktop", "Stop its apps?"))
            local shown = dialog.open({id = "desktop", kind = "confirm", title = "Close desktop", message = "Stop its apps?", accept = "Close", initial = ""})
            local key = {type = "key", action = "press", key_type = "enter", key = ""}
            test.eq(dialog.respond(shown, key, 80, 24).action, "cancel")
            test.is_true(confirmation.cancel(state))
            test.eq(#records.decisions, 0)
            test.is_true(confirmation.open(state, "desktop.close", target, "dialog", "Close desktop", "Stop its apps?"))
            shown = dialog.respond(shown, {type = "key", action = "press", key_type = "tab", key = ""}, 80, 24).state
            test.eq(dialog.respond(shown, key, 80, 24).action, "accept")
            test.is_true(confirmation.accept(state, target, confirmation.gesture(key)))
            test.eq(#records.decisions, 1)
            test.eq(assert(bounds.object(records.decisions[1].assurance)).presentation, "dialog")
        end)
    end)
end
return test.run_cases(define_tests)
