-- SPDX-License-Identifier: MIT
local test = require("test")
local process = require("process")
local events = require("events")
local system = require("system")
local channel = require("channel")
local time = require("time")
local host = require("host")
local SERVICE = "bee.gateway.service:access_service"
local function define_tests()
    test.describe("Approval effect lifecycle", function()
        test.it("completes consent when its first consumer exits before readiness", function()
            local updates = assert(events.subscribe("supervisor", "service.update"))
            local held = assert(process.listen("bee.test.access.start", {message = true}))
            local deadline = time.after("25s")
            local function stopped()
                while true do
                    local current = assert(system.supervisor.state(SERVICE))
                    if current.status == "unknown" or (current.desired == "stopped" and (current.status == "stopped" or current.status == "exited")) then return end
                    local selected = channel.select({updates:channel():case_receive(), deadline:case_receive()})
                    assert(selected.channel ~= deadline, "access consumer did not stop")
                end
            end
            assert(events.send("supervisor", "service.stop", SERVICE))
            stopped()
            assert(process.registry.register("bee.test.access.start"))
            local finished = channel.new(1)
            coroutine.spawn(function()
                local ok, problem = pcall(host.open, true)
                finished:send({ok = ok, problem = tostring(problem)})
            end)
            local selected = channel.select({held:case_receive(), deadline:case_receive()})
            test.eq(selected.channel, held, "access consumer did not reach readiness barrier")
            local first = tostring(selected.value:from())
            test.eq(tostring(assert(process.registry.lookup("bee.gateway.access", process.registry.LOCAL))), first)
            process.registry.unregister("bee.test.access.start")
            assert(events.send("supervisor", "service.stop", SERVICE))
            selected = channel.select({finished:case_receive(), deadline:case_receive()})
            process.unlisten(held)
            updates:close()
            test.eq(selected.channel, finished, "approval effect did not complete after replacement")
            test.eq(selected.value.ok, true, selected.value.problem)
        end)
    end)
end
return test.run_cases(define_tests)
