-- MIT. The node host manager's decisions: a host starts on the first lease
-- for its workspace, stays live while any lease holds it, stops after its
-- idle period, and the least recently used idle host makes room at the cap.
local test = require("test")
local hosts = require("hosts")
local leases = require("leases")

local A, B, C, D = string.rep("a", 32), string.rep("b", 32), string.rep("c", 32), string.rep("d", 32)

local function started(state: hosts.State, workspace_id: string, lease: string, holder: string, now: number)
    test.eq(hosts.acquire(state, workspace_id, lease, holder).kind, "start")
    hosts.started(state, workspace_id, "pid-" .. workspace_id:sub(1, 1))
    hosts.ready(state, workspace_id, now)
end

local function define_tests()
    test.describe("Node workspace hosts", function()
        test.it("starts a host on the first lease and serves later leases from it", function()
            local state = hosts.new(4, 10)
            test.eq(hosts.acquire(state, A, "lease-1", "holder-1").kind, "start")
            test.eq(hosts.acquire(state, A, "lease-2", "holder-2").kind, "wait")
            hosts.started(state, A, "pid-a")
            hosts.ready(state, A, 0)
            test.eq(hosts.acquire(state, A, "lease-3", "holder-3").kind, "ready")
            local host = hosts.host(state, A)
            if not host then error("host") end
            test.eq(host.lease_count, 3)
            test.eq(host.pid, "pid-a")
            test.is_nil(hosts.next_deadline(state))
        end)

        test.it("stops a host only after its last lease has been released for the idle period", function()
            local state = hosts.new(4, 10)
            started(state, A, "lease-1", "holder-1", 0)
            test.eq(hosts.acquire(state, A, "lease-2", "holder-2").kind, "ready")
            test.eq(hosts.release(state, "lease-1", 5), A)
            test.is_nil(hosts.next_deadline(state))
            test.eq(#hosts.due(state, 100), 0)
            hosts.release(state, "lease-2", 20)
            test.eq(hosts.next_deadline(state), 30)
            test.eq(#hosts.due(state, 29), 0)
            local due = hosts.due(state, 30)
            test.eq(#due, 1)
            test.eq(due[1], A)
            test.eq(hosts.acquire(state, A, "lease-3", "holder-3").kind, "stopping")
            hosts.gone(state, A)
            test.eq(hosts.acquire(state, A, "lease-3", "holder-3").kind, "start")
        end)

        test.it("cancels the idle period when a new lease arrives", function()
            local state = hosts.new(4, 10)
            started(state, A, "lease-1", "holder-1", 0)
            hosts.release(state, "lease-1", 1)
            test.eq(hosts.next_deadline(state), 11)
            test.eq(hosts.acquire(state, A, "lease-2", "holder-2").kind, "ready")
            test.is_nil(hosts.next_deadline(state))
            test.eq(#hosts.due(state, 50), 0)
        end)

        test.it("makes room at the cap by stopping the least recently used idle host", function()
            local state = hosts.new(2, 60)
            started(state, A, "lease-a", "holder", 0)
            started(state, B, "lease-b", "holder", 1)
            test.eq(hosts.acquire(state, A, "lease-a2", "holder").kind, "ready")
            hosts.release(state, "lease-a", 2)
            hosts.release(state, "lease-a2", 2)
            hosts.release(state, "lease-b", 3)
            -- A was used after B, so B goes first even though it fell idle later.
            local decision = hosts.acquire(state, C, "lease-c", "holder")
            test.eq(decision.kind, "evict")
            test.eq(decision.evict, B)
            -- A second request while B stops needs its own slot: A is next.
            local second = hosts.acquire(state, D, "lease-d", "holder")
            test.eq(second.evict, A)
            test.eq(hosts.acquire(state, C, "lease-c", "holder").kind, "full")
            hosts.gone(state, B)
            test.eq(hosts.acquire(state, C, "lease-c", "holder").kind, "start")
            hosts.gone(state, A)
            test.eq(hosts.acquire(state, D, "lease-d", "holder").kind, "start")
            test.eq(state.live, 2)
        end)

        test.it("refuses a new host when every live host is leased", function()
            local state = hosts.new(1, 60)
            started(state, A, "lease-a", "holder", 0)
            test.eq(hosts.acquire(state, B, "lease-b", "holder").kind, "full")
            test.is_nil(hosts.held(state, "lease-b"))
        end)

        test.it("ends every lease of a holder that exits", function()
            local state = hosts.new(4, 10)
            started(state, A, "lease-1", "holder-1", 0)
            started(state, B, "lease-2", "holder-1", 0)
            test.eq(hosts.acquire(state, B, "lease-3", "holder-2").kind, "ready")
            hosts.holder_exited(state, "holder-1", 4)
            test.is_nil(hosts.held(state, "lease-1"))
            test.is_nil(hosts.held(state, "lease-2"))
            test.eq(hosts.holder(state, "lease-3"), "holder-2")
            local due = hosts.due(state, 14)
            test.eq(#due, 1)
            test.eq(due[1], A)
        end)

        test.it("keeps a host whose stop was refused and never evicts it blindly", function()
            local state = hosts.new(1, 10)
            started(state, A, "lease-a", "holder", 0)
            hosts.release(state, "lease-a", 0)
            test.eq(hosts.due(state, 10)[1], A)
            hosts.stop_refused(state, A)
            test.eq(hosts.acquire(state, B, "lease-b", "holder").kind, "full")
            test.eq(#hosts.due(state, 1000), 0)
            test.eq(hosts.acquire(state, A, "lease-a2", "holder").kind, "ready")
            hosts.release(state, "lease-a2", 20)
            test.eq(hosts.due(state, 30)[1], A)
        end)

        test.it("starts the idle period of a host whose leases ended while it started", function()
            local state = hosts.new(4, 10)
            test.eq(hosts.acquire(state, A, "lease-1", "holder-1").kind, "start")
            hosts.release(state, "lease-1", 1)
            test.is_nil(hosts.next_deadline(state))
            hosts.ready(state, A, 2)
            test.eq(hosts.next_deadline(state), 12)
        end)

        test.it("decodes lease messages strictly", function()
            local request = leases.acquire_request({version = 1, request_id = "r1", workspace_id = A, lease = "bee.workspace.lease/0190-ab"})
            if not request then error("request") end
            test.eq(request.lease, "bee.workspace.lease/0190-ab")
            test.is_nil(leases.acquire_request({version = 1, request_id = "r1", workspace_id = A, lease = "bee.workspace.host/" .. A}))
            test.is_nil(leases.acquire_request({version = 1, request_id = "r1", workspace_id = "short", lease = "bee.workspace.lease/x"}))
            test.is_nil(leases.lease_name("bee.workspace.lease/"))
            test.is_nil(leases.lease_name("bee.workspace.lease/a/b"))
            test.is_nil(leases.result({version = 1, request_id = "r", workspace_id = A, host = "", managed = false, error_code = "", error = ""}))
            local failed = leases.result({version = 1, request_id = "r", workspace_id = A, host = "", managed = false, error_code = "busy", error = "full"})
            test.eq(failed and failed.error_code, "busy")
        end)
    end)
end

local cases = test.run_cases(define_tests)
return {run = function(options: unknown) return cases(options) end}
