-- MIT. Desktop attention is a read-only, exact-workspace grant.
local test = require("test")
local funcs = require("funcs")
local security = require("security")
local function define_tests()
    test.describe("Desktop attention grant", function()
        test.it("counts only the granted workspace and cannot read its requests", function()
            local workspace = string.rep("a", 32)
            local actor = assert(security.new_actor("bee.desktop/" .. workspace, {workspace_id = workspace}))
            local scope = security.new_scope({assert(security.policy("bee.approvals:attention_client_test_policy")),
                assert(security.policy("bee.security.desktop:presenter_policy"))})
            local client = funcs.new():with_actor(actor):with_scope(scope)
            local raw = assert(client:call("bee.approvals.binding:attention_count", {workspace_id = workspace}))
            test.is_true(raw.ok)
            test.eq(raw.value.count, 0)
            local other = assert(client:call("bee.approvals.binding:attention_count", {workspace_id = string.rep("b", 32)}))
            test.is_false(other.ok)
            test.eq(other.error.code, "DENIED")
            local inbox = assert(client:call("bee.approvals.binding:inbox", {workspace_id = workspace}))
            test.is_false(inbox.ok)
        end)
    end)
end
return test.run_cases(define_tests)
