local test = require("test")
local identity = require("app_identity")

local WORKSPACE = "0123456789abcdef0123456789abcdef"
local OTHER_WORKSPACE = "fedcba9876543210fedcba9876543210"

local function define_tests()
    test.describe("Application stable identity", function()
        test.it("resolves one member for an admitted app across instances", function()
            local first = assert(identity.stable(WORKSPACE, "bee.example:app"))
            local second = assert(identity.stable(WORKSPACE, "bee.example:app"))
            test.eq(first.id, second.id)
            test.eq(first.workspace_id, WORKSPACE)
            test.eq(first.definition_id, "bee.example:app")
            test.is_nil(first.overlay_owner)
        end)
        test.it("separates another app, another workspace, and another overlay", function()
            local app = assert(identity.stable(WORKSPACE, "bee.example:app"))
            local other_app = assert(identity.stable(WORKSPACE, "bee.other:app"))
            local other_workspace = assert(identity.stable(OTHER_WORKSPACE, "bee.example:app"))
            local governed = assert(identity.stable(WORKSPACE, "app.research:app"))
            test.is_true(app.id ~= other_app.id)
            test.is_true(app.id ~= other_workspace.id)
            test.is_true(app.id ~= governed.id)
            test.eq(governed.overlay_owner, "bee.gov.apps:" .. WORKSPACE .. ".research")
            local colliding = assert(identity.stable(WORKSPACE, "app.research-app"))
            test.is_true(governed.id ~= colliding.id)
        end)
        test.it("keeps the workspace-prefixed actor shape without instance colons", function()
            local stable = assert(identity.stable(WORKSPACE, "bee.example:app"))
            test.eq(stable.id:sub(1, 16), "bee.application:")
            test.eq(stable.id:sub(17, 48), WORKSPACE)
            test.eq(stable.id:sub(49, 49), ":")
            test.is_nil((stable.id:sub(50):find(":", 1, true)))
            test.is_true(#stable.id <= 160)
        end)
        test.it("refuses unbounded or malformed admission values", function()
            test.is_nil(identity.stable("workspace", "bee.example:app"))
            test.is_nil(identity.stable(WORKSPACE, ""))
            test.is_nil(identity.stable(WORKSPACE, "bee.example:app\n"))
            test.is_nil(identity.stable(WORKSPACE, string.rep("d", 161)))
        end)
    end)
end

return require("test").run_cases(define_tests)
