-- MIT. Thread authority: membership roles, idempotent commands, producer
-- dedupe, bounded reads and rollback on storage failure.
local test = require("test")
local harness = require("harness")
local function define_tests()
    test.describe("Thread authority", function()
        local alice = harness.principal("alice", harness.ALL)
        local bob = harness.principal("bob", {})
        local carol = harness.principal("carol", {})
        local hook = harness.principal("hook", {"bee.security.threads:thread_observe_policy"})
        test.it("creates a thread the caller owns and replays identical retries", function()
            local thread_id = "thread-" .. harness.key()
            local key = harness.key()
            local first = alice:call("create", {thread_id = thread_id, idempotency_key = key, title = "Deploy"})
            local summary = harness.value(first)
            test.eq(summary.owner_id, "alice")
            test.eq(summary.revision, 1)
            test.eq(summary.state, "open")
            test.is_false(first.replayed)
            local again = alice:call("create", {thread_id = thread_id, idempotency_key = key, title = "Deploy"})
            test.is_true(again.replayed)
            test.eq(harness.value(again).thread_id, thread_id)
            test.eq(harness.code(alice:call("create", {thread_id = thread_id, idempotency_key = key, title = "Other"})), "CONFLICT")
            test.eq(harness.code(alice:call("create", {thread_id = thread_id, idempotency_key = harness.key(), title = "Deploy"})), "CONFLICT")
            test.eq(harness.code(bob:call("create", {thread_id = "thread-" .. harness.key(), idempotency_key = harness.key(), title = "No grant"})), "DENIED")
            test.eq(harness.code(alice:call("create", {thread_id = thread_id, idempotency_key = harness.key(), title = "x", extra = 1})), "INVALID_ARGUMENT")
        end)
        test.it("keeps owner, participant and observer rights distinct", function()
            local thread_id = harness.thread(alice, "Roles")
            test.eq(harness.code(bob:call("get", {thread_id = thread_id})), "DENIED")
            test.eq(harness.code(bob:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "bob", role = "participant", expected_revision = 1})), "DENIED")
            local joined = harness.value(alice:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "bob", role = "participant", expected_revision = 1}))
            test.eq(joined.revision, 2)
            test.eq(harness.code(alice:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "carol", role = "observer", expected_revision = 1})), "CONFLICT")
            harness.value(alice:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "carol", role = "observer", expected_revision = 2}))
            test.eq(harness.code(bob:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "dave", role = "observer", expected_revision = 3})), "DENIED")
            local seen = harness.value(carol:call("get", {thread_id = thread_id}))
            test.eq(seen.membership.role, "observer")
            test.eq(seen.summary.revision, 3)
            test.eq(harness.code(carol:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.message("m1", "hi")})), "DENIED")
            harness.value(bob:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.message("m1", "hi")}))
            local spoof = harness.message("m2", "as alice")
            spoof.sender_id = "alice"
            test.eq(harness.code(bob:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = spoof})), "DENIED")
            test.eq(harness.code(bob:call("leave", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "carol", expected_revision = 3})), "DENIED")
            test.eq(harness.code(alice:call("leave", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "alice", expected_revision = 3})), "INVALID_STATE")
            local left = harness.value(bob:call("leave", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "bob", expected_revision = 3}))
            test.eq(left.revision, 4)
            test.is_false(left.active)
            test.eq(harness.code(bob:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.message("m3", "gone")})), "DENIED")
            test.eq(harness.code(bob:call("get", {thread_id = thread_id})), "DENIED")
            local listed = harness.value(carol:call("list", {}))
            local found = false
            for _, summary in ipairs(listed.threads) do if summary.thread_id == thread_id then found = true end end
            test.is_true(found)
            local page = harness.value(carol:call("read_after", {thread_id = thread_id, cursor = 0}))
            test.eq(#page.records, 1)
            test.eq(page.records[1].body.sender_id, "bob")
            test.eq(page.records[1].source, "bee")
            test.eq(page.records[1].producer_id, "bob")
        end)
        test.it("orders a removal and a write by transaction order", function()
            local thread_id = harness.thread(alice, "Race")
            harness.value(alice:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "bob", role = "participant", expected_revision = 1}))
            local removal = alice:start("leave", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "bob", expected_revision = 2})
            local write = bob:start("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.message("race", "still here?")})
            local removed = harness.await(removal)
            local written = harness.await(write)
            test.is_true(removed.ok)
            local head = harness.head_sequence(thread_id)
            if written.ok then
                test.eq(head, 1)
                local page = harness.value(alice:call("read_after", {thread_id = thread_id, cursor = 0}))
                test.eq(page.records[1].producer_id, "bob")
            else
                test.eq(written.error.code, "DENIED")
                test.eq(head, 0)
            end
        end)
        test.it("replays identical submissions and conflicts on changed ones", function()
            local thread_id = harness.thread(alice, "Idempotent")
            local key = harness.key()
            local first = harness.value(alice:call("record", {thread_id = thread_id, idempotency_key = key, kind = "message", body = harness.message("m1", "one")}))
            local again = alice:call("record", {thread_id = thread_id, idempotency_key = key, kind = "message", body = harness.message("m1", "one")})
            test.is_true(again.replayed)
            test.eq(harness.value(again).record_id, first.record_id)
            test.eq(harness.code(alice:call("record", {thread_id = thread_id, idempotency_key = key, kind = "message", body = harness.message("m1", "two")})), "CONFLICT")
            test.eq(harness.code(alice:call("close", {thread_id = thread_id, idempotency_key = key, expected_revision = 1})), "CONFLICT")
            test.eq(harness.head_sequence(thread_id), 1)
        end)
        test.it("deduplicates producer events by content, not by key alone", function()
            local thread_id = harness.thread(alice, "Producers")
            harness.value(alice:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "hook", role = "participant", expected_revision = 1}))
            harness.value(alice:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "bob", role = "participant", expected_revision = 2}))
            local observation = {type = "notice", event_key = "n-1", data = {type = "notice", level = "info", code = "ready", content = {text = "ready"}}}
            test.eq(harness.code(bob:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "observation", source = "hook", body = observation})), "DENIED")
            local first = harness.value(hook:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "observation", source = "hook", body = observation}))
            local same = hook:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "observation", source = "hook", body = observation})
            test.is_true(same.replayed)
            test.eq(harness.value(same).sequence, first.sequence)
            local changed = {type = "notice", event_key = "n-1", data = {type = "notice", level = "warning", code = "ready", content = {text = "ready"}}}
            test.eq(harness.code(hook:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "observation", source = "hook", body = changed})), "CONFLICT")
            local other_source = harness.value(hook:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "observation", source = "stream", body = observation}))
            test.eq(other_source.sequence, 2)
            test.eq(harness.code(hook:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "observation", source = "bee", body = observation})), "INVALID_ARGUMENT")
            test.eq(harness.code(hook:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", source = "hook", body = harness.message("x", "y")})), "INVALID_ARGUMENT")
            local page = harness.value(alice:call("read_after", {thread_id = thread_id, cursor = 0}))
            test.eq(page.records[1].source, "hook")
            test.eq(page.records[2].source, "stream")
            test.eq(page.records[1].body.data.code, "ready")
        end)
        test.it("advances filtered cursors without skipping matches", function()
            local thread_id = harness.thread(alice, "Pages")
            for index = 1, 70 do
                harness.value(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.message("m" .. tostring(index), "n" .. tostring(index))}))
            end
            local first = harness.value(alice:call("read_after", {thread_id = thread_id, cursor = 0}))
            test.eq(#first.records, 64)
            test.is_true(first.has_more)
            test.eq(first.scanned_through, 64)
            local rest = harness.value(alice:call("read_after", {thread_id = thread_id, cursor = first.scanned_through}))
            test.eq(#rest.records, 6)
            test.is_false(rest.has_more)
            test.eq(rest.scanned_through, 70)
            test.eq(rest.records[6].sequence, 70)
            local none = harness.value(alice:call("read_after", {thread_id = thread_id, cursor = 0, filter = {kinds = {"receipt"}}}))
            test.eq(#none.records, 0)
            test.is_false(none.has_more)
            test.eq(none.scanned_through, 70)
            local small = harness.value(alice:call("read_after", {thread_id = thread_id, cursor = 10, limit = 5, filter = {kinds = {"message"}}}))
            test.eq(#small.records, 5)
            test.eq(small.records[1].sequence, 11)
            test.eq(small.scanned_through, 15)
            test.is_true(small.has_more)
            test.eq(harness.code(alice:call("read_after", {thread_id = thread_id, cursor = 0, limit = 65})), "INVALID_ARGUMENT")
            test.eq(harness.code(alice:call("read_after", {thread_id = thread_id, cursor = 0, filter = {kinds = {"ballot.cast"}}})), "INVALID_ARGUMENT")
        end)
        test.it("commits concurrent writers with contiguous sequences and unique ids", function()
            local thread_id = harness.thread(alice, "Concurrent")
            harness.value(alice:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "bob", role = "participant", expected_revision = 1}))
            local futures: {any} = {}
            for index = 1, 24 do
                local writer = index % 2 == 0 and alice or bob
                futures[index] = writer:start("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.message("c" .. tostring(index), "concurrent")})
            end
            local sequences: {[integer]: boolean} = {}
            local ids: {[string]: boolean} = {}
            for index = 1, 24 do
                local committed = harness.value(harness.await(futures[index]))
                test.is_nil(sequences[committed.sequence])
                test.is_nil(ids[committed.record_id])
                sequences[committed.sequence] = true
                ids[committed.record_id] = true
            end
            for sequence = 1, 24 do test.is_true(sequences[sequence]) end
            test.eq(harness.head_sequence(thread_id), 24)
        end)
        test.it("closes only without unsettled actions and refuses writes afterwards", function()
            local thread_id = harness.thread(alice, "Closing")
            harness.value(alice:call("admit_action", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", admitted = harness.admitted()}))
            test.eq(harness.code(alice:call("close", {thread_id = thread_id, idempotency_key = harness.key(), expected_revision = 1})), "INVALID_STATE")
            harness.value(alice:call("receipt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", receipt = {scope = "action", outcome = "cancelled", evidence_refs = {}, error = {code = "cancelled", message = "by owner", retryable = false}}}))
            test.eq(harness.code(alice:call("close", {thread_id = thread_id, idempotency_key = harness.key(), expected_revision = 2})), "CONFLICT")
            local closed = harness.value(alice:call("close", {thread_id = thread_id, idempotency_key = harness.key(), expected_revision = 1}))
            test.eq(closed.state, "closed")
            test.eq(closed.revision, 2)
            test.eq(harness.code(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.message("late", "late")})), "INVALID_STATE")
            test.eq(harness.code(alice:call("admit_action", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a2", admitted = harness.admitted()})), "INVALID_STATE")
            test.eq(harness.code(alice:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "bob", role = "observer", expected_revision = 2})), "INVALID_STATE")
            local page = harness.value(alice:call("read_after", {thread_id = thread_id, cursor = 0}))
            test.eq(#page.records, 2)
        end)
        test.it("validates context references against committed work", function()
            local thread_id = harness.thread(alice, "Context")
            local first = harness.value(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.message("m1", "root")}))
            test.eq(harness.code(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.message("m2", "reply"),
                context = {causation = {thread_id = thread_id, record_id = "missing"}}})), "INVALID_ARGUMENT")
            test.eq(harness.code(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.message("m2", "reply"),
                context = {action_id = "nope"}})), "INVALID_ARGUMENT")
            local linked = harness.value(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.message("m2", "reply"),
                context = {causation = {thread_id = thread_id, record_id = first.record_id}, correlation_id = "corr"}}))
            test.eq(linked.sequence, 2)
            local page = harness.value(alice:call("read_after", {thread_id = thread_id, cursor = 1}))
            test.eq(page.records[1].causation.record_id, first.record_id)
            test.eq(page.records[1].correlation_id, "corr")
        end)
        test.it("creates one obligation per recipient and settles it with a correlated reply", function()
            local thread_id = harness.thread(alice, "Requests")
            harness.value(alice:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "bob", role = "participant", expected_revision = 1}))
            harness.value(alice:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "carol", role = "participant", expected_revision = 2}))
            local request = harness.value(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.request("q1", "review this", {"bob", "carol"})}))
            local db = harness.open()
            local pending = harness.query(db, "SELECT recipient_id, state, kind, created_sequence FROM bee_thread_obligations WHERE thread_id = ? ORDER BY recipient_id", {thread_id})
            db:release()
            test.eq(#pending, 2)
            test.eq(pending[1].recipient_id, "bob")
            test.eq(pending[1].state, "pending")
            test.eq(pending[1].kind, "request")
            test.eq(pending[1].created_sequence, request.sequence)
            test.eq(harness.code(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.reply("a0", "not mine", thread_id, request.record_id, "succeeded")})), "INVALID_STATE")
            test.eq(harness.code(bob:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.reply("a1", "done", "other-thread", request.record_id, "succeeded")})), "UNSUPPORTED_CAPABILITY")
            test.eq(harness.code(bob:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.reply("a1", "done", thread_id, "missing", "succeeded")})), "NOT_FOUND")
            local answer = harness.value(bob:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.reply("a1", "done", thread_id, request.record_id, "succeeded")}))
            test.eq(answer.sequence, request.sequence + 1)
            test.eq(harness.code(bob:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.reply("a2", "again", thread_id, request.record_id, "failed")})), "CONFLICT")
            test.eq(harness.code(carol:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.reply("a3", "reply to a reply", thread_id, answer.record_id, "succeeded")})), "INVALID_ARGUMENT")
            local check = harness.open()
            local states = harness.query(check, "SELECT recipient_id, state, reply_record_id, answered_mark_record_id FROM bee_thread_obligations WHERE thread_id = ? ORDER BY recipient_id", {thread_id})
            check:release()
            test.eq(states[1].state, "answered")
            test.eq(states[1].reply_record_id, answer.record_id)
            test.not_nil(states[1].answered_mark_record_id)
            test.eq(states[2].state, "pending")
            local page = harness.value(alice:call("read_after", {thread_id = thread_id, cursor = request.sequence}))
            test.eq(page.records[1].kind, "message")
            test.eq(page.records[2].kind, "request.answered")
            test.eq(page.records[2].body.reply_message_id, "a1")
            test.eq(page.records[2].body.recipient_id, "bob")
            test.eq(page.records[2].causation.record_id, answer.record_id)
        end)
        test.it("reserves capacity for every open request before admitting new work", function()
            local thread_id = harness.thread(alice, "Reserved")
            harness.value(alice:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "bob", role = "participant", expected_revision = 1}))
            harness.value(alice:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "carol", role = "participant", expected_revision = 2}))
            local db = harness.open()
            harness.execute(db, "UPDATE bee_thread_heads SET head_sequence = 9995 WHERE thread_id = ?", {thread_id})
            db:release()
            local request = harness.value(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.request("q", "both", {"bob", "carol"})}))
            test.eq(request.sequence, 9996)
            local note = harness.value(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.message("n", "one free slot")}))
            test.eq(note.sequence, 9997)
            local answer = harness.value(bob:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.reply("a", "mine", thread_id, request.record_id, "succeeded")}))
            test.eq(answer.sequence, 9998)
            test.eq(harness.head_sequence(thread_id), 9999)
            test.eq(harness.code(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.message("m", "reserved for carol")})), "LIMIT_EXCEEDED")
            test.eq(harness.code(carol:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.reply("b", "needs a free slot", thread_id, request.record_id, "succeeded")})), "LIMIT_EXCEEDED")
            test.eq(harness.head_sequence(thread_id), 9999)
        end)
        test.it("bounds membership and rejects oversized records", function()
            local thread_id = harness.thread(alice, "Bounds")
            for index = 1, 127 do
                harness.value(alice:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "member-" .. tostring(index), role = "observer", expected_revision = index}))
            end
            test.eq(harness.code(alice:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "member-128", role = "observer", expected_revision = 128})), "LIMIT_EXCEEDED")
            local big = harness.message("big", string.rep("x", 16300))
            test.eq(harness.code(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = big})), "INVALID_ARGUMENT")
            test.eq(harness.head_sequence(thread_id), 0)
        end)
    end)
end
local cases = test.run_cases(define_tests)
return {run = function(options) return cases(options) end}
