-- MIT. Claims: batches per recipient, one live claim per obligation,
-- release only before dispatch intent, expiry to uncertain, reconciliation,
-- stale incarnations refused, and a reply acknowledging its own live claim.
local test = require("test")
local harness = require("harness")
local owner = require("owner")
local function define_tests()
    test.describe("Thread delivery", function()
        local alice = harness.principal("alice", harness.ALL)
        local bob = harness.principal("bob", {})
        local carol = harness.principal("carol", {})
        local function fanout(): (string, {[string]: unknown})
            local thread_id = harness.thread(alice, "Delivery")
            harness.value(alice:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "bob", role = "participant", expected_revision = 1}))
            harness.value(alice:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "carol", role = "participant", expected_revision = 2}))
            local request = harness.value(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.request("q1", "please", {"bob", "carol"})})) :: {[string]: unknown}
            return thread_id, request
        end
        test.it("claims a batch for the caller only and replays it by key", function()
            local thread_id, request = fanout()
            local key = harness.key()
            local batch = harness.value(bob:call("claim", {thread_id = thread_id, idempotency_key = key, consumer_id = "laptop"}))
            test.eq(#batch.deliveries, 1)
            test.eq(batch.deliveries[1].message_id, "q1")
            test.eq(batch.deliveries[1].record_id, request.record_id)
            test.is_true(batch.owner_incarnation >= 1)
            local again = bob:call("claim", {thread_id = thread_id, idempotency_key = key, consumer_id = "laptop"})
            test.is_true(again.replayed)
            test.eq(harness.value(again).batch_id, batch.batch_id)
            local nothing = harness.value(bob:call("claim", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "phone"}))
            test.eq(#nothing.deliveries, 0)
            test.is_nil(nothing.batch_id)
            test.eq(harness.code(bob:call("claim", {thread_id = thread_id, idempotency_key = key, consumer_id = "phone"})), "CONFLICT")
            local carols = harness.value(carol:call("claim", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "desk"}))
            test.eq(#carols.deliveries, 1)
            test.neq(carols.deliveries[1].delivery_id, batch.deliveries[1].delivery_id)
            local page = harness.value(alice:call("read_after", {thread_id = thread_id, cursor = request.sequence, filter = {kinds = {"delivery.mark"}}}))
            test.eq(#page.records, 2)
            test.eq(page.records[1].body.state, "claimed")
            test.eq(page.records[1].body.recipient_id, "bob")
            test.eq(page.records[1].body.channel, "wait")
            test.eq(harness.code(alice:call("claim", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "x", channel = "carrier"})), "INVALID_ARGUMENT")
        end)
        test.it("acknowledges, releases before dispatch, and refuses release after dispatch intent", function()
            local thread_id = fanout()
            local batch = harness.value(bob:call("claim", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "laptop"}))
            local delivery_id = batch.deliveries[1].delivery_id
            test.eq(harness.code(carol:call("ack", {thread_id = thread_id, idempotency_key = harness.key(), delivery_id = delivery_id})), "DENIED")
            local released = harness.value(bob:call("release", {thread_id = thread_id, idempotency_key = harness.key(), delivery_id = delivery_id, reason = "not-ready"}))
            test.eq(released.state, "released")
            test.eq(harness.code(bob:call("ack", {thread_id = thread_id, idempotency_key = harness.key(), delivery_id = delivery_id})), "INVALID_STATE")
            local second = harness.value(bob:call("claim", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "laptop"}))
            test.eq(#second.deliveries, 1)
            local reclaimed = second.deliveries[1].delivery_id
            test.neq(reclaimed, delivery_id)
            local intent = harness.value(bob:call("dispatch", {thread_id = thread_id, idempotency_key = harness.key(), delivery_id = reclaimed, accepted = false}))
            test.is_true(intent.dispatched)
            test.eq(harness.code(bob:call("release", {thread_id = thread_id, idempotency_key = harness.key(), delivery_id = reclaimed, reason = "changed-mind"})), "INVALID_STATE")
            local acked = harness.value(bob:call("ack", {thread_id = thread_id, idempotency_key = harness.key(), delivery_id = reclaimed, evidence_ref = "stdin-write-1"}))
            test.eq(acked.state, "delivered")
            local repeat_ack = bob:call("ack", {thread_id = thread_id, idempotency_key = harness.key(), delivery_id = reclaimed})
            test.is_true(repeat_ack.replayed)
            local db = harness.open()
            local rows = harness.query(db, "SELECT state, delivery_id FROM bee_thread_obligations WHERE thread_id = ? AND recipient_id = 'bob'", {thread_id})
            db:release()
            test.eq(rows[1].state, "delivered")
            test.eq(rows[1].delivery_id, reclaimed)
            local third = harness.value(bob:call("claim", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "laptop"}))
            test.eq(#third.deliveries, 0)
        end)
        test.it("moves an expired claim to uncertain and reconciles it explicitly", function()
            local thread_id = fanout()
            local batch = harness.value(bob:call("claim", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "laptop"}))
            local delivery_id = batch.deliveries[1].delivery_id
            test.eq(harness.code(alice:call("expire", {thread_id = thread_id, idempotency_key = harness.key(), delivery_id = delivery_id})), "INVALID_STATE")
            test.eq(harness.code(bob:call("expire", {thread_id = thread_id, idempotency_key = harness.key(), delivery_id = delivery_id})), "DENIED")
            local db = harness.open()
            harness.execute(db, "UPDATE bee_thread_deliveries SET expires_at = '2000-01-01T00:00:00.000Z' WHERE delivery_id = ?", {delivery_id})
            db:release()
            local expired = harness.value(alice:call("expire", {thread_id = thread_id, idempotency_key = harness.key(), delivery_id = delivery_id}))
            test.eq(expired.state, "uncertain")
            test.eq(harness.code(bob:call("ack", {thread_id = thread_id, idempotency_key = harness.key(), delivery_id = delivery_id})), "INVALID_STATE")
            local nothing = harness.value(bob:call("claim", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "laptop"}))
            test.eq(#nothing.deliveries, 0)
            test.eq(harness.code(bob:call("reconcile", {thread_id = thread_id, idempotency_key = harness.key(), delivery_id = delivery_id, decision = "redeliver"})), "DENIED")
            local redelivered = harness.value(alice:call("reconcile", {thread_id = thread_id, idempotency_key = harness.key(), delivery_id = delivery_id, decision = "redeliver"}))
            test.eq(redelivered.state, "released")
            test.eq(redelivered.obligation, "pending")
            local fresh = harness.value(bob:call("claim", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "laptop"}))
            test.eq(#fresh.deliveries, 1)
            local check = harness.open()
            harness.execute(check, "UPDATE bee_thread_deliveries SET expires_at = '2000-01-01T00:00:00.000Z' WHERE delivery_id = ?", {fresh.deliveries[1].delivery_id})
            check:release()
            harness.value(alice:call("expire", {thread_id = thread_id, idempotency_key = harness.key(), delivery_id = fresh.deliveries[1].delivery_id}))
            local abandoned = harness.value(alice:call("reconcile", {thread_id = thread_id, idempotency_key = harness.key(), delivery_id = fresh.deliveries[1].delivery_id, decision = "abandon"}))
            test.eq(abandoned.obligation, "abandoned")
            test.eq(harness.code(bob:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.reply("late", "too late", thread_id, "unused", "succeeded")})), "NOT_FOUND")
            local marks = harness.value(alice:call("read_after", {thread_id = thread_id, cursor = 0, filter = {kinds = {"delivery.mark"}}}))
            local states: {string} = {}
            for index, item in ipairs(marks.records) do states[index] = item.body.state end
            test.eq(table.concat(states, ","), "claimed,uncertain,released,claimed,uncertain,released")
        end)
        test.it("acknowledges the exact live claim when the recipient replies", function()
            local thread_id, request = fanout()
            local batch = harness.value(bob:call("claim", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "laptop"}))
            local answer = harness.value(bob:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.reply("a1", "done", thread_id, request.record_id, "succeeded")}))
            local db = harness.open()
            local delivery = harness.query(db, "SELECT state, evidence_ref FROM bee_thread_deliveries WHERE delivery_id = ?", {batch.deliveries[1].delivery_id})
            local obligation = harness.query(db, "SELECT state FROM bee_thread_obligations WHERE thread_id = ? AND recipient_id = 'bob'", {thread_id})
            db:release()
            test.eq(delivery[1].state, "delivered")
            test.eq(delivery[1].evidence_ref, answer.record_id)
            test.eq(obligation[1].state, "answered")
            local page = harness.value(alice:call("read_after", {thread_id = thread_id, cursor = answer.sequence}))
            test.eq(page.records[1].kind, "request.answered")
            test.eq(page.records[2].kind, "delivery.mark")
            test.eq(page.records[2].body.state, "delivered")
        end)
        test.it("refuses settlement of a claim from an earlier owner incarnation", function()
            local thread_id = fanout()
            local batch = harness.value(bob:call("claim", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "laptop"}))
            local db = harness.open()
            local bumped = owner.establish(db)
            db:release()
            test.is_true(bumped > batch.owner_incarnation)
            test.eq(harness.code(bob:call("ack", {thread_id = thread_id, idempotency_key = harness.key(), delivery_id = batch.deliveries[1].delivery_id})), "CONFLICT")
            local expired = harness.value(alice:call("expire", {thread_id = thread_id, idempotency_key = harness.key(), delivery_id = batch.deliveries[1].delivery_id}))
            test.eq(expired.state, "uncertain")
            local decided = harness.value(alice:call("reconcile", {thread_id = thread_id, idempotency_key = harness.key(), delivery_id = batch.deliveries[1].delivery_id, decision = "delivered", evidence_ref = "log-line-9"}))
            test.eq(decided.state, "delivered")
        end)
        test.it("reserves a terminal mark per live claim", function()
            local thread_id = fanout()
            local db = harness.open()
            harness.execute(db, "UPDATE bee_thread_heads SET head_sequence = 9995 WHERE thread_id = ?", {thread_id})
            db:release()
            local batch = harness.value(bob:call("claim", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "laptop"}))
            test.eq(batch.deliveries[1].sequence, 1)
            test.eq(harness.head_sequence(thread_id), 9996)
            test.eq(harness.code(carol:call("claim", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "desk"})), "LIMIT_EXCEEDED")
            local acked = harness.value(bob:call("ack", {thread_id = thread_id, idempotency_key = harness.key(), delivery_id = batch.deliveries[1].delivery_id}))
            test.eq(acked.state, "delivered")
            test.eq(harness.head_sequence(thread_id), 9997)
        end)
    end)
end
local cases = test.run_cases(define_tests)
return {run = function(options) return cases(options) end}
