-- MIT. Version-1 history survives migrations 2 and 3 untouched, the new
-- authority works beside it, and altered or newer ledgers fail closed.
local test = require("test")
local harness = require("harness")
local database = require("database")
local legacy = require("legacy")
local ledger = require("ledger")
local migrations = require("migrations")
local owner = require("owner")
local sql = require("sql")
local function define_tests()
    test.describe("Thread migration ledger", function()
        test.it("upgrades a populated version-1 store byte for byte", function()
            local resource = "bee.threads:upgrade_test_db"
            local v1, open_error = database.open_at(resource, 1)
            if not v1 then error(tostring(open_error)) end
            local claimed, claim_error = legacy.claim(v1, "alice", "legacy-thread", "run-1")
            test.is_true(claimed)
            test.is_nil(claim_error)
            for index = 1, 3 do
                local seq = legacy.append(v1, "alice", "legacy-thread", "run-1", "key-" .. tostring(index), "test.case", '{"n":' .. tostring(index) .. '}')
                test.eq(seq, index)
            end
            local before = harness.query(v1, "SELECT thread_id, sequence, run_id, idempotency_key, event_type, body_json, committed_at FROM bee_thread_events ORDER BY sequence")
            local ledger_before = harness.query(v1, "SELECT id, name, checksum FROM bee_thread_schema_migrations ORDER BY id")
            v1:release()
            test.eq(#ledger_before, 1)
            test.eq(ledger_before[1].name, "bee_thread_schema_v1")
            local expected_checksum = ledger.checksum(migrations.prefix(1)[1])
            test.eq(ledger_before[1].checksum, expected_checksum)
            local upgraded, upgrade_error = database.open(resource)
            if not upgraded then error(tostring(upgrade_error)) end
            local after = harness.query(upgraded, "SELECT thread_id, sequence, run_id, idempotency_key, event_type, body_json, committed_at FROM bee_thread_events ORDER BY sequence")
            test.eq(#after, #before)
            for index, row in ipairs(before) do
                for _, column in ipairs({"thread_id", "sequence", "run_id", "idempotency_key", "event_type", "body_json", "committed_at"}) do
                    test.eq(after[index][column], row[column])
                end
            end
            local ledger_after = harness.query(upgraded, "SELECT id, name, checksum FROM bee_thread_schema_migrations ORDER BY id")
            test.eq(#ledger_after, 14)
            test.eq(ledger_after[1].checksum, expected_checksum)
            test.eq(ledger_after[2].name, "thread_authority")
            test.eq(ledger_after[3].name, "work_lifecycle")
            test.eq(ledger_after[4].name, "delivery")
            test.eq(ledger_after[5].name, "projection")
            test.eq(ledger_after[6].name, "carrier")
            test.eq(ledger_after[7].name, "approvals")
            test.eq(ledger_after[8].name, "owner_authority")
            test.eq(ledger_after[9].name, "notices")
            test.eq(ledger_after[10].name, "workspace_attribution")
            test.eq(ledger_after[11].name, "action_inbox")
            test.eq(ledger_after[12].name, "action_inbox_push")
            test.eq(ledger_after[13].name, "action_inbox_delivery_status")
            test.eq(ledger_after[14].name, "action_inbox_outbox")
            local events, read_error = legacy.read(upgraded, "alice", "legacy-thread", 0)
            test.is_nil(read_error)
            test.eq(#events, 3)
            test.eq(events[3].body, '{"n":3}')
            local denied, denied_error = legacy.read(upgraded, "bob", "legacy-thread", 0)
            test.is_nil(denied)
            test.eq(denied_error, "thread access denied")
            local heads = harness.query(upgraded, "SELECT COUNT(*) AS count FROM bee_thread_heads")
            test.eq(heads[1].count, 0)
            upgraded:release()
            local again, again_error = database.open(resource)
            if not again then error(tostring(again_error)) end
            local ledger_again = harness.query(again, "SELECT COUNT(*) AS count FROM bee_thread_schema_migrations")
            test.eq(ledger_again[1].count, 14)
            again:release()
        end)
        test.it("rebuilds the record table without touching rows or lifecycle references", function()
            local resource = "bee.threads:rebuild_test_db"
            local v3, open_error = database.open_at(resource, 3)
            if not v3 then error(tostring(open_error)) end
            harness.execute(v3, "INSERT INTO bee_thread_heads (thread_id, owner_actor, title, state, revision, head_sequence, created_at) VALUES ('t', 'alice', 'T', 'open', 1, 2, 'now')")
            harness.execute(v3, "INSERT INTO bee_thread_members (thread_id, actor, role, revision, active) VALUES ('t', 'alice', 'owner', 1, 1)")
            harness.execute(v3, "INSERT INTO bee_thread_records (record_id, thread_id, sequence, schema_revision, kind, producer_id, source, action_id, record_json, committed_at) VALUES ('r1', 't', 1, 'bee.thread-record@1', 'action.admitted', 'alice', 'bee', 'a1', '{\"k\":1}', 'now')")
            harness.execute(v3, "INSERT INTO bee_thread_records (record_id, thread_id, sequence, schema_revision, kind, producer_id, source, event_scope, event_key, record_json, committed_at) VALUES ('r2', 't', 2, 'bee.thread-record@1', 'observation', 'hook', 'hook', 'hook/', 'k', '{\"k\":2}', 'now')")
            harness.execute(v3, "INSERT INTO bee_thread_actions (thread_id, action_id, admitted_record_id, state) VALUES ('t', 'a1', 'r1', 'admitted')")
            harness.execute(v3, "INSERT INTO bee_thread_records (record_id, thread_id, sequence, schema_revision, kind, producer_id, source, action_id, attempt_id, record_json, committed_at) VALUES ('r0', 't', 3, 'bee.thread-record@1', 'attempt.started', 'alice', 'bee', 'a1', 'x1', '{\"k\":3}', 'now')")
            harness.execute(v3, "INSERT INTO bee_thread_attempts (thread_id, attempt_id, action_id, owner_epoch, started_record_id, state) VALUES ('t', 'x1', 'a1', 1, 'r0', 'running')")
            harness.execute(v3, "UPDATE bee_thread_heads SET head_sequence = 3 WHERE thread_id = 't'")
            local before = harness.query(v3, "SELECT record_id, sequence, kind, event_scope, event_key, action_id, record_json, committed_at FROM bee_thread_records ORDER BY sequence")
            v3:release()
            local v5, upgrade_error = database.open(resource)
            if not v5 then error(tostring(upgrade_error)) end
            local after = harness.query(v5, "SELECT record_id, sequence, kind, event_scope, event_key, action_id, record_json, committed_at FROM bee_thread_records ORDER BY sequence")
            test.eq(#after, 3)
            for index, row in ipairs(before) do
                for _, column in ipairs({"record_id", "sequence", "kind", "event_scope", "event_key", "action_id", "record_json", "committed_at"}) do
                    test.eq(after[index][column], row[column])
                end
            end
            test.eq(#harness.query(v5, "PRAGMA foreign_key_check"), 0)
            local indexes = harness.query(v5, "SELECT name FROM sqlite_master WHERE type = 'index' AND tbl_name = 'bee_thread_records' AND name LIKE 'bee_thread_records_%' ORDER BY name")
            test.eq(#indexes, 2)
            local actions = harness.query(v5, "SELECT a.action_id FROM bee_thread_actions a JOIN bee_thread_records r ON r.record_id = a.admitted_record_id WHERE a.thread_id = 't'")
            test.eq(actions[1].action_id, "a1")
            local attempts = harness.query(v5, "SELECT attempt_id, state, owner_epoch, prepared_record_id, started_record_id FROM bee_thread_attempts WHERE thread_id = 't'")
            test.eq(attempts[1].attempt_id, "x1")
            test.eq(attempts[1].state, "running")
            test.eq(attempts[1].owner_epoch, 1)
            test.is_nil(attempts[1].prepared_record_id)
            test.eq(attempts[1].started_record_id, "r0")
            local _, second_live = v5:execute("INSERT INTO bee_thread_attempts (thread_id, attempt_id, action_id, prepared_record_id, state) VALUES ('t', 'x2', 'a1', NULL, 'prepared')")
            test.not_nil(second_live)
            harness.execute(v5, "INSERT INTO bee_thread_records (record_id, thread_id, sequence, schema_revision, kind, producer_id, source, record_json, committed_at) VALUES ('r3', 't', 4, 'bee.thread-record@1', 'delivery.mark', 'bee', 'bee', '{}', 'now')")
            harness.execute(v5, "INSERT INTO bee_thread_records (record_id, thread_id, sequence, schema_revision, kind, producer_id, source, record_json, committed_at) VALUES ('r6', 't', 5, 'bee.thread-record@1', 'attempt.prepared', 'bee', 'bee', '{}', 'now')")
            harness.execute(v5, "INSERT INTO bee_thread_records (record_id, thread_id, sequence, schema_revision, kind, producer_id, source, record_json, committed_at) VALUES ('r7', 't', 7, 'bee.thread-record@1', 'approval.transition', 'bee', 'bee', '{}', 'now')")
            local _, rejected = v5:execute("INSERT INTO bee_thread_records (record_id, thread_id, sequence, schema_revision, kind, producer_id, source, record_json, committed_at) VALUES ('r4', 't', 6, 'bee.thread-record@1', 'recap.checkpoint', 'bee', 'bee', '{}', 'now')")
            test.not_nil(rejected)
            local _, duplicate = v5:execute("INSERT INTO bee_thread_records (record_id, thread_id, sequence, schema_revision, kind, producer_id, source, record_json, committed_at) VALUES ('r5', 't', 3, 'bee.thread-record@1', 'message', 'bee', 'bee', '{}', 'now')")
            test.not_nil(duplicate)
            local foreign = harness.query(v5, "PRAGMA foreign_keys")
            test.eq(foreign[1].foreign_keys, 1)
            v5:release()
        end)
        test.it("rolls the rebuild back when a reference is broken", function()
            local resource = "bee.threads:broken_rebuild_test_db"
            local v3, open_error = database.open_at(resource, 3)
            if not v3 then error(tostring(open_error)) end
            harness.execute(v3, "PRAGMA foreign_keys = OFF")
            harness.execute(v3, "INSERT INTO bee_thread_actions (thread_id, action_id, admitted_record_id, state) VALUES ('ghost', 'a1', 'missing', 'admitted')")
            harness.execute(v3, "PRAGMA foreign_keys = ON")
            v3:release()
            local failed, failure = database.open(resource)
            test.is_nil(failed)
            test.eq(failure, "thread migration delivery leaves broken references")
            local raw = harness.raw(resource)
            local ledger_rows = harness.query(raw, "SELECT COUNT(*) AS count FROM bee_thread_schema_migrations")
            test.eq(ledger_rows[1].count, 3)
            local tables = harness.query(raw, "SELECT name FROM sqlite_master WHERE type = 'table' AND name IN ('bee_thread_records', 'bee_thread_records_rebuilt', 'bee_thread_obligations') ORDER BY name")
            test.eq(#tables, 1)
            test.eq(tables[1].name, "bee_thread_records")
            raw:release()
        end)
        test.it("advances the owner incarnation only when an owner starts", function()
            local resource = "bee.threads:upgrade_test_db"
            local db, open_error = database.open(resource)
            if not db then error(tostring(open_error)) end
            local first, first_error = owner.establish(db)
            if not first then error(tostring(first_error)) end
            local second = owner.establish(db)
            test.eq(second, first + 1)
            local tx = db:begin({isolation = sql.isolation.SERIALIZABLE})
            if not tx then error("begin") end
            test.eq(owner.current(tx), second)
            tx:rollback()
            db:release()
            local live = harness.open()
            local live_tx = live:begin({isolation = sql.isolation.SERIALIZABLE})
            if not live_tx then error("begin") end
            local running = owner.current(live_tx)
            live_tx:rollback()
            live:release()
            if not running then error("the owner service did not establish an incarnation at boot") end
            test.is_true(running >= 1)
        end)
        test.it("fails closed on altered and newer ledgers", function()
            local resource = "bee.threads:tamper_test_db"
            local db, open_error = database.open(resource)
            if not db then error(tostring(open_error)) end
            local rows = harness.query(db, "SELECT checksum FROM bee_thread_schema_migrations WHERE id = 2")
            local original = rows[1].checksum
            harness.execute(db, "UPDATE bee_thread_schema_migrations SET checksum = 'tampered' WHERE id = 2")
            db:release()
            local tampered, tampered_error = database.open(resource)
            test.is_nil(tampered)
            test.eq(tampered_error, "thread migration checksum changed")
            local repair = harness.raw(resource)
            harness.execute(repair, "UPDATE bee_thread_schema_migrations SET checksum = ? WHERE id = 2", {original})
            harness.execute(repair, "UPDATE bee_thread_schema_migrations SET name = 'renamed' WHERE id = 3")
            repair:release()
            local renamed, renamed_error = database.open(resource)
            test.is_nil(renamed)
            test.eq(renamed_error, "thread migration name changed")
            local restore = harness.raw(resource)
            harness.execute(restore, "UPDATE bee_thread_schema_migrations SET name = 'work_lifecycle' WHERE id = 3")
            local future = #migrations.all() + 1
            harness.execute(restore, "INSERT INTO bee_thread_schema_migrations (id, name, checksum, applied_at) VALUES (?, 'future', 'future', 'now')", {future})
            restore:release()
            local newer, newer_error = database.open(resource)
            test.is_nil(newer)
            test.eq(newer_error, "thread database schema is newer")
            local cleanup = harness.raw(resource)
            harness.execute(cleanup, "DELETE FROM bee_thread_schema_migrations WHERE id = ?", {future})
            harness.execute(cleanup, "DELETE FROM bee_thread_schema_migrations WHERE id = 2")
            cleanup:release()
            local gap, gap_error = database.open(resource)
            test.is_nil(gap)
            test.eq(gap_error, "thread migration ledger has a gap")
        end)
    end)
end
local cases = test.run_cases(define_tests)
return {run = function(options) return cases(options) end}
