-- MIT. Work lifecycle: host-granted authority, legal transitions, one
-- terminal receipt per identity, capacity reservation and rollback.
local test = require("test")
local harness = require("harness")
local function define_tests()
    test.describe("Thread lifecycle", function()
        local alice = harness.principal("alice", harness.ALL)
        local owner_only = harness.principal("owner-only", {"bee:thread_create_policy"})
        local runner = harness.principal("runner", {"bee:thread_lifecycle_policy"})
        local function started(epoch: integer): {[string]: unknown}
            return {execution_kind = "process", execution_ref = "pid-" .. tostring(epoch), owner_epoch = epoch}
        end
        local function turn(): {[string]: unknown}
            return {input_message_ids = {}, input = {text = "do it"}, delivery_ids = {}}
        end
        local function ended(outcome: string): {[string]: unknown}
            if outcome == "succeeded" then return {outcome = outcome, answer_message_ids = {}, evidence_refs = {}} end
            return {outcome = outcome, answer_message_ids = {}, evidence_refs = {}, error = {code = outcome, message = outcome, retryable = false}}
        end
        local function receipt(scope: string, outcome: string): {[string]: unknown}
            if outcome == "succeeded" then return {scope = scope, outcome = outcome, evidence_refs = {}} end
            return {scope = scope, outcome = outcome, evidence_refs = {}, error = {code = outcome, message = outcome, retryable = false}}
        end
        test.it("requires the host lifecycle grant rather than ownership", function()
            local thread_id = harness.thread(owner_only, "Owned")
            test.eq(harness.code(owner_only:call("admit_action", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", admitted = harness.admitted()})), "DENIED")
            local admitted = harness.value(runner:call("admit_action", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", admitted = harness.admitted()}))
            test.eq(admitted.sequence, 1)
            test.eq(admitted.state, "admitted")
            test.eq(harness.code(runner:call("get", {thread_id = thread_id})), "DENIED")
            local page = harness.value(owner_only:call("read_after", {thread_id = thread_id, cursor = 0}))
            test.eq(page.records[1].kind, "action.admitted")
            test.eq(page.records[1].producer_id, "runner")
            test.eq(page.records[1].action_id, "a1")
            test.eq(page.records[1].body.principal_id, "alice")
        end)
        test.it("walks an action through attempts and turns to one receipt each", function()
            local thread_id = harness.thread(alice, "Work")
            local key = harness.key()
            harness.value(alice:call("admit_action", {thread_id = thread_id, idempotency_key = key, action_id = "a1", admitted = harness.admitted()}))
            test.is_true(alice:call("admit_action", {thread_id = thread_id, idempotency_key = key, action_id = "a1", admitted = harness.admitted()}).replayed)
            test.eq(harness.code(alice:call("admit_action", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", admitted = harness.admitted()})), "CONFLICT")
            test.eq(harness.code(alice:call("request_turn", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t1", turn_id = "u1", turn = turn()})), "NOT_FOUND")
            test.eq(harness.code(alice:call("prepare_attempt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "missing", attempt_id = "t1", prepared = harness.prepared()})), "NOT_FOUND")
            test.eq(harness.code(alice:call("start_attempt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t1", started = started(1)})), "NOT_FOUND")
            harness.value(alice:call("prepare_attempt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t1", prepared = harness.prepared()}))
            test.eq(harness.code(alice:call("prepare_attempt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t2", prepared = harness.prepared()})), "INVALID_STATE")
            harness.value(alice:call("start_attempt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t1", started = started(1)}))
            test.eq(harness.code(alice:call("start_attempt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t1", started = started(2)})), "INVALID_STATE")
            test.eq(harness.code(alice:call("prepare_attempt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t2", prepared = harness.prepared()})), "INVALID_STATE")
            test.eq(harness.code(alice:call("receipt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", receipt = receipt("action", "succeeded")})), "INVALID_STATE")
            harness.value(alice:call("request_turn", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t1", turn_id = "u1", turn = turn()}))
            test.eq(harness.code(alice:call("request_turn", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t1", turn_id = "u2", turn = turn()})), "INVALID_STATE")
            test.eq(harness.code(alice:call("receipt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t1", receipt = receipt("attempt", "failed")})), "INVALID_STATE")
            harness.value(alice:call("end_turn", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t1", turn_id = "u1", turn_end = ended("succeeded")}))
            test.eq(harness.code(alice:call("end_turn", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t1", turn_id = "u1", turn_end = ended("failed")})), "CONFLICT")
            harness.value(alice:call("receipt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t1", receipt = receipt("attempt", "uncertain")}))
            test.eq(harness.code(alice:call("receipt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t1", receipt = receipt("attempt", "failed")})), "CONFLICT")
            test.eq(harness.code(alice:call("request_turn", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t1", turn_id = "u3", turn = turn()})), "INVALID_STATE")
            harness.value(alice:call("prepare_attempt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t2", prepared = harness.prepared()}))
            test.eq(harness.code(alice:call("start_attempt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t2", started = started(1)})), "INVALID_STATE")
            harness.value(alice:call("start_attempt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t2", started = started(2)}))
            harness.value(alice:call("receipt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t2", receipt = receipt("attempt", "succeeded")}))
            harness.value(alice:call("receipt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", receipt = receipt("action", "succeeded")}))
            test.eq(harness.code(alice:call("receipt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", receipt = receipt("action", "failed")})), "CONFLICT")
            test.eq(harness.code(alice:call("prepare_attempt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t3", prepared = harness.prepared()})), "INVALID_STATE")
            test.eq(harness.code(alice:call("receipt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t1", receipt = receipt("action", "failed")})), "INVALID_ARGUMENT")
            local page = harness.value(alice:call("read_after", {thread_id = thread_id, cursor = 0, filter = {action_id = "a1"}}))
            local kinds: {string} = {}
            for index, item in ipairs(page.records) do kinds[index] = item.kind end
            test.eq(table.concat(kinds, ","), "action.admitted,attempt.prepared,attempt.started,turn.request,turn.end,receipt,attempt.prepared,attempt.started,receipt,receipt")
            test.eq(page.records[2].body.placement_attempt_id, "placement-1")
            test.eq(page.records[2].attempt_id, "t1")
            test.eq(page.records[5].turn_id, "u1")
            test.eq(page.records[10].attempt_id, nil)
            test.eq(page.records[10].body.scope, "action")
            local turns = harness.value(alice:call("read_after", {thread_id = thread_id, cursor = 0, filter = {kinds = {"turn.request", "turn.end"}}}))
            test.eq(#turns.records, 2)
        end)
        test.it("fences competing and delayed continuations by the last settled attempt", function()
            local thread_id = harness.thread(alice, "Continuation")
            harness.value(alice:call("admit_action", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a", admitted = harness.admitted()}))
            local function prepare_next(id: string, previous: string): {[string]: unknown}
                return {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a", attempt_id = id,
                    expected_previous_attempt_id = previous, prepared = harness.prepared()}
            end
            test.eq(harness.code(alice:call("prepare_attempt", prepare_next("missing", "absent"))), "CONFLICT")
            local invalid = prepare_next("invalid", "")
            test.eq(harness.code(alice:call("prepare_attempt", invalid)), "INVALID_ARGUMENT")
            harness.value(alice:call("prepare_attempt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a", attempt_id = "first", prepared = harness.prepared()}))
            harness.value(alice:call("receipt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a", attempt_id = "first", receipt = receipt("attempt", "succeeded")}))
            harness.value(alice:call("admit_action", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "other", admitted = harness.admitted()}))
            harness.value(alice:call("prepare_attempt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "other", attempt_id = "foreign", prepared = harness.prepared()}))
            harness.value(alice:call("receipt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "other", attempt_id = "foreign", receipt = receipt("attempt", "succeeded")}))
            test.eq(harness.code(alice:call("prepare_attempt", prepare_next("cross", "foreign"))), "CONFLICT")
            local left = prepare_next("left", "first")
            local right = prepare_next("right", "first")
            local first = alice:start("prepare_attempt", left)
            local second = alice:start("prepare_attempt", right)
            local first_reply, second_reply = harness.await(first), harness.await(second)
            test.neq(first_reply.ok, second_reply.ok)
            local winner = first_reply.ok and left or right
            local losing_reply = first_reply.ok and second_reply or first_reply
            test.eq(harness.code(losing_reply), "INVALID_STATE")
            local winner_id = tostring(winner.attempt_id)
            harness.value(alice:call("receipt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a", attempt_id = winner_id, receipt = receipt("attempt", "succeeded")}))
            test.eq(harness.code(alice:call("prepare_attempt", prepare_next("delayed", "first"))), "CONFLICT")
            local replay = alice:call("prepare_attempt", winner)
            test.is_true(replay.ok)
            test.is_true(replay.replayed)
            harness.value(alice:call("prepare_attempt", prepare_next("next", winner_id)))
            local page = harness.value(alice:call("read_after", {thread_id = thread_id, cursor = 0, filter = {action_id = "a", kinds = {"attempt.prepared"}}}))
            test.eq(#page.records, 3, "rejected continuations must not allocate an attempt")
        end)
        test.it("reserves capacity for the receipts still owed", function()
            local thread_id = harness.thread(alice, "Capacity")
            local db = harness.open()
            harness.execute(db, "UPDATE bee_thread_heads SET head_sequence = 9996 WHERE thread_id = ?", {thread_id})
            db:release()
            local dummy = harness.value(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.message("filler", "9997")}))
            test.eq(dummy.sequence, 9997)
            harness.value(alice:call("admit_action", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", admitted = harness.admitted()}))
            test.eq(harness.code(alice:call("admit_action", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a2", admitted = harness.admitted()})), "LIMIT_EXCEEDED")
            test.eq(harness.code(alice:call("prepare_attempt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t1", prepared = harness.prepared()})), "LIMIT_EXCEEDED")
            local room = harness.value(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.message("m", "9999 leaves the receipt its slot")}))
            test.eq(room.sequence, 9999)
            test.eq(harness.code(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.message("m2", "no room")})), "LIMIT_EXCEEDED")
            local settled = harness.value(alice:call("receipt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", receipt = receipt("action", "cancelled")}))
            test.eq(settled.sequence, 10000)
            test.eq(harness.code(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.message("over", "none")})), "LIMIT_EXCEEDED")
            test.eq(harness.head_sequence(thread_id), 10000)
        end)
        test.it("rolls back a failed lifecycle index without leaving a head gap", function()
            local thread_id = harness.thread(alice, "Rollback")
            local admitted = harness.value(alice:call("admit_action", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", admitted = harness.admitted()}))
            local db = harness.open()
            harness.execute(db, "INSERT INTO bee_thread_settlements (thread_id, action_id, attempt_id, scope, outcome, record_id) VALUES (?, ?, NULL, 'action', 'succeeded', ?)", {thread_id, "a1", admitted.record_id})
            db:release()
            local reply = alice:call("receipt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", receipt = receipt("action", "succeeded")})
            test.eq(harness.code(reply), "INTERNAL")
            test.eq(harness.head_sequence(thread_id), 1)
            local check = harness.open()
            local records = harness.query(check, "SELECT COUNT(*) AS count FROM bee_thread_records WHERE thread_id = ?", {thread_id})
            local commands = harness.query(check, "SELECT COUNT(*) AS count FROM bee_thread_commands WHERE thread_id = ?", {thread_id})
            local actions = harness.query(check, "SELECT state FROM bee_thread_actions WHERE thread_id = ? AND action_id = 'a1'", {thread_id})
            check:release()
            test.eq(records[1].count, 1)
            test.eq(commands[1].count, 2)
            test.eq(actions[1].state, "admitted")
            local next_record = harness.value(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.message("after", "gap-free")}))
            test.eq(next_record.sequence, 2)
        end)
        test.it("bounds actions, attempts and turns per thread", function()
            local thread_id = harness.thread(alice, "Counts")
            for index = 1, 128 do
                harness.value(alice:call("admit_action", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a" .. tostring(index), admitted = harness.admitted()}))
            end
            test.eq(harness.code(alice:call("admit_action", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a129", admitted = harness.admitted()})), "LIMIT_EXCEEDED")
            test.eq(harness.code(alice:call("start_attempt", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t0", started = started(0)})), "INVALID_ARGUMENT")
            test.eq(harness.code(alice:call("request_turn", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "a1", attempt_id = "t1", turn_id = "u1",
                turn = {input_message_ids = {}, input = {text = "x"}, delivery_ids = {"d1"}}})), "INVALID_ARGUMENT")
        end)
    end)
end
local cases = test.run_cases(define_tests)
return {run = function(options) return cases(options) end}
