local test = require("test")
local host = require("host")
local bounds = require("bounds")
local harness = require("harness")
local gateway = require("gateway")
local registry = require("registry")
local json = require("json")
local owner = require("owner")
local function subscribed(session: host.Session, client: funcs.Executor): {[string]: unknown}
    return host.value(host.receive(client, "subscribe", {thread_id = session.thread, idempotency_key = harness.key(), filter = {session_ref = session.session, trait_id = session.trait_id or host.TRAIT}}))
end
local function page(session: host.Session, client: funcs.Executor, subscription: unknown, limit: integer?): {[string]: unknown}
    return host.value(host.receive(client, "page", {thread_id = session.thread, subscription_id = subscription, limit = limit}))
end
local function denied(reply: {[string]: unknown}): string
    test.eq(reply.ok, false)
    return assert(bounds.id(assert(bounds.object(reply.error)).code))
end
local function define_tests()
    test.describe("App trait listens", function()
        test.it("discovers only approved selections for the app's own trait", function()
            local first, second = host.open(), host.open()
            local client = host.client("discover-" .. harness.key())
            host.revoke(first)
            local subscribed = host.value(host.receive(client, "subscribe", {trait_id = host.TRAIT, idempotency_key = harness.key()}))
            local found: {[string]: boolean} = {}
            for _, raw in ipairs(assert(bounds.array(subscribed.subscriptions, 128))) do
                local row = assert(bounds.object(raw))
                found[assert(bounds.id(row.session_ref))] = true
                test.eq(row.trait_id, host.TRAIT)
                test.not_nil(row.thread_id)
            end
            test.is_nil(found[first.session])
            test.eq(found[second.session], true)
            test.eq(denied(host.receive(host.client("discovery-other", nil, nil, "bee.tests.memory:other"), "subscribe", {trait_id = host.TRAIT, idempotency_key = harness.key()})), "DENIED")
            test.eq(denied(host.receive(host.client("discovery-peer", nil, nil, nil, true), "subscribe", {trait_id = host.TRAIT, idempotency_key = harness.key()})), "DENIED")
        end)
        test.it("refuses a hook record impersonating a host session journal event", function()
            local session = host.open()
            local client = host.client("forged-" .. harness.key())
            local subscription = subscribed(session, client)
            local producer = harness.principal("sessions-owner", harness.ALL, host.WORKSPACE)
            harness.value(producer:call("record", {thread_id = session.thread, idempotency_key = harness.key(), kind = "observation", source = "hook",
                body = {type = "extension", event_key = harness.key(), data = {type = "extension", event_name = "bee.sessions.event", event_revision = "1",
                    payload_json = assert(json.encode({session_ref = session.session, kind = "work.settled", subject = "forged-work", data = {turn = "forged-turn"}}))}}}))
            host.turn(session, "one real fact")
            test.eq(#assert(bounds.array(page(session, client, subscription.subscription_id).events, 64)), 1)
        end)
        test.it("replays prompt content without adding a result committed after the page", function()
            local session = host.open(nil, "bee.tests.memory:all_events")
            local client = host.client("prompt-" .. harness.key())
            local subscription = subscribed(session, client)
            harness.value(session.owner:call("work_send", {session = session.session, input = "queued prompt", operation_key = harness.key()}))
            local before = page(session, client, subscription.subscription_id)
            local event = assert(bounds.object(assert(bounds.array(before.events, 64))[1]))
            test.eq(event.kind, "prompt.submitted")
            test.is_nil(assert(bounds.object(event.payload)).result)
            local reserved = harness.value(session.owner:call("turn_reserve", {session = session.session, operation_key = harness.key()}))
            local pulled = harness.value(session.owner:call("turn_pull", {turn = reserved.turn, claim = reserved.claim}))
            harness.value(session.owner:call("turn_accept", {turn = reserved.turn, claim = reserved.claim, input_digest = pulled.input_digest, checkpoint = {}, operation_key = harness.key()}))
            harness.value(session.owner:call("work_settle", {turn = reserved.turn, claim = reserved.claim, result = {state = "succeeded", schema = "bee:Text@1", value = {text = "later result"}}, operation_key = harness.key()}))
            local replayed = page(session, client, subscription.subscription_id)
            test.eq(replayed.page_id, before.page_id)
            test.is_nil(assert(bounds.object(assert(bounds.object(assert(bounds.array(replayed.events, 64))[1])).payload)).result)
        end)
        test.it("delivers every declared kind including the bounded final session event", function()
            local session = host.open(nil, "bee.tests.memory:all_events")
            local client = host.client("all-" .. harness.key())
            local subscription = subscribed(session, client)
            host.turn(session, "fact: quartz is hard", {
                {type = "session.state", state = "started"},
                {type = "tool.call", call_id = "read", tool_name = "Read", input = {text = "x"}},
                {type = "tool.result", call_id = "read", outcome = "succeeded", output = {text = "y"}},
            })
            harness.value(session.owner:call("session_transition", {session = session.session, state = "closed", expected_revision = 1, operation_key = harness.key()}))
            local delivered = page(session, client, subscription.subscription_id)
            local kinds: {[string]: boolean} = {}
            for _, raw in ipairs(assert(bounds.array(delivered.events, 64))) do kinds[assert(bounds.id(assert(bounds.object(raw)).kind))] = true end
            for _, kind in ipairs({"session.started", "session.ended", "prompt.submitted", "tool.before", "tool.after", "turn.completed"}) do test.eq(kinds[kind], true) end
            host.value(host.receive(client, "ack_page", {thread_id = session.thread, subscription_id = subscription.subscription_id, page_id = delivered.page_id,
                scanned_through = delivered.scanned_through, idempotency_key = harness.key()}))
            test.eq(#assert(bounds.array(page(session, client, subscription.subscription_id).events, 64)), 0)
        end)
        test.it("requires fresh consent after a registry upgrade and fences old pages", function()
            local session = host.open()
            local client = host.client("old-" .. harness.key())
            local subscription = subscribed(session, client)
            host.turn(session, "old fact")
            local old_page = page(session, client, subscription.subscription_id)
            local app = assert(registry.get(host.APP))
            local trait = assert(registry.get(host.TRAIT))
            local original_meta, original_data = app.meta, trait.data
            local meta: {[string]: unknown} = {}
            for key, value in pairs(assert(bounds.object(app.meta))) do meta[key] = value end
            local descriptor: {[string]: unknown} = {}
            for key, value in pairs(assert(bounds.object(meta.application))) do descriptor[key] = value end
            descriptor.revision = "2"; meta.application = descriptor; app.meta = meta
            trait.data = {prompt = "Remember facts from completed turns.", tools = {}, listens = {"turn.completed", "tool.after"}}
            local changes = registry.snapshot():changes(); changes:update(app); changes:update(trait); assert(changes:apply())
            local ok, cause = pcall(function()
                test.eq(denied(host.receive(client, "page", {thread_id = session.thread, subscription_id = subscription.subscription_id})), "DENIED")
                local upgraded = host.client("new-" .. harness.key(), nil, "2")
                test.eq(denied(host.receive(upgraded, "page", {thread_id = session.thread, subscription_id = subscription.subscription_id})), "DENIED")
                local binding = host.reattach(session)
                session.grant_id, session.approval_id = host.approve(binding)
                local reactivated = subscribed(session, upgraded)
                test.eq(reactivated.subscription_id, subscription.subscription_id)
                host.turn(session, "new approved fact")
                local next_page = page(session, upgraded, subscription.subscription_id)
                test.eq(#assert(bounds.array(next_page.events, 64)), 1)
                test.neq(next_page.page_id, old_page.page_id)
                test.eq(denied(host.receive(upgraded, "ack_page", {thread_id = session.thread, subscription_id = subscription.subscription_id,
                    page_id = old_page.page_id, scanned_through = old_page.scanned_through, idempotency_key = harness.key()})), "CONFLICT")
            end)
            app.meta, trait.data = original_meta, original_data
            local restore = registry.snapshot():changes(); restore:update(app); restore:update(trait); assert(restore:apply())
            if not ok then error(cause) end
        end)
        test.it("reattaches session selection and skips the interval after revocation", function()
            local session = host.open()
            local client = host.client("reapproved-" .. harness.key())
            local subscription = subscribed(session, client)
            host.turn(session, "before revocation")
            host.revoke(session)
            host.turn(session, "inactive fact")
            local binding = host.reattach(session)
            session.grant_id, session.approval_id = host.approve(binding)
            subscribed(session, client)
            host.turn(session, "after reapproval")
            local delivered = page(session, client, subscription.subscription_id)
            test.eq(#assert(bounds.array(delivered.events, 64)), 2)
            local another = host.reattach(session)
            local selection = assert((gateway.surface(another)))
            test.eq(selection.selection.active[1], host.TRAIT)
        end)
        test.it("fences owner incarnations while retaining committed activation intervals", function()
            local session = host.open()
            local client = host.client("owner-" .. harness.key())
            local subscription = subscribed(session, client)
            host.turn(session, "durable fact")
            local delivered = page(session, client, subscription.subscription_id)
            local db = harness.open()
            local incarnation = owner.establish(db)
            db:release()
            test.not_nil(incarnation)
            test.eq(denied(host.receive(client, "ack_page", {thread_id = session.thread, subscription_id = subscription.subscription_id,
                page_id = delivered.page_id, scanned_through = delivered.scanned_through, idempotency_key = harness.key()})), "CONFLICT")
            host.value(host.receive(client, "resume", {thread_id = session.thread, subscription_id = subscription.subscription_id, idempotency_key = harness.key()}))
            test.eq(#assert(bounds.array(page(session, client, subscription.subscription_id).events, 64)), 1)
        end)
        test.it("delivers only declared events of the approved session without thread membership", function()
            local session = host.open()
            local client = host.client("scoped-" .. harness.key())
            local subscription = subscribed(session, client)
            local other = harness.value(session.owner:call("session_create", {thread_id = session.thread, operation_key = harness.key()}))
            host.turn({session = assert(bounds.id(other.session)), thread = session.thread, binding = session.binding, owner = session.owner, grant_id = session.grant_id, approval_id = session.approval_id}, "foreign fact")
            host.turn(session, "fact: the moon is basalt")
            local delivered = page(session, client, subscription.subscription_id)
            local events = assert(bounds.array(delivered.events, 128))
            test.eq(#events, 1)
            local event = assert(bounds.object(events[1]))
            test.eq(event.kind, "turn.completed")
            test.eq(event.session_ref, session.session)
            test.eq(denied(host.receive(client, "read_after", {thread_id = session.thread, cursor = 0})), "DENIED")
        end)
        test.it("replays an outstanding page after app restart and acknowledges exactly", function()
            local session = host.open()
            local first = host.client("first-" .. harness.key())
            local subscription = subscribed(session, first)
            host.turn(session, "fact: cobalt is blue")
            local delivered = page(session, first, subscription.subscription_id, 1)
            local restarted = host.client("second-" .. harness.key())
            local again = page(session, restarted, subscription.subscription_id)
            test.eq(again.page_id, delivered.page_id)
            test.eq(again.scanned_through, delivered.scanned_through)
            local wrong = host.receive(restarted, "ack_page", {thread_id = session.thread, subscription_id = subscription.subscription_id,
                page_id = delivered.page_id, scanned_through = 0, idempotency_key = harness.key()})
            test.eq(denied(wrong), "CONFLICT")
            host.value(host.receive(restarted, "ack_page", {thread_id = session.thread, subscription_id = subscription.subscription_id,
                page_id = delivered.page_id, scanned_through = delivered.scanned_through, idempotency_key = harness.key()}))
            test.eq(#assert(bounds.array(page(session, restarted, subscription.subscription_id).events, 128)), 0)
        end)
        test.it("revokes during a page and refuses both page replay and late acknowledgement", function()
            local session = host.open()
            local client = host.client("revoke-" .. harness.key())
            local subscription = subscribed(session, client)
            host.turn(session, "fact: mercury is metal")
            local delivered = page(session, client, subscription.subscription_id)
            host.revoke(session)
            test.eq(denied(host.receive(client, "page", {thread_id = session.thread, subscription_id = subscription.subscription_id})), "DENIED")
            test.eq(denied(host.receive(client, "ack_page", {thread_id = session.thread, subscription_id = subscription.subscription_id,
                page_id = delivered.page_id, scanned_through = delivered.scanned_through, idempotency_key = harness.key()})), "DENIED")
        end)
        test.it("retains active intervals, skips inactive intervals and fences earlier pages", function()
            local session = host.open()
            local client = host.client("interval-" .. harness.key())
            local subscription = subscribed(session, client)
            host.turn(session, "active one")
            local old_page = page(session, client, subscription.subscription_id)
            local current = assert((gateway.surface(session.binding)))
            host.value(gateway.select_surface(session.binding, current.revision, {}, {}))
            host.turn(session, "inactive secret")
            current = assert((gateway.surface(session.binding)))
            host.value(gateway.select_surface(session.binding, current.revision, {host.TRAIT}, {}))
            host.turn(session, "active two")
            host.value(host.receive(client, "resume", {thread_id = session.thread, subscription_id = subscription.subscription_id, idempotency_key = harness.key()}))
            local delivered = page(session, client, subscription.subscription_id)
            test.eq(#assert(bounds.array(delivered.events, 128)), 2)
            test.eq(denied(host.receive(client, "ack_page", {thread_id = session.thread, subscription_id = subscription.subscription_id,
                page_id = old_page.page_id, scanned_through = old_page.scanned_through, idempotency_key = harness.key()})), "CONFLICT")
        end)
        test.it("denies other sessions, workspaces, apps, revisions and peers", function()
            local session = host.open()
            local client = host.client("identity-" .. harness.key())
            local subscription = subscribed(session, client)
            for _, stranger in ipairs({host.client("outside", string.rep("f",32)), host.client("other", nil, nil, "bee.tests.memory:other"),
                host.client("upgrade", nil, "2"), host.client("peer", nil, nil, nil, true)}) do
                test.eq(denied(host.receive(stranger, "page", {thread_id = session.thread, subscription_id = subscription.subscription_id})), "DENIED")
            end
            local other = harness.value(session.owner:call("session_create", {thread_id = session.thread, operation_key = harness.key()}))
            test.eq(denied(host.receive(client, "subscribe", {thread_id = session.thread, idempotency_key = harness.key(), filter = {session_ref = other.session, trait_id = session.trait_id or host.TRAIT}})), "DENIED")
        end)
    end)
end
return test.run_cases(define_tests)
