-- SPDX-License-Identifier: MIT
local test = require("test")
local sql = require("sql")
local outbox = require("outbox")
local function define_tests()
    test.describe("Pump scheduling", function()
        test.it("uses the later of retry and lease deadlines and ignores terminal rows", function()
            local db = assert(sql.get("bee.tests.threads:pump_deadline_db"))
            assert(db:execute("CREATE TABLE bee_thread_inbox_outbox (state TEXT, next_attempt_ms INTEGER, lease_until_ms INTEGER)"))
            test.eq(outbox.next_deadline(db), nil)
            assert(db:execute("INSERT INTO bee_thread_inbox_outbox VALUES ('queued', 100, 400), ('queued', 300, NULL), ('delivered', 1, NULL), ('exhausted', 2, NULL)"))
            test.eq(outbox.next_deadline(db), 300)
            assert(db:execute("DELETE FROM bee_thread_inbox_outbox WHERE next_attempt_ms = 300"))
            test.eq(outbox.next_deadline(db), 400)
            assert(db:execute("UPDATE bee_thread_inbox_outbox SET lease_until_ms = 50 WHERE state = 'queued'"))
            test.eq(outbox.next_deadline(db), 100)
            db:release()
        end)
    end)
end
return test.run_cases(define_tests)
