-- MIT. The recap is folded from records only, advances with its cursor
-- under a revision check, and a rebuild equals the incremental fold.
local test = require("test")
local harness = require("harness")
local recap = require("recap")
local function define_tests()
    test.describe("Thread recap", function()
        local alice = harness.principal("alice", harness.ALL)
        local bob = harness.principal("bob", {})
        test.it("folds messages, answers, marks and lifecycle into one checkpoint", function()
            local thread_id = harness.thread(alice, "Recap")
            harness.value(alice:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "bob", role = "participant", expected_revision = 1}))
            local empty = harness.value(bob:call("recap_read", {thread_id = thread_id}))
            test.eq(empty.revision, 0)
            test.eq(empty.checkpoint.messages, 0)
            local request = harness.value(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.request("q1", "please review the plan and reply", {"bob"})}))
            local first = harness.value(bob:call("recap_update", {thread_id = thread_id}))
            test.eq(first.revision, 1)
            test.eq(first.through_sequence, request.sequence)
            test.eq(first.checkpoint.messages, 1)
            test.eq(first.checkpoint.open_requests.q1, 1)
            test.eq(first.checkpoint.summary_lines[1], "alice: please review the plan and reply")
            local batch = harness.value(bob:call("claim", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "laptop"}))
            harness.value(bob:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.reply("a1", "looks good", thread_id, request.record_id, "succeeded")}))
            harness.value(alice:call("admit_action", {thread_id = thread_id, idempotency_key = harness.key(), action_id = "act", admitted = harness.admitted()}))
            local second = harness.value(bob:call("recap_update", {thread_id = thread_id}))
            test.eq(second.revision, 2)
            test.eq(second.through_sequence, harness.head_sequence(thread_id))
            test.eq(second.checkpoint.messages, 2)
            test.is_nil(second.checkpoint.open_requests.q1)
            test.eq(second.checkpoint.answered, 1)
            test.eq(second.checkpoint.deliveries.claimed, 1)
            test.eq(second.checkpoint.deliveries.delivered, 1)
            test.eq(second.checkpoint.actions.act, "admitted")
            test.eq(#batch.deliveries, 1)
            local same = harness.value(bob:call("recap_update", {thread_id = thread_id}))
            test.eq(same.revision, 2)
            test.eq(same.digest, second.digest)
            test.eq(harness.code(bob:call("recap_rebuild", {thread_id = thread_id})), "DENIED")
            local rebuilt = harness.value(alice:call("recap_rebuild", {thread_id = thread_id}))
            test.eq(rebuilt.revision, 1)
            test.eq(rebuilt.through_sequence, second.through_sequence)
            test.eq(rebuilt.digest, second.digest)
        end)
        test.it("recovers from a stale revision and never reads live tables", function()
            local thread_id = harness.thread(alice, "Stale")
            for index = 1, 3 do
                harness.value(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.message("m" .. tostring(index), "line " .. tostring(index))}))
            end
            local first = harness.value(alice:call("recap_update", {thread_id = thread_id}))
            test.eq(first.revision, 1)
            local db = harness.open()
            harness.execute(db, "UPDATE bee_thread_projections SET revision = 7 WHERE thread_id = ? AND kind = 'recap'", {thread_id})
            harness.execute(db, "UPDATE bee_thread_obligations SET state = 'abandoned' WHERE thread_id = ?", {thread_id})
            db:release()
            harness.value(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.message("m4", "line 4")}))
            local moved = harness.value(alice:call("recap_update", {thread_id = thread_id}))
            test.eq(moved.revision, 8)
            test.eq(moved.through_sequence, 4)
            test.eq(moved.checkpoint.messages, 4)
            test.eq(#moved.checkpoint.summary_lines, 4)
            local fresh = recap.empty()
            test.eq(fresh.schema, "bee.recap@1")
            local digest_a = recap.digest(recap.empty(), 0)
            local digest_b = recap.digest(recap.empty(), 1)
            test.neq(digest_a, digest_b)
        end)
        test.it("bounds summary lines and folds across many batches", function()
            local thread_id = harness.thread(alice, "Long")
            for index = 1, 70 do
                harness.value(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.message("m" .. tostring(index), tostring(index) .. " " .. string.rep("word ", 40))}))
            end
            local folded = harness.value(alice:call("recap_update", {thread_id = thread_id}))
            test.eq(folded.through_sequence, 70)
            test.eq(folded.checkpoint.messages, 70)
            test.eq(#folded.checkpoint.summary_lines, recap.MAX_SUMMARY_LINES)
            test.is_true(#folded.checkpoint.summary_lines[1] <= recap.MAX_LINE_BYTES + 3)
            test.is_true(folded.checkpoint.summary_lines[8]:find("alice: 70 ", 1, true) == 1)
        end)
    end)
end
local cases = test.run_cases(define_tests)
return {run = function(options) return cases(options) end}
