local test = require("test")
local harness = require("harness")
local bounds = require("bounds")
local host = require("host")
local function define_tests()
    test.describe("Threads search and timeline", function()
        test.it("installs a reference app, approves its trait, indexes facts durably and searches after restart", function()
            local session = host.open()
            local first = host.client("memory-first-" .. harness.key())
            host.turn(session, "fact: titan has methane lakes")
            local raw, err = first:call("bee.tests.memory:run", {session_ref = session.session, thread_id = session.thread, trait_id = host.TRAIT})
            assert(not err, tostring(err))
            local indexed = host.value(raw)
            test.eq(indexed.indexed, 1)
            local restarted = host.client("memory-restarted-" .. harness.key())
            raw, err = restarted:call("bee.tests.memory:run", {session_ref = session.session, thread_id = session.thread, trait_id = host.TRAIT})
            assert(not err, tostring(err)); test.eq(host.value(raw).indexed, 0)
            local found = host.value(host.receive(restarted, "search", {scope = {thread_ids = {indexed.index_thread}}, query = "methane"}))
            test.eq(found.total, 1)
            test.is_true(assert(bounds.text(assert(bounds.object(assert(bounds.array(found.items, 64))[1])).snippet)):find("methane lakes", 1, true) ~= nil)
            test.eq(assert(bounds.object(host.receive(restarted, "timeline", {thread_id = session.thread, after = 0}).error)).code, "DENIED")
            host.revoke(session)
            host.turn(session, "fact: forbidden new fact")
            raw, err = restarted:call("bee.tests.memory:run", {session_ref = session.session, thread_id = session.thread, trait_id = host.TRAIT})
            assert(not err, tostring(err)); test.eq(assert(bounds.object(raw)).ok, false)
            test.eq(host.value(host.receive(restarted, "search", {scope = {thread_ids = {indexed.index_thread}}, query = "forbidden"})).total, 0)
        end)
        local alice = harness.principal("search-alice", harness.ALL)
        local bob = harness.principal("search-bob", harness.ALL)
        local function append(client: harness.Client, thread: string, text: string): {[string]: unknown}
            return harness.value(client:call("record", {thread_id = thread, idempotency_key = harness.key(), kind = "message",
                body = {message_id = harness.key(), message_kind = "notification", sender_id = client.id, recipient_ids = {}, content = {text = text}}}))
        end
        test.it("filters authority before ranking and counting and pins continuation to committed heads", function()
            local visible = harness.thread(alice, "Visible")
            local secret = harness.thread(bob, "Hidden")
            append(alice, visible, "basalt first")
            append(alice, visible, "basalt second")
            append(bob, secret, "basalt basalt basalt secret")
            local scope = {thread_ids = {visible, secret}}
            local page = harness.value(alice:call("search", {scope = scope, query = "basalt", kinds = {"message"}, limit = 1}))
            test.eq(page.total, 2)
            local first = assert(bounds.object(assert(bounds.array(page.items, 128))[1]))
            test.eq(first.thread_id, visible)
            test.is_true(assert(bounds.text(first.snippet)):find("first", 1, true) ~= nil)
            append(alice, visible, "basalt newer")
            local next_page = harness.value(alice:call("search", {scope = scope, query = "basalt", kinds = {"message"}, cursor = page.next_cursor, limit = 1}))
            test.eq(next_page.total, 2)
            test.eq(#assert(bounds.array(next_page.items, 128)), 1)
            test.is_nil(next_page.next_cursor)
            test.neq(assert(bounds.object(assert(bounds.array(next_page.items, 128))[1])).record_id, first.record_id)
            test.eq(harness.code(bob:call("search", {scope = scope, query = "basalt", kinds = {"message"}, cursor = page.next_cursor})), "DENIED")
            test.eq(harness.code(alice:call("timeline", {thread_id = secret, after = 0})), "DENIED")
        end)
        test.it("rechecks authority on every continuation and returns stable timeline pages", function()
            local thread = harness.thread(alice, "Timeline")
            harness.value(alice:call("join", {thread_id = thread, member_id = bob.id, role = "observer", expected_revision = 1, idempotency_key = harness.key()}))
            append(alice, thread, "granite one")
            append(alice, thread, "granite two")
            local page = harness.value(bob:call("search", {scope = {thread_ids = {thread}}, query = "granite", limit = 1}))
            local timeline = harness.value(bob:call("timeline", {thread_id = thread, after = 0, limit = 1}))
            append(alice, thread, "granite three")
            local continuation = harness.value(bob:call("timeline", {thread_id = thread, cursor = timeline.next_cursor, limit = 64}))
            test.eq(#assert(bounds.array(continuation.items, 128)), 1)
            harness.value(alice:call("leave", {thread_id = thread, member_id = bob.id, expected_revision = 2, idempotency_key = harness.key()}))
            test.eq(harness.code(bob:call("search", {scope = {thread_ids = {thread}}, query = "granite", cursor = page.next_cursor})), "DENIED")
            test.eq(harness.code(bob:call("timeline", {thread_id = thread, cursor = timeline.next_cursor})), "DENIED")
        end)
    end)
end
return test.run_cases(define_tests)
