-- MIT. Owner-qualified send: the destination owner commits a forwarded
-- message under the caller node and idempotency key with the payload
-- digest the sender computed; the same identity replays the same record,
-- a different payload under it conflicts, a wrong digest is refused, a
-- non-member is denied, and status answers a sender that lost the reply
-- without a fresh send.
local test = require("test")
local harness = require("harness")
local sends = require("sends")
local function define_tests()
    test.describe("Owner-qualified send", function()
        local owner = harness.principal("owner-node-b", harness.ALL)
        local stranger = harness.principal("stranger", harness.ALL)
        test.it("commits once per caller node and key, replays, conflicts and reports status", function()
            local thread_id = harness.thread(owner, "Cross-node")
            local message = harness.message("m-1", "hello from node a")
            local digest = assert(sends.payload_digest(message))
            test.eq(harness.code(owner:call("send", {thread_id = thread_id, idempotency_key = "k-1", caller_node_id = "node-a", payload_digest = string.rep("0", 64), message = message})), "INVALID_ARGUMENT")
            local before = harness.value(owner:call("send_status", {thread_id = thread_id, idempotency_key = "k-1", caller_node_id = "node-a"}))
            test.eq(before.committed, false)
            local first = harness.value(owner:call("send", {thread_id = thread_id, idempotency_key = "k-1", caller_node_id = "node-a", payload_digest = digest, message = message}))
            test.eq(first.sequence, 1)
            test.eq(first.caller_node_id, "node-a")
            local replay = owner:call("send", {thread_id = thread_id, idempotency_key = "k-1", caller_node_id = "node-a", payload_digest = digest, message = message})
            test.eq(replay.replayed, true)
            test.eq(harness.value(replay).record_id, first.record_id)
            local other = harness.message("m-2", "a different payload")
            test.eq(harness.code(owner:call("send", {thread_id = thread_id, idempotency_key = "k-1", caller_node_id = "node-a", payload_digest = assert(sends.payload_digest(other)), message = other})), "CONFLICT")
            local second_node = harness.value(owner:call("send", {thread_id = thread_id, idempotency_key = "k-1", caller_node_id = "node-c", payload_digest = digest, message = message}))
            test.eq(second_node.sequence, 2)
            local status = harness.value(owner:call("send_status", {thread_id = thread_id, idempotency_key = "k-1", caller_node_id = "node-a"}))
            test.eq(status.committed, true)
            test.eq(status.record_id, first.record_id)
            test.eq(status.payload_digest, digest)
            test.eq(harness.code(stranger:call("send", {thread_id = thread_id, idempotency_key = "k-9", caller_node_id = "node-a", payload_digest = digest, message = message})), "DENIED")
            test.eq(harness.code(stranger:call("send_status", {thread_id = thread_id, idempotency_key = "k-1", caller_node_id = "node-a"})), "DENIED")
            local page = harness.value(owner:call("read_after", {thread_id = thread_id, cursor = 0, filter = {kinds = {"message"}}}))
            test.eq(#page.records, 2)
        end)
        test.it("binds the identity to the authenticated principal and covers context in the request digest", function()
            local thread_id = harness.thread(owner, "Two subjects")
            harness.value(owner:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "second", role = "participant", expected_revision = 1}))
            local second = harness.principal("second", harness.ALL)
            local message = harness.message("m-1", "same node, same key")
            local digest = assert(sends.payload_digest(message))
            local first = harness.value(owner:call("send", {thread_id = thread_id, idempotency_key = "k-1", caller_node_id = "node-a", payload_digest = digest, message = message}))
            local other = harness.value(second:call("send", {thread_id = thread_id, idempotency_key = "k-1", caller_node_id = "node-a", payload_digest = digest, message = message}))
            test.neq(other.record_id, first.record_id)
            test.eq(other.sequence, 2)
            local status = harness.value(second:call("send_status", {thread_id = thread_id, idempotency_key = "k-1", caller_node_id = "node-a"}))
            test.eq(status.record_id, other.record_id)
            local unknown = harness.value(second:call("send_status", {thread_id = thread_id, idempotency_key = "k-2", caller_node_id = "node-a"}))
            test.eq(unknown.committed, false)
            test.is_true(tostring(unknown.observation):find("no matching commit at this read", 1, true) ~= nil)
            test.eq(harness.code(owner:call("send", {thread_id = thread_id, idempotency_key = "k-1", caller_node_id = "node-a", payload_digest = digest, message = message, context = {correlation_id = "corr-1"}})), "CONFLICT")
        end)
    end)
end
return test.run_cases(define_tests)
