-- MIT. The consumer's subscription session, pure: transport loss
-- acknowledges nothing, reconnect continues the same lease, resumes under
-- a new owner incarnation or resets a closed subscription, stale pages are
-- dropped, and only an owner reply moves the cursor.
local test = require("test")
local session = require("session")
type Summary = {subscription_id: string, after_sequence: integer, lease_generation: integer, owner_incarnation: integer, owner_authority: string, closed: boolean}
local function summary(incarnation: integer, lease: integer, after: integer, closed: boolean): Summary
    return {subscription_id = "sub-1", after_sequence = after, lease_generation = lease, owner_incarnation = incarnation, owner_authority = "authority-1", closed = closed}
end
local function define_tests()
    test.describe("Subscription session", function()
        test.it("continues the same lease after a reconnect without acknowledging anything", function()
            local live = session.attach(summary(1, 1, 5, false))
            test.eq(live.state, "attached")
            test.is_true(session.accept_page(live, {page_id = "p-1", lease_generation = 1, from_sequence = 5, scanned_through = 9}))
            session.disconnect(live)
            test.eq(live.state, "detached")
            test.eq(live.after_sequence, 5)
            test.not_nil(live.outstanding)
            local _, action = session.reconnect(live, summary(1, 1, 5, false))
            test.eq(action, "continue")
            test.eq(live.state, "attached")
            test.eq((live.outstanding :: {[string]: unknown}).page_id, "p-1")
            local acknowledgment = assert(session.acknowledgment(live))
            test.eq(acknowledgment.page_id, "p-1")
            test.eq(acknowledgment.scanned_through, 9)
            session.acknowledged(live, 9)
            test.eq(live.after_sequence, 9)
            test.is_nil(live.outstanding)
        end)
        test.it("requires a resume under a new owner incarnation and drops pages of an earlier lease", function()
            local live = session.attach(summary(1, 1, 0, false))
            test.is_true(session.accept_page(live, {page_id = "p-1", lease_generation = 1, from_sequence = 0, scanned_through = 3}))
            session.disconnect(live)
            local _, action = session.reconnect(live, summary(2, 1, 0, false))
            test.eq(action, "resume")
            test.eq(live.state, "resume_required")
            test.is_nil(live.outstanding)
            local refused, reason = session.accept_page(live, {page_id = "p-2", lease_generation = 1, from_sequence = 0, scanned_through = 3})
            test.is_false(refused)
            test.eq(reason, "session is resume_required")
            local _, resume_error = session.resumed(live, summary(2, 2, 0, false))
            test.is_nil(resume_error)
            test.eq(live.state, "attached")
            test.eq(live.lease_generation, 2)
            local stale, stale_reason = session.accept_page(live, {page_id = "p-1", lease_generation = 1, from_sequence = 0, scanned_through = 3})
            test.is_false(stale)
            test.eq(stale_reason, "page belongs to lease generation 1, not 2")
            test.is_true(session.accept_page(live, {page_id = "p-3", lease_generation = 2, from_sequence = 0, scanned_through = 3}))
            local blocked, blocked_reason = session.accept_page(live, {page_id = "p-4", lease_generation = 2, from_sequence = 3, scanned_through = 6})
            test.is_false(blocked)
            test.eq(blocked_reason, "page p-3 is still outstanding")
        end)
        test.it("rejects stale summaries under the owner's generation order and never rolls the cursor back", function()
            local live = session.attach(summary(2, 3, 10, false))
            session.disconnect(live)
            local _, older_incarnation = session.reconnect(live, summary(1, 9, 20, false))
            test.eq(older_incarnation, "stale")
            test.eq(live.state, "detached")
            local _, older_lease = session.reconnect(live, summary(2, 2, 20, false))
            test.eq(older_lease, "stale")
            local _, behind = session.reconnect(live, summary(2, 3, 4, false))
            test.eq(behind, "stale")
            test.eq(live.after_sequence, 10)
            local _, closed_old = session.reconnect(live, summary(1, 1, 0, true))
            test.eq(closed_old, "stale")
            test.eq(live.state, "detached")
            local _, same = session.reconnect(live, summary(2, 3, 12, false))
            test.eq(same, "continue")
            test.eq(live.after_sequence, 12)
            local _, stale_resume = session.resumed(live, summary(2, 3, 12, false))
            test.eq(stale_resume, "stale summary: not a newer lease")
            local _, other = session.resumed(live, {subscription_id = "sub-9", after_sequence = 0, lease_generation = 9, owner_incarnation = 9, owner_authority = "authority-1", closed = false})
            test.eq(other, "summary names another subscription")
            local _, foreign = session.resumed(live, {subscription_id = "sub-1", after_sequence = 0, lease_generation = 9, owner_incarnation = 9, owner_authority = "authority-2", closed = false})
            test.eq(foreign, "summary comes from another owner authority; reset")
            local _, replaced_owner = session.reconnect(live, {subscription_id = "sub-1", after_sequence = 0, lease_generation = 99, owner_incarnation = 99, owner_authority = "authority-2", closed = false})
            test.eq(replaced_owner, "reset")
            test.eq(live.state, "reset_required")
            live.state = "detached"
            local _, fine = session.resumed(live, summary(3, 1, 12, false))
            test.is_nil(fine)
            test.eq(live.owner_incarnation, 3)
        end)
        test.it("resets a closed or replaced subscription and never acknowledges while detached", function()
            local live = session.attach(summary(1, 1, 0, false))
            session.disconnect(live)
            local _, none = session.acknowledgment(live)
            test.eq(none, "session is detached")
            local _, action = session.reconnect(live, summary(1, 1, 0, true))
            test.eq(action, "reset")
            test.eq(live.state, "closed")
            local other = session.attach(summary(1, 1, 0, false))
            local _, replaced = session.reconnect(other, {subscription_id = "sub-2", after_sequence = 0, lease_generation = 1, owner_incarnation = 1, owner_authority = "authority-1", closed = false})
            test.eq(replaced, "reset")
            test.eq(other.state, "reset_required")
        end)
    end)
end
return test.run_cases(define_tests)
