-- MIT. Subscriptions: one outstanding page, acknowledged by identity and
-- exact extent; filters are identities; leases fence stale pages; reading
-- never moves a cursor and never touches obligations.
local test = require("test")
local harness = require("harness")
local owner = require("owner")
local function define_tests()
    test.describe("Thread subscriptions", function()
        local alice = harness.principal("alice", harness.ALL)
        local bob = harness.principal("bob", {})
        local function thread_with(count: integer): string
            local thread_id = harness.thread(alice, "Subscribed")
            harness.value(alice:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "bob", role = "participant", expected_revision = 1}))
            for index = 1, count do
                harness.value(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.message("m" .. tostring(index), "n" .. tostring(index))}))
            end
            return thread_id
        end
        test.it("hands out one page at a time and advances only on an exact acknowledgment", function()
            local thread_id = thread_with(70)
            local created = harness.value(bob:call("subscribe", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "timeline", after_sequence = 0, durability = "durable"}))
            test.eq(created.after_sequence, 0)
            test.eq(created.lease_generation, 1)
            test.eq(harness.code(bob:call("subscribe", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "timeline", after_sequence = 5, durability = "durable"})), "CONFLICT")
            local first = harness.value(bob:call("page", {thread_id = thread_id, subscription_id = created.subscription_id}))
            test.eq(#first.records, 64)
            test.eq(first.from_sequence, 0)
            test.eq(first.scanned_through, 64)
            test.is_true(first.has_more)
            local repeated = harness.value(bob:call("page", {thread_id = thread_id, subscription_id = created.subscription_id}))
            test.eq(repeated.page_id, first.page_id)
            test.eq(#repeated.records, 64)
            test.eq(harness.code(bob:call("ack_page", {thread_id = thread_id, idempotency_key = harness.key(), subscription_id = created.subscription_id, page_id = first.page_id, scanned_through = 63})), "CONFLICT")
            test.eq(harness.code(bob:call("ack_page", {thread_id = thread_id, idempotency_key = harness.key(), subscription_id = created.subscription_id, page_id = "other", scanned_through = 64})), "CONFLICT")
            test.eq(harness.code(alice:call("ack_page", {thread_id = thread_id, idempotency_key = harness.key(), subscription_id = created.subscription_id, page_id = first.page_id, scanned_through = 64})), "DENIED")
            local acked = harness.value(bob:call("ack_page", {thread_id = thread_id, idempotency_key = harness.key(), subscription_id = created.subscription_id, page_id = first.page_id, scanned_through = 64}))
            test.eq(acked.after_sequence, 64)
            local second = harness.value(bob:call("page", {thread_id = thread_id, subscription_id = created.subscription_id}))
            test.neq(second.page_id, first.page_id)
            test.eq(#second.records, 6)
            test.eq(second.records[1].sequence, 65)
            test.eq(second.scanned_through, 70)
            test.is_false(second.has_more)
            test.eq(harness.code(bob:call("ack_page", {thread_id = thread_id, idempotency_key = harness.key(), subscription_id = created.subscription_id, page_id = second.page_id, scanned_through = 64})), "CONFLICT")
            harness.value(bob:call("ack_page", {thread_id = thread_id, idempotency_key = harness.key(), subscription_id = created.subscription_id, page_id = second.page_id, scanned_through = 70}))
            local empty = harness.value(bob:call("page", {thread_id = thread_id, subscription_id = created.subscription_id}))
            test.is_nil(empty.page_id)
            test.eq(#empty.records, 0)
            test.eq(empty.scanned_through, 70)
            test.eq(harness.code(bob:call("ack_page", {thread_id = thread_id, idempotency_key = harness.key(), subscription_id = created.subscription_id, page_id = second.page_id, scanned_through = 70})), "INVALID_STATE")
            local db = harness.open()
            local obligations = harness.query(db, "SELECT COUNT(*) AS count FROM bee_thread_obligations WHERE thread_id = ?", {thread_id})
            db:release()
            test.eq(obligations[1].count, 0)
        end)
        test.it("advances over an empty filtered page and keeps filters as identities", function()
            local thread_id = thread_with(3)
            local receipts = harness.value(bob:call("subscribe", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "settled", after_sequence = 0, filter = {kinds = {"receipt", "turn.end"}}, durability = "reconstructible"}))
            local wide = harness.value(bob:call("subscribe", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "settled", after_sequence = 0, filter = {kinds = {"turn.end", "receipt", "message"}}, durability = "reconstructible"}))
            test.neq(receipts.subscription_id, wide.subscription_id)
            local page = harness.value(bob:call("page", {thread_id = thread_id, subscription_id = receipts.subscription_id}))
            test.eq(#page.records, 0)
            test.eq(page.scanned_through, 3)
            test.not_nil(page.page_id)
            harness.value(bob:call("ack_page", {thread_id = thread_id, idempotency_key = harness.key(), subscription_id = receipts.subscription_id, page_id = page.page_id, scanned_through = 3}))
            local full = harness.value(bob:call("page", {thread_id = thread_id, subscription_id = wide.subscription_id}))
            test.eq(#full.records, 3)
            test.eq(harness.code(bob:call("subscribe", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "x", after_sequence = 0, filter = {kinds = {"ballot.cast"}}, durability = "durable"})), "INVALID_ARGUMENT")
        end)
        test.it("fences stale pages on resume and refuses closed or foreign subscriptions", function()
            local thread_id = thread_with(5)
            local created = harness.value(bob:call("subscribe", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "durable", after_sequence = 0, durability = "durable"}))
            local page = harness.value(bob:call("page", {thread_id = thread_id, subscription_id = created.subscription_id}))
            test.eq(harness.code(alice:call("page", {thread_id = thread_id, subscription_id = created.subscription_id})), "DENIED")
            local closed = harness.value(bob:call("unsubscribe", {thread_id = thread_id, idempotency_key = harness.key(), subscription_id = created.subscription_id}))
            test.is_true(closed.closed)
            test.eq(harness.code(bob:call("page", {thread_id = thread_id, subscription_id = created.subscription_id})), "INVALID_STATE")
            local resumed = harness.value(bob:call("resume", {thread_id = thread_id, idempotency_key = harness.key(), subscription_id = created.subscription_id}))
            test.eq(resumed.lease_generation, 2)
            test.is_false(resumed.closed)
            test.eq(harness.code(bob:call("ack_page", {thread_id = thread_id, idempotency_key = harness.key(), subscription_id = created.subscription_id, page_id = page.page_id, scanned_through = page.scanned_through})), "INVALID_STATE")
            local fresh = harness.value(bob:call("page", {thread_id = thread_id, subscription_id = created.subscription_id}))
            test.neq(fresh.page_id, page.page_id)
            test.eq(fresh.lease_generation, 2)
            test.eq(fresh.from_sequence, 0)
            local db = harness.open()
            local bumped = owner.establish(db)
            db:release()
            test.is_true(bumped > created.owner_incarnation)
            test.eq(harness.code(bob:call("ack_page", {thread_id = thread_id, idempotency_key = harness.key(), subscription_id = created.subscription_id, page_id = fresh.page_id, scanned_through = fresh.scanned_through})), "CONFLICT")
            local rebound = harness.value(bob:call("resume", {thread_id = thread_id, idempotency_key = harness.key(), subscription_id = created.subscription_id}))
            test.eq(rebound.owner_incarnation, bumped)
            local again = harness.value(bob:call("page", {thread_id = thread_id, subscription_id = created.subscription_id}))
            harness.value(bob:call("ack_page", {thread_id = thread_id, idempotency_key = harness.key(), subscription_id = created.subscription_id, page_id = again.page_id, scanned_through = 5}))
            local transient = harness.value(bob:call("subscribe", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "view", after_sequence = 0, durability = "reconstructible"}))
            harness.value(bob:call("unsubscribe", {thread_id = thread_id, idempotency_key = harness.key(), subscription_id = transient.subscription_id}))
            test.eq(harness.code(bob:call("resume", {thread_id = thread_id, idempotency_key = harness.key(), subscription_id = transient.subscription_id})), "INVALID_STATE")
        end)
    end)
end
local cases = test.run_cases(define_tests)
return {run = function(options) return cases(options) end}
