-- MIT. Waits return at once when something is pending, wake on a commit
-- while blocked, time out with a cursor, and remember only final outcomes.
local test = require("test")
local time = require("time")
local harness = require("harness")
local waits = require("waits")
local function define_tests()
    test.describe("Thread waits", function()
        local alice = harness.principal("alice", harness.ALL)
        local bob = harness.principal("bob", {})
        local function shared(): string
            local thread_id = harness.thread(alice, "Waiting")
            harness.value(alice:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "bob", role = "participant", expected_revision = 1}))
            return thread_id
        end
        test.it("bounds the effective wait by the ceiling and the transport budget", function()
            test.eq(waits.effective_wait(5000, nil), 5000)
            test.eq(waits.effective_wait(90000, nil), 60000)
            test.eq(waits.effective_wait(60000, 5000), 4000)
            test.eq(waits.effective_wait(60000, 500), 0)
        end)
        test.it("returns at once with claims and records when the thread already moved", function()
            local thread_id = shared()
            local request = harness.value(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.request("q1", "now", {"bob"})}))
            local key = harness.key()
            local ready = harness.value(bob:call("wait", {thread_id = thread_id, idempotency_key = key, consumer_id = "laptop", after_sequence = 0, wait_ms = 5000}))
            test.eq(ready.status, "ready")
            test.eq(#ready.deliveries, 1)
            test.eq(ready.deliveries[1].message_id, "q1")
            test.eq(#ready.records, 2)
            test.eq(ready.records[1].sequence, request.sequence)
            test.eq(ready.records[2].kind, "delivery.mark")
            local again = bob:call("wait", {thread_id = thread_id, idempotency_key = key, consumer_id = "laptop", after_sequence = 0, wait_ms = 5000})
            test.is_true(again.replayed)
            test.eq(harness.value(again).batch_id, ready.batch_id)
            local nothing = harness.value(bob:call("wait", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "laptop", after_sequence = ready.scanned_through, wait_ms = 0}))
            test.eq(nothing.status, "timeout")
            test.eq(#nothing.deliveries, 0)
            test.eq(nothing.scanned_through, ready.scanned_through)
        end)
        test.it("wakes a blocked wait when a message commits and times out otherwise", function()
            local thread_id = shared()
            local started = time.now():unix_nano()
            local blocked = bob:start("wait", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "laptop", after_sequence = 0, wait_ms = 8000})
            time.sleep("300ms")
            harness.value(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.request("q1", "wake up", {"bob"})}))
            local woke = harness.value(harness.await(blocked))
            local elapsed_ms = (time.now():unix_nano() - started) / 1000000
            test.eq(woke.status, "ready")
            test.eq(#woke.deliveries, 1)
            test.is_true(elapsed_ms < 4000)
            local key = harness.key()
            local quiet_started = time.now():unix_nano()
            local quiet = harness.value(bob:call("wait", {thread_id = thread_id, idempotency_key = key, consumer_id = "laptop", after_sequence = woke.scanned_through, wait_ms = 400}))
            local quiet_ms = (time.now():unix_nano() - quiet_started) / 1000000
            test.eq(quiet.status, "timeout")
            test.is_true(quiet_ms >= 350)
            test.eq(quiet.scanned_through, woke.scanned_through)
            local replayed = bob:call("wait", {thread_id = thread_id, idempotency_key = key, consumer_id = "laptop", after_sequence = woke.scanned_through, wait_ms = 400})
            test.is_true(replayed.replayed)
            test.eq(harness.code(bob:call("wait", {thread_id = thread_id, idempotency_key = key, consumer_id = "phone", after_sequence = woke.scanned_through, wait_ms = 400})), "CONFLICT")
        end)
        test.it("never claims for the wrong actor and refuses observers", function()
            local thread_id = shared()
            harness.value(alice:call("join", {thread_id = thread_id, idempotency_key = harness.key(), member_id = "carol", role = "observer", expected_revision = 2}))
            local carol = harness.principal("carol", {})
            harness.value(alice:call("record", {thread_id = thread_id, idempotency_key = harness.key(), kind = "message", body = harness.request("q1", "for bob", {"bob"})}))
            test.eq(harness.code(carol:call("wait", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "c", after_sequence = 0, wait_ms = 0})), "DENIED")
            local alices = harness.value(alice:call("wait", {thread_id = thread_id, idempotency_key = harness.key(), consumer_id = "a", after_sequence = 0, wait_ms = 0}))
            test.eq(#alices.deliveries, 0)
            test.eq(alices.status, "ready")
            test.eq(#alices.records, 1)
        end)
    end)
end
local cases = test.run_cases(define_tests)
return {run = function(options) return cases(options) end}
