-- MIT. The docs request boundary: every operation, every field and every bound
-- is refused with a stable message before the corpus is consulted.
local test = require("test")
local protocol = require("protocol")
local function define_tests()
    test.describe("Docs request protocol", function()
        test.it("accepts list, search and read and refuses anything else", function()
            local listed = protocol.decode({operation = "list"})
            test.eq(listed and listed.operation, "list")
            test.eq(listed and listed.limit, nil)
            local filtered = protocol.decode({operation = "list", topic = "cluster", offset = 2, limit = 64})
            test.eq(filtered and filtered.topic, "cluster")
            test.eq(filtered and filtered.offset, 2)
            test.eq(filtered and filtered.limit, 64)
            local searched = protocol.decode({operation = "search", query = "subscription", topic = "cluster", limit = 16})
            test.eq(searched and searched.query, "subscription")
            local read = protocol.decode({operation = "read", id = "runtime/lua/core/process", section = "process-management",
                offset = 0, limit = 16384})
            test.eq(read and read.id, "runtime/lua/core/process")
            test.eq(read and read.section, "process-management")
            test.eq(read and read.limit, 16384)
            local _, unknown = protocol.decode({operation = "delete"})
            test.eq(unknown, "unknown docs operation")
            local _, missing = protocol.decode({})
            test.eq(missing, "unknown docs operation")
            local _, notobject = protocol.decode("list")
            test.eq(notobject, "request must be an object")
        end)
        test.it("refuses unknown fields per operation", function()
            local _, cross = protocol.decode({operation = "list", query = "x"})
            test.eq(cross, "unknown field query")
            local _, reader = protocol.decode({operation = "read", id = "a", topic = "cluster"})
            test.eq(reader, "unknown field topic")
            local _, searcher = protocol.decode({operation = "search", query = "x", id = "a"})
            test.eq(searcher, "unknown field id")
        end)
        test.it("bounds every count, every id and every query", function()
            local _, topic = protocol.decode({operation = "list", topic = "Cluster"})
            test.eq(topic, "topic must be a lowercase topic name")
            local _, blanks = protocol.decode({operation = "search", query = ""})
            test.eq(blanks, "query must be nonempty text of at most 256 bytes")
            local _, long_query = protocol.decode({operation = "search", query = string.rep("x", 257)})
            test.eq(long_query, "query must be nonempty text of at most 256 bytes")
            local _, newline = protocol.decode({operation = "search", query = "two\nlines"})
            test.eq(newline, "query must be one line")
            local _, list_over = protocol.decode({operation = "list", limit = protocol.MAX_LIST + 1})
            test.eq(list_over, "limit must be between 1 and 64")
            local _, list_zero = protocol.decode({operation = "list", limit = 0})
            test.eq(list_zero, "limit must be between 1 and 64")
            local _, search_over = protocol.decode({operation = "search", query = "x", limit = protocol.MAX_RESULTS + 1})
            test.eq(search_over, "limit must be between 1 and 16")
            local _, read_over = protocol.decode({operation = "read", id = "a", limit = protocol.MAX_READ_BYTES + 1})
            test.eq(read_over, "limit must be between 1 and 16384")
            local _, negative = protocol.decode({operation = "read", id = "a", offset = -1})
            test.eq(negative, "offset must be a nonnegative integer")
            local _, no_id = protocol.decode({operation = "read"})
            test.eq(no_id, "id must be a corpus document id")
            local _, traversal = protocol.decode({operation = "read", id = "../../etc/passwd"})
            test.eq(traversal, "id must be a corpus document id")
            local _, space = protocol.decode({operation = "read", id = "a b"})
            test.eq(space, "id must be a corpus document id")
            local _, section = protocol.decode({operation = "read", id = "a", section = "Not An Anchor"})
            test.eq(section, "section must be a heading anchor")
        end)
        test.it("keeps the tool schema and the decoder in one place", function()
            -- The advertised bounds are the decoder's own constants, so the
            -- description an agent reads cannot drift from what is accepted.
            test.eq(protocol.MAX_LIST, 64)
            test.eq(protocol.MAX_RESULTS, 16)
            test.eq(protocol.MAX_READ_BYTES, 16384)
            test.eq(protocol.MAX_QUERY_BYTES, 256)
        end)
    end)
end
return test.run_cases(define_tests)
