-- SPDX-License-Identifier: MIT
local test = require("test")
local process = require("process")
local events = require("events")
local channel = require("channel")
local time = require("time")
local system = require("system")
local uuid = require("uuid")
local sql = require("sql")
local runs = require("runs")
local demand = require("demand")
local owners = require("owners")
local SERVICE = "bee.node.service:tests_service"
local function stopped(updates: events.Subscription)
    local deadline = time.after("10s")
    while true do
        local state = assert(system.supervisor.state(SERVICE))
        if state.desired == "stopped" and (state.status == "stopped" or state.status == "exited") then return end
        local selected = channel.select({updates:channel():case_receive(), deadline:case_receive()})
        assert(selected.channel ~= deadline, "test runner does not drain and stop: " .. tostring(state.status) .. "/" .. tostring(state.desired))
    end
end
local function create(): string
    local id = assert(uuid.v7())
    assert(runs.create({run_id = id, workspace_id = string.rep("c",32), actor_id = "demand-test",
        overlay = "", application = "bee.tests.node.hub_tests_fixture:application", plan = {}, state = "pending", result = nil}))
    return id
end
local function complete(id: string)
    local deadline = time.after("10s")
    local changes = assert(events.subscribe("supervisor", "service.update"))
    while true do
        local row = assert(runs.get(id))
        if row.state == "complete" then break end
        local selected = channel.select({changes:channel():case_receive(), time.after("10ms"):case_receive(), deadline:case_receive()})
        assert(selected.channel ~= deadline, "pending run does not complete")
    end
    changes:close()
end
local function define_tests()
    test.describe("Test runner demand", function()
        test.it("dispatches to an absent runner and stops only after durable completion", function()
            local updates = assert(events.subscribe("supervisor", "service.update"))
            test.eq(process.registry.lookup("bee.node.tests", process.registry.LOCAL), nil)
            local id = create()
            assert(demand.wake("bee.node.tests"))
            complete(id)
            stopped(updates)
            updates:close()
        end)
        test.it("recovers pending rows through the boot backlog path", function()
            local updates = assert(events.subscribe("supervisor", "service.update"))
            stopped(updates)
            local id = create()
            owners.recover(owners.discover(nil), nil)
            complete(id)
            stopped(updates)
            updates:close()
        end)
        test.it("interrupts the previous running row once and resumes pending work on restart", function()
            local updates = assert(events.subscribe("supervisor", "service.update"))
            stopped(updates)
            local running, pending = assert(uuid.v7()), assert(uuid.v7())
            local db = assert(sql.get("bee:db"))
            local tx = assert(db:begin())
            for _, row in ipairs({{id = running, state = "running"}, {id = pending, state = "pending"}}) do
                assert(tx:execute("INSERT INTO bee_node_test_runs (run_id, workspace_id, actor_id, overlay, application, plan_json, state, created_ms) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                    {row.id, string.rep("c",32), "demand-test", "", "bee.tests.node.hub_tests_fixture:application", "[]", row.state, 0}))
            end
            assert(tx:commit())
            db:release()
            assert(demand.wake("bee.node.tests"))
            complete(pending)
            stopped(updates)
            test.eq(assert(runs.get(running)).state, "interrupted")
            test.eq(assert(runs.get(pending)).state, "complete")
            updates:close()
        end)
        test.it("retains an enqueue when a drained runner is stopping", function()
            local updates = assert(events.subscribe("supervisor", "service.update"))
            local quiet = assert(process.listen("bee.test.node.quiet", {message = true}))
            assert(process.registry.register("bee.test.node.quiet"))
            local first = create()
            assert(demand.wake("bee.node.tests"))
            complete(first)
            local selected = channel.select({quiet:case_receive(), time.after("10s"):case_receive()})
            test.eq(selected.channel, quiet)
            local owner = tostring(selected.value:from())
            local second = create()
            assert(demand.wake("bee.node.tests"))
            process.registry.unregister("bee.test.node.quiet")
            assert(process.send(owner, "bee.test.node.quiet.release", {}))
            complete(second)
            stopped(updates)
            process.unlisten(quiet)
            updates:close()
        end)
    end)
end
return test.run_cases(define_tests)
